chartConfig:
  config:
    eChartsConfig:
      series:
        - encode:
            xRef:
              field: mart_spotify_audio_track_genre
            yRef:
              field: mart_spotify_audio_track_count
          type: bar
    layout:
      flipAxes: true
      xField: mart_spotify_audio_track_genre
      yField:
        - mart_spotify_audio_track_count
  type: cartesian
description: null
metricQuery:
  additionalMetrics: []
  customDimensions: []
  dimensions:
    - mart_spotify_audio_track_genre
  exploreName: mart_spotify_audio
  filters: {}
  limit: 20
  metricOverrides: {}
  metrics:
    - mart_spotify_audio_track_count
  sorts:
    - descending: true
      fieldId: mart_spotify_audio_track_count
  tableCalculations: []
name: Tracks per genre (top 20)
slug: tracks-per-genre-top-20
spaceSlug: shared
tableConfig:
  columnOrder:
    - mart_spotify_audio_track_genre
    - mart_spotify_audio_track_count
tableName: mart_spotify_audio
version: 1
