# B138 — the 7 remaining active repos, codified in IaC. Generated by `tofu plan -generate-config-out` from the
# LIVE repos (accurate, not hand-guessed — B137 lesson), then cleaned: the experimental generator emits
# read-only/create-only cruft (etag, fork, gitignore_template, license_template, source_owner, source_repo,
# archive_on_destroy) that was stripped here — same fields repo.tf drops for weyland_lab. etag especially MUST
# go: it changes on every repo change, so keeping it makes every plan perpetually dirty and defeats drift
# detection. Deprecated `vulnerability_alerts` is intentionally omitted (use github_repository_vulnerability_alerts).

resource "github_repository" "Algopedia" {
  name                        = "Algopedia"
  visibility                  = "public"
  allow_auto_merge            = false
  allow_forking               = true
  allow_merge_commit          = true
  allow_rebase_merge          = true
  allow_squash_merge          = true
  allow_update_branch         = false
  archived                    = false
  auto_init                   = false
  delete_branch_on_merge      = false
  has_discussions             = false
  has_issues                  = true
  has_projects                = true
  has_wiki                    = true
  is_template                 = false
  merge_commit_message        = "PR_TITLE"
  merge_commit_title          = "MERGE_MESSAGE"
  squash_merge_commit_message = "COMMIT_MESSAGES"
  squash_merge_commit_title   = "COMMIT_OR_PR_TITLE"
  topics                      = []
  web_commit_signoff_required = false
  security_and_analysis {
    secret_scanning { status = "disabled" }
    secret_scanning_push_protection { status = "disabled" }
  }
}

resource "github_repository" "ServiceTransformation" {
  name                        = "ServiceTransformation"
  visibility                  = "public"
  allow_auto_merge            = false
  allow_forking               = true
  allow_merge_commit          = true
  allow_rebase_merge          = true
  allow_squash_merge          = true
  allow_update_branch         = false
  archived                    = false
  auto_init                   = false
  delete_branch_on_merge      = false
  has_discussions             = false
  has_issues                  = true
  has_projects                = true
  has_wiki                    = true
  is_template                 = false
  merge_commit_message        = "PR_TITLE"
  merge_commit_title          = "MERGE_MESSAGE"
  squash_merge_commit_message = "COMMIT_MESSAGES"
  squash_merge_commit_title   = "COMMIT_OR_PR_TITLE"
  topics                      = []
  web_commit_signoff_required = false
  security_and_analysis {
    secret_scanning { status = "enabled" }
    secret_scanning_push_protection { status = "enabled" }
  }
}

resource "github_repository" "emangini_tailwind_nextjs_contentlayer" {
  name                        = "emangini-tailwind-nextjs-contentlayer"
  visibility                  = "public"
  homepage_url                = "https://tailwind-css-starter-blog-three-xi.vercel.app"
  allow_auto_merge            = false
  allow_forking               = true
  allow_merge_commit          = true
  allow_rebase_merge          = true
  allow_squash_merge          = true
  allow_update_branch         = false
  archived                    = false
  auto_init                   = false
  delete_branch_on_merge      = false
  has_discussions             = false
  has_issues                  = true
  has_projects                = true
  has_wiki                    = false
  is_template                 = false
  merge_commit_message        = "PR_TITLE"
  merge_commit_title          = "MERGE_MESSAGE"
  squash_merge_commit_message = "COMMIT_MESSAGES"
  squash_merge_commit_title   = "COMMIT_OR_PR_TITLE"
  topics                      = []
  web_commit_signoff_required = false
  security_and_analysis {
    secret_scanning { status = "disabled" }
    secret_scanning_push_protection { status = "disabled" }
  }
}

resource "github_repository" "startme_curator" {
  name                        = "startme-curator"
  visibility                  = "private"
  description                 = "Taxonomy database + save-time bookmark classifier for start.me (weyland B132 / EMA-193)"
  allow_auto_merge            = false
  allow_forking               = true
  allow_merge_commit          = true
  allow_rebase_merge          = true
  allow_squash_merge          = true
  allow_update_branch         = false
  archived                    = false
  auto_init                   = false
  delete_branch_on_merge      = false
  has_discussions             = false
  has_issues                  = true
  has_projects                = true
  has_wiki                    = true
  is_template                 = false
  merge_commit_message        = "PR_TITLE"
  merge_commit_title          = "MERGE_MESSAGE"
  squash_merge_commit_message = "COMMIT_MESSAGES"
  squash_merge_commit_title   = "COMMIT_OR_PR_TITLE"
  topics                      = []
  web_commit_signoff_required = false
}

resource "github_repository" "stud_io" {
  name                        = "stud.io"
  visibility                  = "public"
  allow_auto_merge            = false
  allow_forking               = true
  allow_merge_commit          = false
  allow_rebase_merge          = false
  allow_squash_merge          = true
  allow_update_branch         = false
  archived                    = false
  auto_init                   = false
  delete_branch_on_merge      = false
  has_discussions             = false
  has_issues                  = true
  has_projects                = true
  has_wiki                    = true
  is_template                 = false
  merge_commit_message        = "PR_TITLE"
  merge_commit_title          = "MERGE_MESSAGE"
  squash_merge_commit_message = "BLANK"
  squash_merge_commit_title   = "PR_TITLE"
  topics                      = []
  web_commit_signoff_required = false
  security_and_analysis {
    secret_scanning { status = "disabled" }
    secret_scanning_push_protection { status = "disabled" }
  }
}

resource "github_repository" "freejack" {
  name                        = "freejack"
  visibility                  = "private"
  allow_auto_merge            = false
  allow_forking               = true
  allow_merge_commit          = true
  allow_rebase_merge          = true
  allow_squash_merge          = true
  allow_update_branch         = false
  archived                    = false
  auto_init                   = false
  delete_branch_on_merge      = false
  has_discussions             = false
  has_issues                  = true
  has_projects                = true
  has_wiki                    = true
  is_template                 = false
  merge_commit_message        = "PR_TITLE"
  merge_commit_title          = "MERGE_MESSAGE"
  squash_merge_commit_message = "COMMIT_MESSAGES"
  squash_merge_commit_title   = "COMMIT_OR_PR_TITLE"
  topics                      = []
  web_commit_signoff_required = false
}

resource "github_repository" "MyBodyGraph" {
  name                        = "MyBodyGraph"
  visibility                  = "public"
  allow_auto_merge            = false
  allow_forking               = true
  allow_merge_commit          = true
  allow_rebase_merge          = true
  allow_squash_merge          = true
  allow_update_branch         = false
  archived                    = false
  auto_init                   = false
  delete_branch_on_merge      = false
  has_discussions             = false
  has_issues                  = true
  has_projects                = true
  has_wiki                    = true
  is_template                 = false
  merge_commit_message        = "PR_TITLE"
  merge_commit_title          = "MERGE_MESSAGE"
  squash_merge_commit_message = "COMMIT_MESSAGES"
  squash_merge_commit_title   = "COMMIT_OR_PR_TITLE"
  topics                      = []
  web_commit_signoff_required = false
  security_and_analysis {
    secret_scanning { status = "enabled" }
    secret_scanning_push_protection { status = "enabled" }
  }
}
