apiVersion: v1
kind: ConfigMap
metadata:
  name: dagster-workspace
  namespace: weyland
data:
  workspace.yaml: |
    load_from:
      - grpc_server:
          host: dagster-user-code
          port: 4000
          location_name: weyland_pipeline
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dagster-config
  namespace: weyland
data:
  dagster.yaml: |
    storage:
      postgres:
        postgres_db:
          username: weyland
          password:
            env: DAGSTER_PG_PASSWORD
          hostname: weyland-postgres.weyland.svc.cluster.local
          db_name: dagster
          port: 5432
    run_launcher:
      module: dagster.core.launcher
      class: DefaultRunLauncher
    run_coordinator:
      module: dagster.core.run_coordinator
      class: DefaultRunCoordinator
