---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: weyland-operator-secret
  namespace: weyland
spec:
  encryptedData:
    TELEGRAM_ALLOWED_USERS: AgBrSLE4QVYfp6WojJ5MrzjXP6Bas43OTMqO8EMK+ycyL0F/Ask1XYWvNhP8o6wfibXOwmN0jhHH9FPAGrLrNTi3K5aVOCxUfitbf37SEvapUXFc67a6rxPU6zyslLVPC4bSCieLSHvuX6iXlOC4lZoC0bl3xYK/Xhg/jGbC8YxDF4vAdLWBwLFDGyvHs2Yz2TwBRg+Gi/zbVYofmFYlmMQcxF+3FuQFIj2U4O87xY0i2APnKm0lRXWUBJTIbQBvBKONcAQjA026qBJ8GS8fD4IbbC5uicbmX8LYUXp50LCJxskx/YfTA/o9VBeJ0JSD8xeL6HtUSmnt/ieodYVS8BxdJ/z66B74F6exMaUVI3MOj2usbc3eI3oOIVqJLYj24F0mm4CLd3aiNagfeCjbJFi5wccGh17YKd8HLbP9ntEWv6KogjP3CA0fQ9jku83DoxqS7f5OASaM05dVLrQfN/5lt52Y+I9ZjDjvNeAK/S6BaFRNp/Xm7VrwafWLu8taUeyBPFl6GfYrSeOO1ar4zAz69H096nmMGcdcBuAV5SpVGbTSQF4mmoYzBoklzSJYBDYOvRHomrOgUpmAGdK0RHN6zm0KYcUS2RcAqH2DUbCUbyeeVrHGGNCG/SBT8cxMOogEbOLl7077F5Pm2N0tvpV4RFXf3PQDlFcTK6qdTljLvM1PebMBL0KSMwh4iQr2EwfTmD9obapjjVBu
    TELEGRAM_BOT_TOKEN: AgCRebURrNW4OrYWwf/hss3i0lihXv9HZw/iAXdDaivCR5c/J+hX7WN5sz4C1cWkOcI84fHVmXgzgRfvi+JzA+aEJ48pCA6vD2bzyqEbKsJi/RVm1A/Btp2QT1Q2Q7naNHGRQOWUQpaKvYM7oHZYJbFQevMjMe3fq+RM+A9MgOgPpWd+Asf4x/2DAk3OjNPE0D3iMwL7EpYVMaxNN/ej/ycfrZQ7IwP9a8xNye7WMjhYCvFWDbvDsI2WwIFnK4D19QI3LljHbTw1l1su9qkNFF7m7NFObB9EWy/NVXdb98anTx1GdeVUIaaPEv+8oGCA/5414sNEnyysXyK/Lr1MfGrbnSMjYIum/WDrdVKOhLjDqV9boYR4DNuI2XLn850qZoAT95qKzzU2yu1xHnp2jgn7tKHDDAzsFHmTWA5ajf5elv2bfBUU+ataMKcZnLb2nas2YSFkdriLuHoYCjR7pRZ0DMOK+5DGFhLLP1eEzHNsT4O3TmpNgnv1+CY1tt3Ej4AGs8iKFP9Kgigsobf23F+PiH6/9a5tlMK0XSDmweZsQc22rX5TmCpo0owvPjHk6odyAR/vGJW2YGos3BSInn4i+OqZ4sqPiFKkiKL4gz5PcBIHRurpPAkcKYT0O6P1K+xsHJEEjMvlw9jaQDVE1CA6QgvhjvqnxPmVtuEt5xh4gcIV/qHkYQIuIvEAU8XPZN7G2S9sbH4xzmpRO7CtTDj/BRC6HfVpXVsinvsNbq74dLI06tnkMWOwBcvA6sKf
  template:
    metadata:
      name: weyland-operator-secret
      namespace: weyland
