---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: trino-metrics-auth
  namespace: data-mesh
spec:
  encryptedData:
    password: AgBZzMqp/OuNhfl+3LvHWReE9VcsnbfDMadcEp9IdYW6ClZiwQ5fxyFamlMc98dC57l5r2IuyMTphQZNPoQ0jqJ1IVhFnoytMPpvAbV7faOev06wCUZr4hNeBpFI52/0M38M1n1S+5pXdQ4BuAvi8Mjw9Z5aoSbCYSDnInJkS9Rmo1h5Zr37/e4Bso95TJvMQd2YU5Ly+R0oOyuFMZleTFKSxBCoWKKOagQ6nLshXp9JGy/KE+5w8xAL8hNWtWSpnNTluu6zewIkjxBaI9W6pvj8aaS1i3EeVqri4O690epY+W/2KfYLDXD8hfL+YQCQm+AbgXX4oodVdTiLVfwjdf5bk93MUL2qf7JwpSTicm2j+AdMluXmg0MgXiaR10pC4AXkDEms5GjNUHF7wPycrI+JZLsSHUt0+cCB3tusDnCztr17qf9kcUqNOCJG5S/NlpSdotGjFgp8QU9si7c+wlR5Al1btnDeD5osDWuIAs9/a5K2+yIG05NdjZrTVJ2i2MKI61lpS+SkUgYXNUHBVXdQoLOaamsggoyS1dX5CIRzFyxbJGPnGXIMQBhHavURjT1Oq7bCYuD1X6J2f0S6krRpzS+vmLApgTjpcTaUoUKOimmIUcX5/BaCv4w9ultPK99v9ddA6NezK1BOGGXjgiW6b9I6CjvTBr6qJ08IZPHR+EqkUvssXrVe7UdoshiJhbc=
    username: AgBq4gZQ3pQ+ltKXFj6RixCyQuHJfnvYOHeRbajqTkpdGvYU4ju3IU/+ytz3Cau09B2d0GSvYgtAF6jLNsbxxP5Jk4mLgBElXA2hYkiWpbGjKVPp7JbuVLKXrsQpc0U83sAcNC2NOyQ8ezYCC5qToP1ypTv3nJJPkR6R2eQAAvZZPkO1edYLPSzmbl5tdl+kNwyOtuKx0fp2KiNiPA3CUcYMby6ZTNWPPUijeFtP7vmwSI/8f6lLMdPC7Rftf1pZW4gYNlf3KWtJ0rSFitLuHCK9w6xiHSgUyUXqOrTOOlNQVFwvNvbR+VDF2NYF3dPlkEK2U8XeJMDUK/lCvy1F8v9HyGG8FbJIOV/TeKkNbi9YJb4WuyK0BhGjEnJIIIVkxP1PdKNlhqQPoMjVv4J5YMMvq0n1edArnsf4WrqF2OOSECkxGvwShxwo3HAxgoeWprjHmEgjjToSH63hd580BQwXxxum+VTvcQwEvVqJo7uTLQ16mwwIigSHLTW6zqG8dOvmiN6pOQaA5L88ns0gzaW78Kgao+t9I92BKUZop3M+fRVBCY3dzHLcBaeDXc4pFbS71+g8MK9RsA5L2SB7Ra8PCaMsMIksD8UcEgjy1oXx8uehR+piSvrVKHpnhv9fYwW1hwtzvAVV3JBQzXW4GCEg4UkUncGOrJck3X+amY+AJgjIQ67PgJmpDTx1MdH2q1wysBjtADe0qXNz
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: trino-metrics-auth
      namespace: data-mesh
    type: Opaque
