---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: lakefs-creds
  namespace: data-mesh
spec:
  encryptedData:
    LAKEFS_ACCESS_KEY_ID: AgBL1ESXu7xZDR7fBrNhnuBgsmqUT3oY+h4xIMhI21qhF4K5XOioj0miskh9USYdMs73+0qwKmAyyXs+rN/MNEL7UE5/RwvPon+BnjstAbrcWbqqkQLoi7JpBOGfWADwVJ+3uuo6oXl1Jac5Wi292h9gmH8dwCi2Uc8NQlI++CJ4SwAEfHlOD9RLsyIQ4z/7e1mz2N7Kk5buZWBO5bA/xzDUW2GPuDstScNFlmnCMeyl/al4xl4UeWyUe/ePsIk2/oiWhDUeywUT/LHja9sDigyjSxbK1G6Veia2OEr4LPlo32bsZln/1YutK3CwnNrItXPKKfwa7tBNydnMD7BP62d1iVI5cno7TmdUOgAUsRk7z8VERjcOBRCmC4LDaZdcLE5RkNFk/ETB6pa6gQFkk7klLD/w0fQs3AxArPGKJtZuMAnDSuxVEMuB7H0TIXuRIumls4LxRg4BarfB8MtCXA0EqQ1L+UMQQdzLTEQy0lWOemlTM+bjxZLU+dQdzDOmmZFR/mUSznJHcYIolrFusQBcSBKoEhqPBSEXBtifODugRy48Ok5AIVjE7D70GPqkHPRjsgh2uSRG+pxDCCaKTulplUXXM8iCUjLs/3C5HnifTuYN6AA3QRCsLwVIKUdABKbVc7543vt8qhUq43wYds7FIZhTfMnfPcL/gU4IJNg15xmhCejI0hRP3fj4rDoG6RXYJzX0BSnAp8kie+wm4IV9THuDeA==
    LAKEFS_SECRET_ACCESS_KEY: AgBQtRHshIv8z2ooI1P8+iER8/20PTE1N7iNBW3BLHUfFIEdVcPWD8TEKknwRlkkWXIvdBHVA3WDCeAr8dTe/R6dwVeCPGRyCNcv0z55DatnYHgh8bSqvM4HAdmNans+XH/0e6rzp8oRQs4eVjDCwCbptWGxy1f7ML2/j7kTZigG1q2EH3/W5f7g+E3GRh/7eRq//N2XqyUE5tMgwD6AQcQi01lx1mgbEi5t1dY04qe6CqtM2oPccI77TmU8iF0sctJUWwS8jzIYu1Ymzw4pPYThEsccLgqwqETc/P99QfMKnwuJuT+jgKF9bEcLQD2nCmuYoZ1Bi0BiA3tY4kOhWCKx+oS+z5M/3pvYP4j9Gp5AZDjyHJEwhuKxpzWTjouoecQRfZh0GS/6X98w/O0GOR6gPVMpiSttJuOOcZ3sFHK4X3bfP2EyA7sqJMJoEmedQIiHJHstFJ+u2k/jc4s+qkrX7h4N1rzgxjTqN/z/Y73NGKHwfDC5AhKFa+BW6xtn/7VF8tOUiA6G2OK26Z6tej6s2gaBWALW4+lkCY1kue14F5xSD5IhEgTmY2FXWe6S3m0L/HqCCnAZXyJop0h32YAmeHGoCjvM2pM+x5sPnHN92N4O7uhaR01OStI2osjYnZDQS7l7Cf7HdL8RDF7Y9OnDPOd6g+Yxw7F8iG9Vf+ioZoBto4Oz0nxA/aXSnKEPv8CI2Uu9u/C6kJim9cIyPnt1WKNC1ZKBWwScZRtAznex/VYe8sX8/Wfk
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: lakefs-creds
      namespace: data-mesh
    type: Opaque
