---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: clickhouse-users
  namespace: data-mesh
spec:
  encryptedData:
    weyland-users.xml: AgBxXEiNbnUkgE+dfGAm4Hi3vY9q4wOazJW6WgXK8CchQ1NEnZju3eRPLT6X4opU2hvsyfwzJeooTJroHlEhzsVqpQT+zvMyPZXIibLvRJ6HlWbO20kCpDZEy2Li5Ch3R1FetThFsk/xqmqJMCb2S6pkw0HuSOv5ZyHUXKy8QiUY6GdyC/eocHfm+c5SAnQoRr+JDH9Xoy5ajrelRfSH9ULhixofcIGSChg0AELr681jJkgCz/AWRGIotPl+x6wHWL5qyzd4DAC0UbD6MCmfGPpqFlBsc641w7P7k/oRWmLJirdjzXE7oH3Dqrdw6tP4MvRmf34Gvim9Rix71xHr1XUxr7ay1hqc4xtMTi9TuFgje9/9E0etKnL3DpNx4dz65rvdvvmmSGRn3EMGZYRxXbsh4kwuTl0ZoqkvmmcG4bFF+Qw5D7t8hyUHp/+3rezsRclL8QqEJrZd6lZfR83C38I/UY17P//WjXo2NO6MUEBLhs95ljGbg+9PeUNsdRO0E2xcX8jIfQCRYX/lFMyLUMr+aTnGclCU/NPZcrMpR7KyDwnRoVVyd1SELbyIwQZAWNPWEjLiVGAx67bo+SYKtfntBbq+CgzwtsL0+kJ9cz+JzRAH9IGrlvuuFIaAu54/x4BN66hwESKzcFih68pawMd+kr3oF5nHY3goxVrkk/90qZr4/1UJIryk3qxenlPu3+aqi8P55tw4BdqbBSXSPNgxw6iQkYoIt+y+gCE3PcCvx19ix6GHtnfue+5hmFlj7Fb8DkLJRK3TJ6Afsq/H0zUUWL/1DmTdXvA0ZRJQvxhDQ9DZNEUSc6DUTQRRcIb+lFCgMDnH2RkSY/uCKKpfJAMf1azOWu1RyOuGfrExqxWAvesVJyZfTCFdixqYfbOfzknj9LImMCCJAZ0mgC74hisJzoRE/P03EK5gHSkrPvwQ/q4deRo6s4tGQ3tanFEfgA0+WjQRDwdRRA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: clickhouse-users
      namespace: data-mesh
    type: Opaque
