---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mongodb-secret
  namespace: data-mesh
spec:
  encryptedData:
    MONGO_INITDB_ROOT_PASSWORD: AgBHt7+plc5E6G7gAUWpPJOQYAad14vJSCSwYc+kAq9gL2g2DA0gxk7bwErTVUUV8WOmQAndhr/BhtKDaU2jF3BOMYUuO7R8c/HmogWO3MZm3rUsZCDQoHOHCniAIO4i8EBxbqD84JIcZ15+SrL/I4I5/VgcVQykn7yoDHrVM5RBCHQtd0oXoh/Y4pQCvG+mnM17VkNeZr6uXX+ipF/btO1i3tUzvCLygRO++CKFiLt2VvjBryksUiHH5bCtbn20i1Mlg9nV4/yLfno7zDR8nBTpl0BbNLrnSQ6UiefCYLyoU4a5cFp0DD86foHms8xOiCOyAvL6pAuRjyrzzq7t5/lOtObRaRluOR5Mlh6R+cLAs2sZxDc/JbXrWmxm2kB8xEoDRSajTXP7+p8w8xuTVKhXblioFWArKMXKaqrMi41tRNyu61IMGhLYcyOogegOB72Arnb27JIKPpLZpLDhJz7BpheDvVsvzau6RvruVU2gS84ruUZVHa8QU6Mw36ikjnfxsMU8bpVS3F8Qan1poyP97Db4UDeGccajUddEYQyNObtE8cR7ttNBLqq46Deo+kcOd88krQfN7SSDPKXa8XcwX4GDO1I7EqG/FMh7+Wuw7dV7zDvhf2UwziQ+6j0gH9U+8WiwhycDNOuWQfe974z6hIWevYIw+24Fau+jtnbv3YxPIQSckCEnk3T0Xibyef74YO7BbRhumu04UI826Y1PVLoQ0Q==
    MONGO_INITDB_ROOT_USERNAME: AgCrngxCjRbc/1z4ZvZYd4wUXiIgHYU8+XgQYSmxlvCerd2+vu57beUr/5uq1vSagKfJY8xL6dEKr3Aw3DR5W9TeydkWZO41A1sY1r0Eyf6RwkKQBYgFgZtyfLRfuYZGQ932/Nx37oz7QSjh6GuyyEiBLCH9TQpXuvqhUB4BGZwkPzySa28kUfagclPI2nw+zIl8wGDb73ft71tcqwZPWGNLMQ9fam4jKr4G5DZ59y++rx4wWntjiR1OhStiwBVTyvla10Q+tUwa2aDBNd6/Rm2njBErDToAr8KZVmXz3CAxYLq+4ip/nBSE2oSVOxL1z/moR9erkPK1UJoOY7iR7VmvqT3zEr5xq03GrgKNu+GqcQ50UuiupI0A+sgDlz/I3kTGx1sC9fC2UCKORpJxgYEI0SXqVtDRksM0iCfSx+q6jZPtHplm3dD9m3AdlN4uO9UDnhttzoZlny3Ci5OfV2PJc6gvV+k5xj8l6Xm7LQaLl7UQU2eIj35aBEumbWHumzsNGpdjFr4pSl6x98L7iBrsONed+V7+BliEfOedShiYSgiTTV1VbbxpsRiSCOCVEVyyoFD891E8D+SXf+2bmo4Maeph2458KvS3DyzsmH1gdhzdgLLKJmcbox0LaotytxqxJ/Y+0f2V8KMq6a/0zdtsPJ5cYFwGSIDmZzww0xzlODugF6XG40ehnZdt5uJZwriMzQUy9Ub/
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: mongodb-secret
      namespace: data-mesh
    type: Opaque
