---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: datahub-oidc
  namespace: data-mesh
spec:
  encryptedData:
    client-secret: AgCOzSKulRduxo+bkJX9y+X3oi37eEJrojTQa9lK/PKXb1QmscaPT1HBADW7z4yvm9iqeP71T2sszkiju1IEp66MBvym+Ryvj9+u9r0kxvnZx8c01y3hF142ZqD9gMgofhUIpSfOwM5zh4hGZyZfXSTC7GPWMSvY2Q4p+5INFHKPGefjAz/8wN4o4gqVGqHj6lCLQT8gIi8EG5Hrt14IwKNLipB8chMjAR6wjFfivdKRMIY+IyD/6T7j3AbQmc/4qwFE6O7tTDvHLLNjPFXz6nliBJ9w7wt+BdSvro2CY44EnsgmUIJ11W5lhZx2DqN84RSoOfNkFMBY/ougT22aQa8ak0uav5vzNi81GfHk3+NN9y3Q2AHqXcExCxH8WFYGCJ0JJq0qQLL+z0qIWrHcBGMjjeuT8N5pWKxxuOP9xIGEnv6QJZRQySq+Bd005PKRiGKbwF03/nqjxKY/Mp763mbzrrSwyUh7LU6aJYEFpxNJmnl0eQHUvNRwbG3nDhxAKsv5rvH6Y88BJ2h/NTEaf/JBH68qsmPEaNJKiYIlrgDfP4DQmHfWNWgZ3YDw4M1rCxxGwsyKcsncJYUFJyFAdfNu30A89W/XUSssdbME/hrr/m3EQ/e68krNOjwckAeNapAhipxDa0gXeZOijauEoqzbsx1xFnNuDd5ScQ0OUEIP0Qb9upRY3fCPtgytlPgoRrBG9DW33hl0U7lrgt4coClQMcngskrgI/Til8yEnk2MAQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: datahub-oidc
      namespace: data-mesh
    type: Opaque
