---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: trino-metrics-auth
  namespace: data-mesh
spec:
  encryptedData:
    password: AgCw2x/mhofPG5ml7GgypOPOIqkWpVXAXXylb7+wiURoH9DUSrpk0LwGG9JhR1AnMqnRNTKM5kfXCwo8Xvaj5WwKnULLEZih+JzqnYztXvsU2cKRfmvQQzqS1LF2kDN4ne0YaKy1IbopwXjIhiceDPhxEl7Tj9Y/SVBwLvgE6aeve3BQfrbn7ebmgW9e6O/i6VO2LBdGv/2UT0rGGz94QbrnnAcr9tPUh6DzaLBHBMrCYLFXr183/BiyHAa6BuRky7r5tpYEv3/8hxZnatBJYbDhxCzLmc1Ph44CRdtwYWQ16jbTdCU+3oywo9GahJFvxXfxNpLJVSkLFDJRZSiFdj+AnLAlrM5gUIjqiBqVPfVWFixDEbv0gug7GO/lcNFH5GP1wgBApaZsq/lFQZcLylF02olzzXVb0ZGpxTHQgN9OCUUb2ZXO8svp5qEuhDIddavbmXJTbPeQQszBUI4M2jm33J0Ty/4qKqbSFg949hfpsARBFtLN4KbootghS+2wdci26SslOAfanBqrE4lfVke23434whNkvQXi7vjOWWdHPOA8tSHjQZDNNuZaiV+h2gdSBoXhHrWnqz48Qb7mveMzjWUehIlkrFlPcoJMPLw4UKku42Qq4SQpDAA1PCkRgCgjuzJHZzlcApKBfv9wCnwvF3kgOBMQW5cSHTYY/62L9HYzra9/mLk63cRC6qXCy2A=
    username: AgA2TiI+kurTsnwmh28G2SMl4kJDHi5qKoc2SX+KkgCq05mS6zuWjM4HADhUIMJEE8KwCkUOUB8iXhHcQiMF0wchq5peI2cQrb8QyKTVwmAm6ROCQZ1jghf2WaUBcgQ+v+fWo9Xzci0hjyxLIJ9twM44INl+EfwGICUrxgF+20C59sie2E/CI1EJQfuid9YF2LVgrwXUrqp6/os34Kvc5BEeU6CqHd/It4cln5Yu8VXDe894qNFY3yMDGgJOG/oethbExVJmq2muE6PwQGP/x1KC395cY9bpa0/5Oy3jFGPtsJ26CpHhgzJbgiG33fcf5EknZvziA1CoZy2rrCRRBmRTviXqS4I/kdtuZx1/nPqONC/XvbcUEkqPxkyM5gqvp9FYtRI20Ltbej/GrWjSsNo9wOW4XXRF4bwlCcZK2VxTI/+DCkJ/N+MkLq7ENl0LrqBAfGH+SPoGf5e2VOKEWYLlDP9aKDuvSraNdrcyNsV30npWOgwYRMA7roVAItQ0rW2B+QTxISBp3YT6aRh9kxCFq+ja9q7pQzqUCSguRyWX0j7kCqXEddp7vGtTcDwM6ps89S81voW4IO31gtwT7cFGmu0yOe9/0k413xPzVkSrR1/iH7oH3Glb66vyKNtp44AJyAAx/eui545rR2IHyNXxcGj+7W2azF/4CslcWLxF8d8ntteECmrpzBLcmkexVw3JbbJPOOUNZuvh
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: trino-metrics-auth
      namespace: data-mesh
    type: Opaque
