---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cube-secret
  namespace: data-mesh
spec:
  encryptedData:
    CUBEJS_API_SECRET: AgBYGo9ZETWloW4E7DIQvngcBHeyUYGTZ8dTKVtrlBl0UI/ztKqh2O0tsOt5qcEwJvzo6FDPv9zieZyyYUnWqRaF1eLycnT0rybGyerHhbzE+1GihbSCGK36afg+2atgSOU22Zg/XitHvZ1IkJo/0/rysz2HW2Slua53bHZHGKOM4UOgoD6pPJM+g5xbfjnZSsHwfdIkQ115gPcTNt4RQnPXGdtA9tGMOawy0oTtKYsgDUCqpk9k1R1iBiWKZWCtRMSbwvJwwzfs+XtCvgySM62QaHUmVB9+1MgwOutQEMomajhUG1ZOB0wPcOXO25xM8UsRebhhvnwl71WbidyrQxO4lSloqNOIjokzEmE1nvmuIMQiThoes5X+OT3RabUK+D7IjGZxil6aQESqiTw/5O0WO0eI7NkgKekhPBdYU5fMpJOT6gaP9GlHEx1UWT3Y0TEcS68eyVwO8j21r/OD9dTSTAI0paUiFt29cy3u3hTPDj1Tjr3VuoghUJmsvLGshjYLx10Ruig6B31kCpjABPDiZ3xKyzIeYLM0IcTC/J7W6YoufMLdIlFKOAkGwawhZs1QJi5MAD4G0Q5pSxnvvYNAZETVBZZlC3nDC9HrEDiLMqLeMM9E6HziOi4nSqQw+YaUv+xSSImFkkqKUyZZTngLr+fxqH1AJJ1iKziGpjAZcVdJcp7KDIIY6i83e9E0gnWFESfP3RI3ZQSJ2gDUV8qp5ShmoKVJILwmy0x8LIU9dpI/5CelBC4e9F7hIZKx3X87AL3nduCz4OHF5jvfnXG6
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: cube-secret
      namespace: data-mesh
    type: Opaque
