---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dagster-postgres-secret
  namespace: data-mesh
spec:
  encryptedData:
    password: AgC+X/dnzXClmnlfi/YXp83Mxa/2gtIOOY8t8AM0YIjc3vSV/eg3ehy2mLtLgOu+hVhatmJeMwUxyzmiLzcUQ73Wo28S6OtOXjw5esG5cBgHc9/NIFmFQPXUJwgJkQof5Y2Th3GQ2Ule1q4WdfofajbeiN0tpmbKvDv2syOEBSeR6pMNw0vdJF9islu3ZdjWwZs4vlGViZB2hdjzgtVvzID2rti+DDw4Ys3v9VWoIV2IPuHzRBIBonRXz6B63qxXoIrQi0C/zt2wwzOzjGIchGZYnDgORDGPyUKREogVTEnbx1tDNIj8bJaA+hwJUqXWMLCdfgytJGu9/WYlGCAle3UmqkL9VE/R0yxKxSmGJzw+oJh1qJyOcLPIyVqE32VY+bbGKNglnHrQ8xVDGBkfoLjM/MdEeATMWZIdmzGNs+HxYSs4VpNRt6z7VlnYsYFRPdF/8eatgOUhmP9B5j5tA+ktQUQGlS4OXvJmrzx/3iGEmQsJXeEe1iN+bM+/E3ksCJd/Lui+xzoTozRi3BXeZiXPHoY03vbn9ZiTchQNXd/5mz5s8Jq/iKcimKluX3F1laEuyDxUj3+JrOSQ2WOA7tdgB3IJ0fcq7GLMdChyXBON2f14VmlPxBCBwTgV6Eqj5kBACbSnGYLxDCtgul+hdVCxssFJHk/wXUtjiL9ClBHdc+sICEWsNMnTj31qZkTo1uwhayYKCE37k8RdTt22U4LullwwOg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: dagster-postgres-secret
      namespace: data-mesh
    type: Opaque
