---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dagster-postgres-secret
  namespace: data-mesh
spec:
  encryptedData:
    password: AgAG0HGpNI3qZsL3MEnwKuSRhs3FVNb5lGg8quQsOL7T+NT8kiCzqRT/NACjxuIQpD2N2HxPGPmirtV7J2C4nj3wDDfBgcqXS2H1ZnZ2ZZHmHRbHNWsecM95YCmNi2w5cENJwD6VH47WXn+FfNUOdf5EcxfyHHlgki69LaPTs+MeTMdm2pol89fKB87rO4PVBAMQ2cVrsBBK7pmsSx3qj0fMxLEmEOcZuNZ7kd8ZA0QCS9RYfmIig47nWXNXSnaE+2/OMDrNHPpiX6iyq7IToo0KEbXPeDGwLPg6slCFfm/07Ils2tRbvpiHorFqI4e4aekTwg/tLlgc7/Q48z276CsTA2jiat74OTAFxBDNl7tAOyOi3JUBh4Op5+yOb0UB5sT7Pb7VPoPLd7lmEB/zKCiGvHFGlG1ZbKIaM70B/Mab/Ix18p8fAuWY86U3ltOK+zHyLjp145WgpWJq/EzQccvpFsPfhv58LlSoBPNcsiQKR7Fj+kPYg1kiUJxiekMa43kWSAYRnZmBF+atpG2EjhEfFezgGZizdCXa8/vQ1o4fxNGpJGa/hEodDn1rQIFcHa7LZxwTpHI6xGg4U3tdcOz0c5wCDpe8FTlvXXLFU3efkgdztOE0paxmiTR/TNmCY3RUsPyCD42ux5Y1i4zTrenQPcGSe1KsFVILTJNX9FGxfiixk2vj6TIItpBBApX3w9qAcdGF7Mist0xKeHeEblqhCkuEhQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: dagster-postgres-secret
      namespace: data-mesh
    type: Opaque
