---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cube-secret
  namespace: data-mesh
spec:
  encryptedData:
    CUBEJS_API_SECRET: AgAEUiDtYb5/+32NmzD3NwADYa98bTR8hLQbG6NRMnu7TlHmgcqrFdy4vh5d1ldaRfI0ugQ5R7ZTYjx31DlDe0MrJVbkMYkwkmQIU/RjNyt0rmZHw/AvZFj4+v3K3KfvDOatFvmanJfu8BnkOLcqkBqkaE+Bzl7IgNGASpKhPPCJBXocZZiyEVQRYKk5suIcWKSuFPezYEJUnsbhuWk6PCK3wR6nkFqQscpadcYc8hjdFHqiO5VpjawFwAoqH5POjzeOYBTa943DHX5zju3kn1+2MJSA2eIocNP5DsrQE0/aP0Z5BjOvyzNn8hmDtaNU5qJZwk7kaqOaugIXLGlix0EOaHAJtnHPVRrA9Y1QbYFpWSpUk+991DIMQXW+Me+RsBZ//TFyLK8n4YuuY7tvVteU2yF8EI4rG/sxvsjMvl6tPzY/4NADIWdD5YimGJGXluUqV+vGgA/+Qju43/3if7ok92cHhzCx9Xw6+NAMPAatixWjn0zMw4IvoaVWdyUs1yvoAWyigDKO6JKeYHerLOXxySb92qy66067fQunUUcbYEJQaAdvHLF/lS3amOXQKrSJ2WhEAhdrFlfo5FeneTy+a4ibG6UGrYSbrRK+dUX/cknfsIcQ9G8XgA0D2t+v+6DYNCKhAa/2eZOLui4RMFY/vZQ4oYIRjBMc8BQiygP6UWgpc5XtY7yXAP9R8k3MUvMaEQLQ1fxwyxLkDnETqNU+FEbDzVe9lbzbXPsd5eNhXPDgseYyyhkg9RiKn3AIJgVEQ7cZA8Lv68hxHeFL6N8l
    CUBEJS_SQL_PASSWORD: AgCpn0Vl8c4jWfBRcjt9rDP5hOZuUf6QBmMQk++PqYC04b8apQ+9Un0UckGZnWogavJxgaMEEptPnF4jLsKaOI2Iq6rV6XpU0sgHr0OeMHAcm/o2glR9T7haNfJ9799zA7x+ABBcBpPVebwKu0lK4f592RtuD+3tvZoeY+lT6aXtGbFTuGJy1DvHNOf9GDal/EnoPZS5eyFbtX8ssv5cJi63NYFrJA35E4vpyunwmQIEkmBuWzVgTq/0SvM6xaxw9zsOJ9LJkqzheJBClju8Mg0wV9Tgi91icvBujfDBjbezuZOMU3NIOwq4ZAjMDYJVs+x0VPIhT/EFH4OBFtGEOkUDFwaZlb5UzFiv2UTT0Pcwr3nomuJ1J226Cal4Yft5UWNNe/AvGkFtgfp7LCT52dQXMdvxDpx/V8soh/iB/7yoWdQxAVkeYkG9scZKckKbJDPnWx+BrqpGTG3GqZrkhJkh2DU8HlYU8udSwkEMuQ0FcW7anG61bn72hd4yvIAsQo9/n+sWURDtDQI3w5ZNzWt70L5JOv1jhUSEj/gKx2V7HCpi+GK/vNB49+cANup+dtw3LahIqEVY8eySLe7I3ukiuAC7HIEHyxinI1cBkxfDWjwLB9PbwX3lkPKrwlRN9pj9j2S6AeVS7a4u9RwVLvR3fF1Bj+dhcgdlWhiUEMdNUfBztety0yFU/Uhju+5aO5zCRilelzGyLBsc8Ij9jypfLyjxZA==
  template:
    metadata:
      name: cube-secret
      namespace: data-mesh
