---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mongodb-secret
  namespace: data-mesh
spec:
  encryptedData:
    MONGO_INITDB_ROOT_PASSWORD: AgB133Qde1wQ87xP3DNuZiBLd9k1/6fYSHXD6EU+UxB5sY/A/rXY4xWBxdM6anIXI/IhlUG2ATUz+lo95uSzLv+EkVUiHz74VwHrqTM9iWtFPkFW0Sxq5Z0MxqmldnENAUNCnb8c5jSFzVgBwF5p8abkEut+UJuR7n46QPw4PxeWCfVIaKn3l7o2s8sRBE84QCZTjBoFT5TI/otqQTa4AGl67O6YgCqf2AvtJgdsl2ImajYG8nn6XVfj01cYTSHdL8oPlyd7OtkqD7w6vayOiEDSx2hnX4to9+MJ0Y9Jg7zWM78gnskMCcGcVPDMDibBV40lUwMJGSC8+pLrsEdAjl8L+GF3fhPN9CtNHeZKOFpCTdoKmvBoz2HIXzOWWMLN59gtnGUzD4qmxWFQartn+qDjkTVfcM9z2Cti4jXru/55BR6ebpuNlPss368w3yowP2wcGz1/7Oi73ZVFb0q3ktymA8wKT1OCQTWtbpH110kL+TKASj345XJy6pplKqu4hcVMo3f35V+/ngvFSXmzdguXZcv4lOi+tAyN6JXCLIl8jaEPVrLHsy2OOPU51hRZ4021fleaNtchzbI+tdQf09RjodRRmHwl8chtUun/kRYml3sSYzc97LJoC8Dbjqh6RqAKsIQRkEzf7EQs0IaYsAqlUNsVaWrwlsjY44udOV4Cn0i24bNsi6cm0k8wn/TK9XZPftypqfrA35XC8pufakF/IGILzg==
    MONGO_INITDB_ROOT_USERNAME: AgAk06a/0zb3Vb73sJYfdRm/kJzQkwwzUg3flugNOQJsIuIb1DkuRYnoRKBRu4B9jxol1H2T0mhUtHXETjVxT32dqw6ATLPCkEP49/U0x2Fsv0GufhnK3izB5mp1RjrfeUntGzPjgid2JDz5rcE4T+mKxc1ZyV/83I/yWvQmCVYwDiOmMdaA9Dhsp0geT4TyVqDdJ5O9LzQ6ACW20gOS+lOqGp9R15AHIfXcWuDLhd67MdFUGpgVXrhuVG+y2tVRA385lmhqw5tGmsiMkfjMmP7gNb/IN/4H+tj9PgH1vtwF1OFKN6uplVfP8+vB3ZsxN2bBpfclmMjC+MFj4XGOc1XQnThbn1PFjeUC2QWwNQQAsEAedDIUVkDIQLQGz3qCnEhynHyWirSnHQpIX5SGOib6wdRnuh6nBHOeFDOnyFof0E4JDsy7pcILbHhCtgMsC6ZqjEJIEXZRh7qFr3krs+MbsWH+2L+i/+iBXatkhdp2hXlfUse0CAwhfYzeGBUgcn8/brEizzIw9AVtslHZUbpxHKc26Rfaj+5rMhAyREf3PEwGeJOImvSrVByC2JTPLJ45E6/kSDO/g70sFnKr0CvZloKOE3wLyyNlO7DntTMkxH5hKWuaSUif52Tki1FRM9BPZGD1eniRHdYZRtfLhN3iqStUYH1N07Asr3gNhDJON5DurprKLXN9P+Njx0aOeN7n0pqTraKC
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: mongodb-secret
      namespace: data-mesh
    type: Opaque
