---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cube-secret
  namespace: data-mesh
spec:
  encryptedData:
    CUBEJS_API_SECRET: AgABmH3S4CAjjHEvnzkKZ92a7+jShr05+J6BTd2Rcs0XnRSAKi65DjIsj+tzjBLIsTp8p5rbjL+fUwFar36yRG3jYbVb9UQfqzgEyKHoTu/ErPDNNF3lKL1sztNg9YnfHUX7sSGQdHRmYxRQKuWSVb84VZ2UDfIenLI4NLgjtJ0GyInA4J0t3ZvlTIhNT24v8MOQTJHMJ7m0wPUAD9lywaRBC14vzbI5+GJabqXB26zS/hMYoFxL7kLnJH90EL41cQ4gD+OcQXsk/TA8H1vEPWB15uJMHPOD9LZdhHarvNI+JyRbNDOItj7fkhgnXtuflN/GC7gMUzJwa3XywwTny99bsEmbYpOo1KGFIip3apBykwufT4e4XsxkDdb9NLuE0NVncdrUX8KplEV9CiSFPqWfypXEgC/bXpVf1CvtHBiu89OtBTtMnrGZB04d7oP/uVjUkb/KjwU+goSijmk/r/H5R+6h5Vz7qX68coJs/Nx8nEdfc9DNU2GQBK5UPc3xHZabhqOfseZyYAEO27IKUV4QSDjesyD5+dITm++DA9/6t27NBDbTD4ZfNj8ip6gZkpvXVQN2gKgdEXLs6WEldiHcURhOxyDldpwtDtpGARpuDxd4pqn6oK6dumnnSBVIqIv5DIeOgFWRGCq8aDqNi1wAZpXmRnZ6zyX7E0aPqFZYCX8d60g3kVx0lK2ARLSKAi5n97V8k2w7yCTPgndYuFt+MjRsAmuQ8kM1BjlRo3OdKwPhMkx5A3hOnU8BH6m3o0OIeutABvzWcpSYn61z+wzp
    CUBEJS_SQL_PASSWORD: AgBWl+GU0vdf0gztaF6zGItdISCKYuc+WKMF3njjYUr35av5xsG+6hJKHIluY/n+i/fhqMil48UTk1s/Hv6OK+ZzB/twvoKnE9eoBsT+K97f5b+lZ4RzSx2j6ZgI8Z8nZwzngjbV501XZeepf4OnHtP0eqVMaIGXix4I+mVbQO1bUCC7ILjHS+jvoa5jRxakxyea0YGOHKa9OHYeIhvKb4m3XiWTo91bt8SLy9gqv6vGrDG/N3gLneYHnp+FeBdkNke8ia4qa6EoSx2LPNHBNDTPM0DIpdDgXniNvUm71v1Ahk+qEFCwGWoFZYK3aBmkmBXT5GKKRiDSO4ttlBAFPQRZsKM8A2/NAN5QsXD5rp+tCzm7NQXXSX7n5FK9dBEhoTJT/FaK/Vqz7DhK9ZlAibSFN0jD9h1u54ybuCOUPqJl4T/mNlNW5XkwZdXGh+N2S/Rtu3jbkwAU1rQp7ryWnmK8FZ6deorqcyrv4ZZ1ywFV7MR/CKNxHOnEvasTXeXoY77ovF1LtnSLh0tlup6diMOQ8XYv+s0elqQ+ocjCnFYOtpFop+4k2uxZ6NT6RSJRZUFMsY1ZOkSize5JCAkhwcCK3oBfzFS+Sg8bMUeuc78h6qIWAcYhM1ZOXn+e3+mZNL1xOWG1FE6svNVTiyKufIhXK1r1byyHqGuUG0SjJvztYiJI3khXSHtJwSEF3QCRBnmZl2gK+Ns7rreintFGlToWz0VGKw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: cube-secret
      namespace: data-mesh
    type: Opaque
