---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gpm-secret
  namespace: gatekeeper-system
spec:
  encryptedData:
    secret-key: AgCWXqtuKjq0+xBpynT+wmwl2lnlLdqLq+MV55oslpp/RfHElkJ+wO+Wc2BB4ESNnTk5DxlzDVv259cDw8lzwmJL1tfaljA03C3f+666WWqxrDXksjJFxUOUeB29Sc8u/ptzIjniuLRV4AD7CSUxl/mmcmd4FUlCb98X2CzYQbY2pfi+v28+f/O+vtL9MYmzo+sKC6E5aS0RN8Mh5fNxIBEpqW8cCT2kTHADLc8F9P97iq8H/FnWdu1BQdpaS/p7OIzMb1A7g81gkKoCI8GwrvBwnJ0NHDPvvBYK2b8JfihBmILUdbuAoMSt/vVdBn0MlFH4LkyxPvhTcrBECE6l2XAMt6FPrW8DPesNHw8yh4MGz9Mj2RZnZ4dkGyDJPwZ9NZIRJsJ8zLzck3z8tln2T2/vC0AHrPKHamGecRgdzyloMBLz3IO0yUG8+AAtxjBox0UmMdaL28fCbI3Xc82YPsEkxXCxzv6uClo558zlpoWvDG7cn6JXxVFqYzXa9WvDG1fs7PA4WfajqHl+PzKwSc08v3AB57VUX/ksnVzWVAVWmOatHJ+4Q4pjA68xjk5wJdSZH0h63mUrTIL65CdCioLuH/Bi9L8uFELMkO74FUhzYzlIFdmKuQ/JEh1lEHK53kddQL++3DBvM18uIbINDdZmw8k8YeHEWQ8xrC7GNVzK6zH/Gmf/k7YGHVPvRT5WNi6XJd8QkA4elBBnma6IHc+gQvIa0t1Myzlw13bTodOOj+JFRXh77PfYI5csY4NGqat2/KjHHUimXHugA3kkLm/x
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: gpm-secret
      namespace: gatekeeper-system
    type: Opaque
