---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gpm-secret
  namespace: gatekeeper-system
spec:
  encryptedData:
    secret-key: AgAE4RTKasQuK3dc/7ixQxQnAaCd51RtBRrApQYLOGbfDB9443L7Ck3Yuvw0QtAGu9DPSHODOld0qh6NsGq0hBWq6M0khHo4M5iwbBv/wCHw93bCue1tAqzW1bg4HVl8Udcnc6iPKHYpU42X7bQO9z1yWrU9ivxQv+yqkDtDkballIcg7RkcWZO8h+9gXOi2aiPlbBivKnBZtHcT/JS/SEkCrHxkkxvQFMBTu50RiJtp58El90UbiQ/C6lPIYih1UDTpuwUDZBGuR87ImZaV1ANHNbfGoaRVf0y1zq1nKUxrMOEuT1mWaBN3c+ZqqeQsFqAFBsoiitEH7uXYu0GtoOzFMaDCrnbROLiF0ZYrvwRcnFWjrkwg9IKCTncUG66iUGfuxRFt9Jzx3vIW+IlMWIXr6ovAXTFDSZm+92erg9sjsyUm8xTdft6I6yi0EQcAUMh84Wd1sAz/aDAbrHUyfC95CSpysLKH6oh4WjyrSMFYsNnVsA8iRGflyQnzX4nfF85GT0wEUxpHVdxWpAMMgKM0kP4pCkn/GpOXkTIZx7BT/JtP/m4+M+fK+w+SCAan6qlVGgPBJH/oYobSBJOvKtNHQhfotQr6yGZ6ZntAIt9pwqEs/2soZ6x+5rk+PPrepWsQGV09ah+qaCgyCHAgiD1U/rJuxJuH7nHyzVLNDRttLQmdPmdzHyDXG+MplXotQ8uiQpo1kSVixNgAMSd8OHnzOPm2+vvUymQ/8ur7q2GL1w/CFvig4XqIIFuva4QC4uaH+yogk8kcf2cfLMz5/8sk
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: gpm-secret
      namespace: gatekeeper-system
    type: Opaque
