---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: lakefs-creds
  namespace: jupyterhub
spec:
  encryptedData:
    LAKEFS_ACCESS_KEY_ID: AgBKW8Ndr1vnoljfuwfbbp9BVH8oKmQf1/f12cuvKp1wBcCfqfR8yTlStoaPyX9+IqmKCDxSpaNuQE4NEjNvPrSyEBiLFjgoj0+v+3AErzF1Wm12bdN1eUlNywchxoG3MsrvxiSn1ZT3eYxCEdZbcKdBQ5yFDnQaFnby6tTpL2qMonYJJUFLWXl8QNI8XN2oiSU+oqLa7ACnePBh3lU99lF7RAwKWMJPjvnCPZksWk/uyeVDZlxhU5GydsBHxQP4PDKrRi3uMDrCWmN+NjHFoe1XjZWLt6FteEWHVktEfsXfM7g2d72ebv6KV86HCn+hOKrOQpynkPeK1R/2evnD5Ahds4rQtxEyMGubwqg+56Ds3S4c7KBDu2+ldTWtFstKb0otyZQVbUsRAFFk7+cTe+eO+Qku35ii0gYoDnxMtotoAcriAM5c8W8zYhloBcPWq8YQyCK17wyqLSQmnfNrsqEH0J+4+zC5TtCUdBLuHLBG83nFsIop+W7g7AJTE87wL35nwuwOC6X3f57aIwXSEM7Y8qchQN6mQS0V9ROC1BTJgXTPpOvcXiivezGplTMpRrOtJBa7uUZ1KkGExpaLOKDcK7MJyXVDwUWkk0ExsqAkpGL7Bs8jsCGa21yh8irBztTqSRvwGmKHEHnvSjXOEEdAZqOtm0aFl2Bmm8VdDlb+/k+hrXCjIVi1jQSW3lfYWauo1yZwWdaaOhNr5vxBSRbIG1AasQ==
    LAKEFS_SECRET_ACCESS_KEY: AgA9GP31M/jyScH7jL1kzGHkwOdiSMAiMx8WNqteJaFjHq0ySaeIFkWEry0IEElbkBD7njYUwz5fYu0/f1SMEuw66CM9hOrCG06b2r0J22ZUakWm1qCrWVrrND0i3HW0ZhCPQU/W99TZCyT4Sfe7sVFlR4M9MrLyiLxLudRwehkKMVxtkOGImElYExk79D+mVp0q9l9wo4ILQOO54KWphc4L2KklJHZE0LvueCYKnNkjDpv8IZ+RxKoObbFeWKWBlw3F0jHH6aGT6ojR4eZUwb00+YcNy7xCpV5pFSJgofDTTCFZjRqUu0JgeHANRjyrsC8tWyKZhL+F+ScEnOXVr3PdpMGeiaw4I784H4YWKF/UmZ0YtkJzgH5wCeJ/UV3uvHQ0mitx122dPUXG5fIyhSM72x3SQGY1OPY+NRh3sL1LJp30I5Dm3Xj+imFlNso7a/Wur3ZlOs+OXABQm7uHzp9NwRFfCRK1LPl1Vi7JSWGLBm/DIyVK7/rblxRfs8efsZvRUtBvveBfWDW2/ZMikDu8GSw7ktfnIj/iF+Sudt54uz/bwYucTLSbwysXvlYvxyAqFCGwpNScicjMkeZLO8tQHqOVXk7pCjBLSezvm+ciaVt3f8VORRxX7xM0SAo0/NCO1tBi37oQeA+OH15yPL5mRBd5bQcEIcRQRiCmJdKu3w0NjU+f4blMwBijAWfjdUSGpQIxgZ1+ZS6eXiQi043VRkCkxkrgqyPFHjjoe2MOLGEjUhwXOQRF
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: lakefs-creds
      namespace: jupyterhub
    type: Opaque
