---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: jupyterhub-oidc
  namespace: jupyterhub
spec:
  encryptedData:
    client_secret: AgBaJ1t44d6Dfn1kCuZcyJW3WN4+CdMEaujmOS3nGxz84HlprnptKJxEFK9cM+Pzp0WSxfRlMFtvvxCaCJfpO/cxaiAkdezJlmUfz6jZM2pWsYRl0ngfsEMCnEUafayCFhSpmPVYspAY46XFlJA9+2w7qiUnCfTdXsn6X7i3NV0NGtSwUu/uFzqmDB44Wau0elzAHJUz+A+FNxYHqlvzrgQXTwz2VSJLDlq93p7FnUTLq9cP6a4rP3thQrfUHNLMx2eZaCx2WzXx0+N9ukMm804lDxJCTn0+YxEFdPFHFPRr0gmqkWgoNLzG0ICCwOc2mbPDMm0iq+4UwuFp7dWy7jfssoVsMW2S7G4WVKUSXAAeOzxFhw73PQcPyUKB8FjWhza/i3qjTfe+vFnAw/tEaWvlvwesga/Dt2UiceodlF8S8zBqEQsqUjpUkFegDW0cStEA9+G73aZ1pgItnAWmmpRaMR7DZA1MLSHZBGvI5jX+7bECX8oTLIrUDL8zCkOrECPHemw+P3IeettpMwOINXOQGaOFlWeX2PjBAOZMEJMMJgXm4gZvFFICQQBRyL6pIDGi4DWCrhHocn3PdzS0RuYbksmnMcicy1adH76Aec79/w0pVX+iplV+XuEzqvUWaigFKk+mqQJFXjmV5PHoezzXyv0888OWaxkeoqT9eYG9N7/R1syzVJ4P6MowCdbaM/DRfA/KBJ5g/JSFGVehYQcqm84JVkRkVBzpSPuu+8jb0g==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: jupyterhub-oidc
      namespace: jupyterhub
    type: Opaque
