---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: lakefs-creds
  namespace: jupyterhub
spec:
  encryptedData:
    LAKEFS_ACCESS_KEY_ID: AgCoA/eE7qjdsmbZca1fOeIhFdL5Vg5mqYjX2cxpdUeWaotxBATovG6/VNkmi783X5nKso+uG2p/bZcIMwLYy7qjMs3zdkeesyq07/Jm4GCkLrIGxniJxiGUEdEfuLkUqR1ltId70L0rtyGhwZgrXyJV0mY5T/qpk76kmJCL89JTUF3CZqfPYVJFWF1AgVNY8lvnIRodOQ2jDsYWmp2DTi1nBx2p5KnWfqAkuhS2v1iDnbcXTOzLAGLUU5eG4Q10fbw+cAlpg51wZgV9a7BQo4ENjikQ7dOoavfeOX+Aog/asg4RnVWclPtpHkGdKJS8QzzcfkpU9H7TNiXfAtKbkwRpWMolGtGM4fw3B6+cRDX6S3UBtifb+YLOeNzprIQhOy8W3mG2NUTpY8FBWXPfKY8zhAemrSzvmYXGV6clUklL/9s+uhmAlnZDvUGMyA1ya7lYbSa7ndpqfUGMJYo3iinjRz6X/TQdqVb+WgzAisUe7bvo+glNkO2FtRBgXASYtPcW0ZN+ssZi47w0Y4ndtjwVKm4xBcs+24rlSlicgU0aKVt7n3fj/jtK7vAnNBRqUWxICLy4nuuDeECPlOJF+OPmzKMokGAkaa07tCrBy8rAz7LbS9fnH71yHV0NRIPHf9X38DcD2PnGOeKztyAONDnhRUCPfUazIVaPb/ztLYJ/t7NbIjKRo2uKUQ1Ow+GTmQNwi/86ynMZS1VOycVONYuRISfxbw==
    LAKEFS_SECRET_ACCESS_KEY: AgCZYHTcUUU9QHAFJK73z0gRpUlyk1KLXn7OLdnXpVfeEOE5/kJKSHj92LLBM6e3V/gkxouvicwXUdclnOrCouSDPt2oqUhYRE8g9swyegUUGVIjxtHDyFa8AdCenSP76R1/OcfF5AtawztQVgFd+xv9eT09QHczsK6WprlXhLBcIo6341nlBY8we1/zYLL5Gi0e4HEa/dQzZi37Gnx/F1AdTL6EBTmvbsdl6nwQtoxeiFobmDNnHimp704lEe5BohdYb8uQIFlv/lRI1D7mjGFAzSkCuB8kMUSlB2BZBsSIN02k41TRQfDmu+ZL/sz4LaePXJsUvsdP1RrKHffsCMMsWO3+2RCuCCxGlDJ75K0jFzpxv+dwXN62RRJoHbwaSgrd1i/L9MFx6r5oWkfLklHSYRs7V7Vx1UTZa/AQXBreJKNhLpMKuOobYoJrzFXH7n4uESd17G1Z2KfXzXjkCgmL8aPtLfTYUcufvYxg4DqLltLxB8Md7jlQFtYzJVo6Rl5ao9DlbPF/O4WziAPne7lBh5kuckuKn8tQz+KJNvt4r2WzmWY6mCzqrmivb2tj0CepmDuqEMQwL7dHBOaoTk2CrgyxZMiKxz4z3VHN1pWNkErfM48SZCzF9UIwxuCGEIlxjx/1VXuEmk64P3AegDYvukAAJhpvD1Kl4sOtvZSKHz0BqLMOHy1Pc10cPEb0McwzT4WwdeppbrT1ko33juwymq2wElQZbLMmXSmnN85HK/sryKZ7n780
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: lakefs-creds
      namespace: jupyterhub
    type: Opaque
