---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-creds
  namespace: minio
spec:
  encryptedData:
    MINIO_ROOT_PASSWORD: AgCejWA0dcSB54Liv0Iuiy15VTPYlLfWZrld++LM5t1Lg1UhIzWt+2UzgIFPCGAcn0w70csHSxzd4DN690c7oYynH3LzT71KjNPxQ6lmJAZ/6PvjregxEpchz7qmEigbWq0z3Nue6nd/NmANJ82Lb+uPsSSuHO8+bgBvHQ6rh8fYZUtYSLmKtVAYHiq5+OurPbYPa13Th3aiTjt9tplPcMOE8eiBy5eOY6uMvkqpNeC+RTcTE7UE8w77NRPI0/fBGPc2JXn7/AJUkM4/x45qNjWUnGnKoVrEEfJpM3N3DGro1B/fibYj/5+kl1eFKEw0iiVpkehhwC96ZMwzOOZ4xDDkCf1CCN5pK+s7X74QXkq5xkemHG8Sz8Y/5btYPLvmANfk2lAyrRSVQUpP8/GwJBH0FvcxMRlgPn8UyGCvdY+jHbWYceoNdTHivf9brmra3+GwVl4JdAYFny/0JTlCjv3fsWMdYdVr7zBYA1Nn37ck9yCnmR6SUxM1Hg4x0xyQKcMAzZyb5gP81YtHIHpe5korXevyEbrhR/pAhTd/OkrF6v33izQHVZxg0xJpw8BL2NrLToRJp77zPsBUfyLarxneKOdkFHq5HmDYGwhSZ7+5qajSJERjazxVhBx5n4w4HVOaN7tM+6/iUX3t4+jtycRN/uuHcyY1OxOjgAIowXVtFWIp1imdNO+okym0MzqHAcGfWqXyBxxLAWb0PYDrCNy1L65ixQ==
    MINIO_ROOT_USER: AgCinJFZNhxiSK1QwIEaQyjTMDVmPYx6j5yDM5srLYRrctUJkCHImxWP/n+PPzBsy+ubW+ANqM67hs2SvLctQyZFxmbv4sXeSf4Vp3ucdZ8m1ezr7J3Z7nK/BH8nKQTUK4CnQPv0NbhARJietGFLCp/BTueNOT1VhdhXY5VwgH0YEb26x71cmczLC3wv50oxAUIEu42UnpIrBBu9jbO1HY1TJy4tEcIaY3yVhKemKmQsU8ZLLmnPjoTiRsBp2JhILqSfTX5WkvctD90mI8EqNigth1w5T5IB0BOHaArFKbiuFXwZvVVqnAM4TUecqh+lTOEXRVxgx5GhzguxRK4hCFFt2rTBzg/41Si6CMiMyHyggXc/qesyHy1dRubvffF7XeWDU+mbSWssJtN6RgsHn3N0/uHIP05YdoNrZL0kRt7M8znKrlAe+E0+wiRcJD6rFactqarFq40/DioU2WZmYZURiI9Uo8cxD9rYuWv0G7Xw72p1EKNOhHxJsRhBjN2ehgOfkdb8gw+kbUzmSBFjptWOP1d8JIj+gcN/9JFli3HVKtptSU9XGYAVNsEoXksnUIzx4GYDuwuZInVUJx41q5uG5iEMR9KfsE7KskUhwU1SrLQXdG7/KMsIWH6FY4rPfqS3pIHJXRHGyH2TTum7uxgA9mSnA+t4d6zNuPqJUBvF3ivx9QGcXaFisIu/aqRaiNDd041T/g==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: minio-creds
      namespace: minio
    type: Opaque
