---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: weyland-alerts-telegram
  namespace: monitoring
spec:
  encryptedData:
    bot-token: AgBcjXgeKCeCNoj+MGoKQEqyQzZhyA5y0+4lrKmOUMWo+9MCEOe4IxnOhhuyVn0xSHiteFA0CQ5o4A2U9ue0Mxna65hT2rSWtkoR/6pN2iktH2WBIc0LdLoM+fqef390b7HQvvG3mNUMR9ZTPdnTB6Ya22qJzFhQ4l/M//19JyvDvNDnQxLNgZmRo47vT1Yq96qFIP5dvyjr/RkLiAHIKxB6VQE7j5FLrzAVxDOXr7hVxo6OYDr7VieNCKQuM8gvokt1jeuwGI+IzUWgeIktVvcOMgnW68fEWIY32cu11ffB1ExDlEN6b8+0HymBCc4uu+z23OejaQx/e3HrJ+ayH7ir9Jue2hmPkeJlbdgq+yKIb5atT4vaRYbzn5J582wWgx8iyX1IvrCbmcjOJdnSpKpsLhiV8kH6zOU9MX/VAPG5W2kMipwjE3V3QjjhCIde6YipDrgN0yrQqGSUkMRYVBuiSRt976Ln9JpasPXO+u0AW85mGosbh/R/2+TzwH7mBvWzuF+6qYUxVr2+qfORtmgRjGA5z5bUsnp4jj7nEWXPkWIPHFd0GSOxA7MSzsO783vTWPwnQOR2EZvb3TIh+H42SjusgBQS9pnuOTZ6Zu79gcjcCUv18TnOIWCBy9ZTqH+hFAEVLd6l1h6ugKoBK0qChCGIviPWATimvbglCXyUtziM7xV7aBnLg24YCCeRy36e2odz134N+0jWhf2o9AfbOccbX5+Exa65L/AEHVmwD5vcPuKHBF0/cvC9BEkK
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: weyland-alerts-telegram
      namespace: monitoring
    type: Opaque
