---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgB0cTiYQa/Nq52M3X77Rc7HbDQA2UisDpElo9GlQx9aDLYnXLja1I6Q7bNL0v5UXVxjvXUN3NnaJKqb72T3vbbvY7hOI18xtqmyXGxSG3lGAN38+jUKMjuECeIZ6gifqufx6SKAHWp9zkczl7tBN6SwEbxEJSLZ6+FetunicudBrLFDq/mrJOj/W6yw7jb+d4iI63Wwal4vLslV5jeEfaTnJegMV4ElX18nJSDLTszy6ZBvn3aATazr/h0ONIUv2CLvn/8EN7AZ+tal56uZeTbgFGq4GoMoSijaU0hepZymYhDduEfPOSBMWkj4UtK54iErx1JgQBOl1m6pUySkRa95Vm7KZH1PT8c9A3NApcmWe5mMqr0le4cFcS0TcvWimwS0UIiWydjB20CbG3qmi1+bbPUPslgSHCJ7KZi7H4+T+XimYYW7By0bGo4CTF7TXw9je2n/2MxXLgJCRk12M6G/vJ5HP4TpUuIwZO8tNFyvJpceIwaGts2BPXnFyJL8MueKK5P+2dHa31nPWxFaNrAf4ymnnUken/ggjHCUV9lNJpojIyYbqhQvVhqttKNkgmdWWcHJgv1Pcf2o+NzeQbmTE/t4KJukL/W+WWs6HkNEhJ2leJ0PJQaQOlFS5cCAyfsllAtwQ1SEC+J/ypvLSfCYgRNxDW1LFZTgOOvMi+mddJH4bdCxRPuPVt4b1aIq+MkpBVIco+XwdeaGq/3JZvMuw/yglQ==
    admin-user: AgCcmS8za8K6NoWcZUs8+KaeuCbqF/SUI4wHrZCLqtYhh3rWuaWP2es++ETb9IExB5ZkuboKDQJbkANicNDCiXLsGFCl+VWK70ZMUU91fpyNRdCR9/LfDU12qRwTeuSI1uWsU7kJZFBCQ7HfhRf8Ae7yn/615VOZk6PS6omZNEVAWuMXx/Mt/8dYnwkfaZKh8rKbXQ5hQlD+jGLXyV1Z8YrbY+GZF1NqRf6R3frE4hAN6qSsFUmgAJ1KkVpufSbcVzNqwLo5u9lN39NfoCu2QoF4hbgsgOGm6Gn/ICLaLD72hD2kOqZNlPGQYjve17VlhrNx39mFbnmbMhLVAt5vz/IXgGMqIepswb/ySHq7l9u5fZFpEbN5P339m599JWVuS2PHDZLwQ+gSgFKZz8rmZcfIT7nMVdNDsycysA8WpDekCZlHjCLeURr3Zwneqvagq9eGmf+8jOR2CxxYs9k+LHXQgqwbByoJHrJNIlEw0FzGbPF33MTcoFIWp/6fko3p+/k4N1s5xmqbVDarofDDWoYGtdduohpDfY2ja6ilYIwGJEw1xzbQJaUB73wABo1JVZFHMhRRqswAJ/lGp+Hcw0z2znx8acJAi4fJpuHUusCrxKNHFnmKEY1ZLjHzce3bDh8k+dw+pvThc5avdBAUwQoIp43J7V8Xl0srB8cM3wqmvtz+hgOX36ZUT+brprUUOyg+lsLbDA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: grafana-admin
      namespace: monitoring
    type: Opaque
