---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: loki-minio
  namespace: monitoring
spec:
  encryptedData:
    access_key: AgAgL2uMLWor88tn1quU7nsFiIWaLAHSOttTNmIlLI+2Ida3WeDJgLpr1Yabp7YkQP5MX8CaCxpyNC3JZpzCFvbwnKPN663CeiybsVOu3DBQKjkiIzemKxu5dLO2/SJnxaMynOBBRUo3V9rmxiwCHy0autQ1nII1KdvI3A9G8jqTeGiulbHlLxcJqyBU8aZBJiWkAq6gKobFFL844+ofJPbGggkX3ccLTqGMD2gyi6HpZ3P7SvMSLwXfscVc5j8U7PtvnkBLdnEpGXul/xyKW7hjld1U+xDRsmKX72b77DUzeLgQv5P+HxxaK2ISIvx2Vce9HfOs1b8w1esryUhhlEzZt6qYWGEVDESNBC/D2cuL7xyH8ynodEVsMJAzjots+R7h2GRAhEDftJRZrDai+5C/idQ7JqmYsleNkyEHNBs1KxtFA3ZyKcFA0mVmkUXOwxe0ny15aB1Xdql9HrzKhhwgn+I1Qoupdg1hLUy8gtcZ21JP+V58hN6OypOByjpPwRkpJJc4yNERFxNCu3iSZedePmTRR13h90RSbUn2xa8jqQvu43Rxmer/0i1JGBnIE6Bb6A/nvsEVBjL39L8hG3xDkVB4hHq5Mbcy5JzzqaBg6BAB0nLMv4syji0Ztd/a9LD8E674e7qJrofLEyA3Q7tTw8DnJyfwTTZ6gscdv7Nyu9dMlTsLOyjAeE1x/7/f//Urgq4hsQ==
    secret_key: AgA2UNaQZ4+lTfeEc4e6r/xpilK7FlF8N/MWYe8YR6fTckvkdLWRzPgvCHs1On1XcE0UwfqIaK1qPGu4YrTFsW2ZxW6gS093N1st4vpad5jYm9AQo7z/EONLNZd/uFK5R6QNxS8+mHZbxAPyinsY7mum+t/gG+LSQcMX4sGUxU4Fwa+SGT5SSh/H8+JfhApQ8QkugK6Phq95xIvIWmIGvBEYJQFj1NwpeN95Rw/+YVq9gWwJzb7uuu7yNOwOsX1Ts96YEN5WQVwPHFpqNEVQMX5KoumTL2kJjTVRnKJGHROsTjIh9JaEUE0JaJgtX0cLLxrw1jGLPnp9n3AIaQ3QESiOiskAPl6/2Z+5svxf+Vb9yieaHbN9r7H5AFwJF3ODr1pDlRpfqVagWdb+cksD1hReZvRLSbXookNgN1HsoUg/maOq0wLt5GzJedqh+kwiLCLnyrTKw4ehKKlltKPeaRfrBnxjzzOFHvKsZUjEGXvGWK5uoQWt5pR17wgvGoipmUGt8yas5dZwORXQfgJmHUeKUsuwke8oZW+v+GLjzeNTg24PxbbXZd79ySmDk3ql/GNuGSDPmIGdwFsKUGS/jvbL7jLC3xfVp4JHA2XE+lkrWCOa02xITmyc1TqHZCKeJomArFoDQZoOHbB0yMgTRAHWO5cRF663zgO73LZNmHUSpwOcqzQBEZIsb74foAS0rsbVcM/7lSUoiO/QzwPVfhVueCV6sA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: loki-minio
      namespace: monitoring
    type: Opaque
