---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-oauth
  namespace: monitoring
spec:
  encryptedData:
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: AgAmuVt717v9uz/+/UR+fm3+26Kc8cjB/Kk6XzYszCkEtZZpMNXBJ6CVMtFZqeeCoZnIaSltzSpTBmNdxBoasp9GPy8MXHf9wAVEwcC9uFQZwkQG6qE3dq+XsLK7h4U7T1ih5XdN+IBa5HpDLJZ1o1Yat14oZkejhB1VN6oP8f2Ha36w1wd7sS+TwOC5q3Vv3uaszh5wsorbMHXKnpc5wjfUhofgiG4+5GEvAGrg9Es79AcN5xo3acNAmJR17LB9ZeI/YrqHhoU/4OqI61X3uSFtWNR8A+Rj2vGMHd7HDMi1e8oSEQ7lCXbMn8ZyTxwZd2Q7aBTMod/bjDF+gvwQ+BawePg2Tgw7mficZR0rsBL6t4aKZtbymZwK7G4I/lhTYWES1Em9Rlsc4FQvcUeoDmJLuKVNii1je0N2ob0PhdsAqxETH/9sUX5DqH5Y6tgK8+YdpYC9/gNfiNXPRYkawheKaEukMPZRyKRT3wKI3gcjbVZDQeOPAs1zx8c6FvsyP0UEhchnmUIX6rPSoMfq4E3E9u2pnh/2lQgCGWO+RwxhR+ggr+SwT2oe3b34bCcisjWZDrrAOEIfW/YONYXt8SVjx2lUYf0SpRwUXhDIqZCtk6SERbD7P3qwdrqa2YhrMPdWNoPohIt5VZuFJwAx3mhWkaEuOgKWs4Z6mZVC/Lcl6bHN2fGzm8z5dYGgULweIf+85vjwWxWMMEQOxEpv4DDQklFdNAXVykX5ZN8Di0UMpQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: grafana-oauth
      namespace: monitoring
    type: Opaque
