---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: watchdog-healthcheck
  namespace: monitoring
spec:
  encryptedData:
    url: AgC9kw61OZ/pLQe2Jl9FR09l0WKHtm51ckLiR7cKW4OMkjVOEcTXU89ZxDSO97Kw+KsioOY2Hl2Sr4fQZE2ffShFl84uxO4f5LDpUjcdt5giQbpsvOWO8mQx2k9dvub9gdBHZUzndVJuiX8PC0NA+xV0uSA7oteZAQ9pkckB0zFLC3rrJzc/LMo0IvD8fJLu9fk1hETpl4s3n2rQ7krzrC3g8G2opLUVZ6naN91kp2b+bR1wTRG+yFYQvX9jDsyjNjpe2HpapT7k1hIzGzj2mlj99PDfbrxwAEMrliM/SmwOivFz9gpo6feVmQNSbeUp2G8+zv7s/ukVdYQWk7+YkBjZlzaQ18A9C1SAyOV/szvJ/Nsw5ppfivG1ArllXmErMs1G6sV6BweSQt2fUcwKIauER8WcveP1VUjbmXJSKQ56KPwAsY6e6WCsFK3sT5kCeWNoYBcwu0VR3HwMiKMhbdb6zWkVyTniWM5W/vaOF4TfEvhejYuFJBQ+EpL9ZX07elRAGOGHpQHb/Bsx6N7QeH2MgFnsz6q6eEdHW0blVgvJO0AWp1iQd80+Q7DYdMKLcT7Dq5ZUJZBweMavRWm0SLsjeDs2KAuLqoT3MBW9a0/DbhdYpsDvOmnu1gmYgs7txpulkzAzLOORiE9zts3KK3QjA9GpjbBuUzO3XmZOCOoYM+0lsaUGOIBCUD4lgHdoLKan/1thnNQySwEVHA8zxWenbhmTltStmrDPA9qtd5hsGugkist7J5GoItq5XmMrvPrJH6E70T+OSw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: watchdog-healthcheck
      namespace: monitoring
    type: Opaque
