---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: loki-minio
  namespace: monitoring
spec:
  encryptedData:
    access_key: AgBOv5aIc+KVCl/SCbKYmvlRByI4ZCpVOJeVbKKovuW+LP4ksNkkry18LVLdxNQGL09CEiQ6c3w9gSfLYcGuEy8VcVRQNcCMGfqziQ7M+eEdCnjus673Ab2Z8+u8cPXY2fPePTMjBizaEO0fuI581/Go4uZbDq7NzJA4lyLH9ucWE7T9N29msxk6qzGWGGPlzibjyqp2rd3Dq366vstIxaKNL5ZhsbN3NwJ03ty/4RXYy6hFy0I7pAjNM4odbnFtgm9X4c97q0ooZLdQ370pYhRWD8QTzpKlnxqPz3clTCr3oKa3K8MASSlOV3MtN75TTCXXAnqN11AAeQFYpmxu2Nlo4P/Pr9zE/HS7ih9Kd7wa5O14LHlkl20mKJl7cHovJ0CKwThLX4mr1RF20CPNFFRuriUkuiKhiR624T/UJO/xaz2jU5fa8WLNSWqUPwk5579G8D0zpHBAakUfVIvG8VdTgTLgDjV6VsERIcmj6ycJU3dEiku4UVY0uxKZFkHWnbHCC0J5a/LQDtyVxd20+x3VNKzOM4R8xPxTa1YTXNpmvxS1UaH7M0lUQW2nYrlOrM9f3FN/Q0aaDnTLQcn45s+W4X66xfSfg41+AMllxUvLFBx40wxVOcx5A5tcmQW9iQ432/BkoznOCTel8i5bePvzPPNTBh5l+wVajk1VY2Tm0FIpNHcV1Jy+bYXHuO2lYPx+JabukQ==
    secret_key: AgBFK67Lqo5pYVhWFuHGKmNcVMGJ1q5vHzqpW6KNmfli86YQ3ujO0/sDDQU9EH+jUe+2YAAZB03d+2ltG/Hv1JGaUTbDU+Tir/6rPlg6RDmvnIQ33WzbqN48dDSxrzJt0CoMFW+PtLfQJBmEk87ItCWs0Vz0+T6IPxRC1CaNnjBNCHZuET4OXcowpbWIkX51UnV6fRll5a7QvEa1VNEbhvN+vWjJJYcOTBT3m5gTMSDEzXhnzQEl+Ich1qm+03IC0Vt/Czctgd47OFGwQFtxYypAelSQyP/38sUymR/WsxduluKvYzW/HDCZxsC0rKcaK5vY0UHyAJFnbeOh/9iAeXb0/yR8gMLIVeCAqzdA2R+/NbrjTOZqYmLnMSrTkyca86ev9PqcmXGzIgO6+6eoGAl2u1gnWf4LcdbPKq0gx3xy0/1qrdGMlOrqGdGyfhLIt7fPkRE4i/lMKEib1Bap8HtQeg7vqancO2nI0LjHdEuKkmin8eoQx1yKBcVr5+wgFzjnoJqitepipPKt/vILxs44nOi1gxTuC3rXCKEWr/3k/RLh7BfTZjkjOuuqT4P0d2mV54OqpddNCrOQgWrShMPiF/RogM2URyVBheENZ148YumTkQCED0aoOssnsTD8vllb4Su7I/iSL07oVgkGxuDu/7kx9IH+6wFW7+pLgDdWRxENPAqfwofDpEBjB48OVrZfQJKxLiBWY1mvD2Nq6gx1QocfsQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: loki-minio
      namespace: monitoring
    type: Opaque
