---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: n8n-secret
  namespace: n8n
spec:
  encryptedData:
    N8N_ENCRYPTION_KEY: AgCCfNOnujbVUXwtzPnPSrrZVm5mVEM5n7rsLa/4rZbok57IZn1JjiQDS1XcX2qywjRLkLEcMXFITEZl77f+MRn5wYJ2AnBS1gdYH+iouHX94CcHm/hpCiFTHyCIgW9Qk4GWtRfSsGid8HW10KrQIMoQfN0v05anzJ1bmRTEqw8kMFjKr6rjr78uxvXBcYDooNkHRWGMGLiOiQMIUK8wNxfwfCcF7vakvs7/le83QhfJ5rdlUgfc111ZUkKOd/PKA8sCLi6QTc5CD5gRFHC5EguPEyadCU5quhMcGh9eOj6tKVh39wE4cAv0SxTUn0iEQUrGmRzFU1k7+7X4PtGcJHEGwX5EgzqJC9CzmIyOYuwsnWW8vhhtMEPBtFUz7JhnCjMvoJ+k5v7FD8/ecctDlEDFb+NrrSneR0It4c1cl93bptg4BrXwukIm6swlNOfyqOOH0NP8anLpqvu3Aw55aaIqKLIs5MKXfjKx5tcUq0VbI4lFKyHwu3tZNgU02w7dxpbkDPNxWSlXI2yYOZ4/1gLW9NwKV6wTudFKgWxLk76x11XGKWvYpIIuO0fBpuqa4UFE0D89I3oV5FK61hfuW/gNLEVTTtcsPJ5jTI7Toxr8xSGrzo5poxmt54+iAdmAZlZdXNlWVdlx1qqkSSZ6QXKnSaapxAFudiNaU9+Xl6KcFZlt9dkmoIL9lvSwb3tOeqYJc9Kr2uXMifdnVI0l46naHgdZSThfIELCVt/IHOXpztNAgb5Q8jTHrw61H/yDU2oOBnxZKySTzhJQj413L1b2sQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: n8n-secret
      namespace: n8n
    type: Opaque
