---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: n8n-secret
  namespace: n8n
spec:
  encryptedData:
    N8N_ENCRYPTION_KEY: AgAUGSu5yFI+pSU3nkD7cDoWoP5VywxhFOExTfrHbcpBrEiV86yjM0ofBSoFADtVfVtwgWH7DHQnD6Xv5AOP8RVh0ZC3BSO04ZJPvcH4G5+VYPk0YsGjW8mdOeZZKO4SRDxh5ExjDbCF9gqw9ggARL+kaWbGnYb/seRVKZwk0XuOLP2vpK5W+hqPx4ZTb6iiNq+ZjtDYTOHdANyI/bb46GomFEvk7rjow+saoqv9uWQf4oXlJApjM06JNdu+dwDN6iL7McO9Xok2WJXXhdVygdPcrqVUqHNKbnh8pNaQ2Yva3tga9gvqp9uloW8y6/F2dXUIETgtcn4YFMWng5ukcSovWf7+9G89koSOCpwz9dOpDOvm7a+b4fVgta66dKdMQQmSDB9zPq5zwBcl5Or0Uh5rU8A6j2csmRI0UI91MmWNpXLv39qRSsLubmVZOKN9+TsOQPmkc2XKRd3elxkvzUNMICQB2m83zkJharrpc2o/XGgdg36vgycDQ/9JobnuHlHwzem1qTfey84CpOz+8iPHERIvI6LGPcW/I4dWYc9wUmymS6MCOBMS1bRnBFW0RXWNbx7ODGPPHoodvmdnvW0t5KDafc9cHlgF3t7NBPcLXtVyxhw5p/nIcdFEA30iQzgGM5V/NJnVTEvPQaUi96hWArv+KbeE0hyf7g0v/KrpfCIOV3kIRNX2LM+G5nwSo17edZ09zlo0PdH3cPXOQXBp0hDqxVYzK1JU6KhS3Exq1x8vKMsUZ04MQ1unEXcGFSk+Yli+78Y7zQbOLCIgjWXHJA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: n8n-secret
      namespace: n8n
    type: Opaque
