---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: weyland-cluster-port-k8s-exporter
  namespace: port-k8s-exporter
spec:
  encryptedData:
    PORT_CLIENT_ID: AgAkuyGksUivV4HadQ6HEDKKRauXyesjs9+F+n6CsqnE4P3e6urUC2HW23apX0V6aXGN8qIBpeq37HGUh+clJgndAc+8gUj7nyXV5TkhoCvSnrmHF7kLCQ3DJQ4pwBvPHOok5Cfmco3H54UbuPojWGarXPzHnO9ZmIZA37u+2uMDUMa+UEzSupcngSx9SvfDciBB/C6Ou3iBjZ01Nxib6cKo8xqonxNUyUBXA+7xxel5jCKYV4pfTXPDqckddkjz6a10nOcXS8/zLHTXLlwKvSdf4KFh6HZHA6WNuvbKiu/T8qBKJtXhQwCd5MuE0jLmAKNhC9QaYlBsiR7tgNztyjxCl0VJnq6mQRF3PC9XEc93qF68d0bt9+qNgogbwr5Bj6oesp4om7FS554Z7sPp3DpCj0HD1wDqjjZ5xYruh4r2jWM/PjMiY/mCy3y/ts3x2hHpOYY6ZKUyL55JlgG+OI9WnHb/yq2TFsso4dGU2NqWeMlWltDAI0eD1Vk+LPEgxnSEWEgGzRhg47jFCrKvfXq1bsNGWYA8tYJWZjC0VGFBP5ckhWdUKcqQjuasn+jTC2c2fSs4S0heGrtNFku3XCxfLQ6iq2uoRTfBARglnNjINpokMVjVqh5L+vMsQdC7f0K5KevjOrpQmCD68gLIBZkvi9nYsbD1CohAsznC++lJDf3Kr8Os0aTADB/7wbzNL3oiXUpD/RB4wrU/K49xK7LS42pXxdrUEao5oRprOZD+Mw==
    PORT_CLIENT_SECRET: AgCImzsQ3BvFpxmHS9cLMC9sIvqlTO059j/xXWNuhAtvhPQLH1uV9db3ig9LaJ3IJ7zww0dBFEUS11lFm5tALIfBJRV21TSk7YYf+sXH9nswFKpwF9BNGEGn7fW2DbwEI+Hzdl2n8gMG7NBiYQpBtRhP33hrYKFCxuydl5ivIFkXGRUCWPRXax3Y0MhJz8Ux43JtVyWQhRRx0hXLz0UWa3EmvOIRsHrAMCn8vwbYJ8Z2G3VSVnurMdZrSnskfm3tDGT2xwPly7CZ6Td7P/IOiaT8aiIYmX0hzQ2S4spQasr5D7oWA4de7esPU/Qo7WSf/4YkjZxIJ8EvxnTZDza0M8m4pRI02j1EJ9AdTAYb7qjHalWnIOVCxgxWeIX7LPUedXQvD/g2va0UEVOrlPKZlMia9k/0XzqcKbsrP317vVAec9lfPxEMHO/vmKMq072gKXv2Bv8UdQMYt1g9MUZ4KTInlFeFMdKyxqP7ESJ4FFhRv0Ea/t9/o4lLkd5Tlm1uFYnv7cM/TVMNwTocuBb/o5ntUHybJEdWuUgd3W6lBd+mtzFtOi55gOmBRiZoreA0HfDCwiKrjNT9k+DnhgyWrobqp+isrQlc6J1u/1HmGA0gpJT7pK2ekXDUKBjAHvunGEE0nZnHo4OO5ifJZQkgOglPOxpd09931qWSw08oaMQb7/x8qR0YyytMpn4gBGg9YgD5tPiXE3SfaPlkex3gvC1U9kX+JfCB+tefoLDRDo9Tx4Rdunb5TR5RsCQ1+mnH09vgRrk/bbqeGzeQkYMJdjKC
  template:
    metadata:
      annotations:
        meta.helm.sh/release-name: weyland-cluster
        meta.helm.sh/release-namespace: port-k8s-exporter
        sealedsecrets.bitnami.com/managed: "true"
      labels:
        app.kubernetes.io/instance: weyland-cluster
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: port-k8s-exporter
        app.kubernetes.io/version: 0.7.4
        helm.sh/chart: port-k8s-exporter-0.3.28
      name: weyland-cluster-port-k8s-exporter
      namespace: port-k8s-exporter
    type: opaque
