---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sonarqube-secret
  namespace: weyland
spec:
  encryptedData:
    SONAR_JDBC_PASSWORD: AgA4dwws9K6rZXNCVNBR5QEIDweOv2Hezu6ID7q2B8st5hKLr0oCIrXFCMxLLSy6Iokqnt/OOYZtvWFRN0Deb/PtMM7ad2wYjEDOmSgJ1gjxjULdD5lXEnm++S7kznqIpkXPn02D/qs8mi5Cga1EU/KhXrKzr7GcjjImbQmu1lY0vmSYi+BI9XFtJXk/uYVkz9w+MQ1JvzGzKLsNnBKhZygokf3LcJv58MCBsVYImuKCuzlGOU5L4jtZNA0lkX11TYMOIzxJfK4A7mmh9G5BmazRRa9F8lMAiXnSDPMiObIMTieniBFEF2Qbu5LEjhrnsm669Fn/RFHHmJ3qDF4rhnqbc0gNJmlsAaBMwSVZ22UUGUym42AME5Ryw2DmfZ/ENOd5TEO5wzvbgmKwMVc1bMfURwuZFVKly+H8wPlfXbNcFu6MLmK4NYdMyOq/hNAO8CveK4qstoenmE4UUcd+lgn8MG2xk9ARxXmEhTDyuuDo7ZFY1P4gzG8+jkXoL0Sz0slhQf8S4X8akl1PhnGP+deRYLWhPPRByIGpZ2XO+s/aiEGVj7qLj+T4r/0xL/j/BaMmC8rYtQstP9RyHY2dPF8GPhIsw6SbMgim1i9d25TmZAT4DBfp10vQUXPNqQRpkuz/yz4DH/VfZnK85V2GJjtOfDIet6x0+1MFJ0ZMdMYO0wT2POUNgtAL3e5cqvQKUm4CFKsUFSo3ZboKjpr5cHuuglqgMQ==
    SONAR_JDBC_USERNAME: AgA1m0S/IpovSXeZK+7MHnbNj4TXXeaHeNQ+dfH7OgHT6t9NeWmbz6ODYKuRgGO3ujWKdJNHCL1X/UzJA1T85eUh0zt6uzanYqhhZZj0SAoEnkd9Fl+zvzZXoE8N2WAxnxl7G4KO/axflqSX8/f61FOBsd8lZgC+vwWOyZwfMGYmSgSOUag+pQqvacc8NDjBFRCzvtX1B1r0sEuiOGhj9E0YqkkJdNRfO/HA6kgY73f54cZwe/8UmIUs36kNVzZ0KT8Vz7NHHsre4UoDBBu2U3Q00PtaIivWVWRK0ftt9rXRr6NFOiuHBVF3aW4u6bBe/goybyqwL4ofGgsfayZBgzU0gml4q8Y2UcQKoDgZhKZJPT/6FHYWEFmXiNd3C+8/S6LJdAyxC7/+AutiBzrakO1md1ebRbhml9YBVt7raKHPJcA4+HtieQPjaAEhxPLGVUXzp3MD/qGFAcjwkgmwo+WfV16mN/3BM1LNP1+tA3xYyq9JfJiTPnH+L+bmh7Bv+ggeMSMW1CnL86ldIvbCNU/MEV/shqxSlUwz1e1/qxnO2aeblF7PGwijFMHuEYv8tEzSA1AgscndqzSL0wyFj3tlaqy7iPwTymwKqGhvTzwzQ0MHPPt/AFcpIPmWljq9W3i+gDzxBeaFmq4TiYwMvRDP/mY3TS9EhZIjBdQwdSVy2poVYdP8p72iyFiHOpy7zZ49oXEb1LSULqU=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: sonarqube-secret
      namespace: weyland
    type: Opaque
