---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: aidlc-kb-minio-secret
  namespace: weyland
spec:
  encryptedData:
    access_key: AgBnSFX+rlZhUT12GJXII81WoyenaywKtfzffCrUWqnB4hPTAFEr6aw7kVJ7ZQgLZOTs2HPu7TtqDF5xxpj8fpBjM4gQmEBeauHKnzPy+MpUP9WivesipSY20WTwR025DgA7iYNImtdL9wz97mvC3q1hVEDCYg1+OVx+CxfvnkRnNSOni7T6yVE1tZyG1+DuQIbUoyDs1t0aSm7rn8iJRjFJx4A0mMhTIAprkHda8XW5sArazcv+ArQyxdXl5lXEtN26Q4KJh9H0z/1HJAcipahqnCQSe9pgJD5jv04KBnkDaGvSUFRQ5JsQPeeH60O71jZdlE1wSUOB8sBR12djTNuv9F+eDdIJ/OX3PZNYtnPvThT6mj7bAoJqW66X4/62kCCmaASrggNhwfMJGP4SHPBi+Z0AtPpoeLoNqkxzQDWCSBB/RUyHHMiu2VNmmzdJDnuV44+7JBzf8Zge0J3kzeLGC28IPk4Yv9jOEacNcalcW+jpzc8adR7CgOffdk0Y00qXBqBG8Fnp2AaZ1Qv2hvuSPmcSP/Hq9Sh2xeCtckVM09tJcofwjsSfHxGhbcNBz/e3egPKvq/gLDdBX1ClF5a+CzoP4VhptZXnB3/0FDyLv4lW7HXkKzV8gZvqduvskG9FaSaaqeTSBBOWpsKmzeaUE9FBd0JM3oyEUPcq63W1daj086ypCrYbsTMhzdEQIHLtZdabRQ==
    secret_key: AgAJMpoPziRBlCl5JXpVPJmremRvf8f2ga19hDv3Q0PFdJFSwHUYYmceJqeatbumf7Gnmy91OsiCP7Dja42DsofHYUIZ3riOnTAY+GunuYCsp2TpRBYPkZF52hwjX7ClVVYlaiFToUIQijZl4ScHvjTr6nM11/7bZG/Q3bhHdzVmA8cM+yROGh5uaKfX7a3mop9QHyENy/a8z1vKg70l3OMARicw+KQG5qV7TiX5tiHL9XLCpZY+4Vb1aCM8+kOr4bFv5oiQtCojAt5fE1ZK3KdZ/5K0Q0XNXFlhD/iI852JV7NlYqUFQ9ioHNWhkNXkpYCi1je/WehWncx/hZDuhS/z3JScZd5KafBGNyNMgye1pMXulVQcJkOnSZbKmkQw8fvL2eszVuwxMeOOuMEgy0VCWh0t/vyf/FD4ESKIi8yjURnE0VNJT39hgnnAb5QtoFe+F7RcCY7AkT+6r0y6aTOsM1yFaNP2WX5xwntIuUJadNY7EdZTpJL1x0pEvPJ0AxKiH6MGK+v2pPbpy9d2Q5hEg7GAqjh6XNUERv/yGCf//Q7/m0/wq0fv7xwkP10urdhXfYBDe6sGMdkHWVSXrQwitta6POqZb1M9mk9ZMicUYE50R07CW98g1gGQnFCH0X3+UW7xnnQaphZZOQeAHQVgYTDGVqY5CdZIpRAYyzhvWLLiKEeml3BJ3wfd/wljuj2kzIZcirNxmZniDi4hfqvyUjMX8Q==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: aidlc-kb-minio-secret
      namespace: weyland
    type: Opaque
