---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dagster-sentry
  namespace: weyland
spec:
  encryptedData:
    SENTRY_DSN: AgCTqzSTM6IEjjHdxgxuXlUk7SrG3NsIkgvP/jAk/Iqr/Vikls65IwYdpxnpMA9RwtdyJ6rBJxIhRHLk7JwblWCj5U4u+WRyaLvX2a+AFvm9JPDDa+KF8q1+2x6PV+F3A0jvOEh/qwlmC18xVJzqe/N5qj/yeMAV/GsP5Etbcja7WC6MXxfpAA+1p2ilnRr2kki5D5Bz29t5TpvTe+ds3oxdn684ms6x4CrwRUaxErQLJfyhplhgzXTRkDoR/D1Vkj5dn1AnLdXBico8Zx+i2NavZ38lKFuMOk0fGxLWLsblleVVCyukkj5UFOcFcjnDTKM5/zc/C0L2aFAWktS1f1VDJRHiUzvu1U+iUoiSl/BD/Kuq+1KIASSB1AS0+JY2tPIwxDkEOyU/VWf1Q/KM1eQraCkrPXxIl/BfwNweybET7ZswuEXy7ociHOOjUWIxZgfklt47sQs3mbhtesf0SEqVIoogKXxjwKWj1F511O/MGC11jVlcvQM9/lj7sJ5uHcg38udnKgORk34wouRLBiDOcLNiG5YkzIZPsTGP/m1ud3Hoz5BtrIF/4Y/NxftFg1UgiNeWmiKAxlna4Oi0OS9d/aAc6xA1ADq9OgtqpFzndXACGuUr7sfZoYS/tPorvr965mFEtuhMeA8wWtercO4u1O3j57fFz0AkjwawBYZ1VKTBMwZFJ/4reX+F7cuF6mFpzWEDLL8oPErm/POYfOkSmCdQF9An2PAAH40huTIyCJ7gJtgWeSuptvdfh+BEs7p67SPuh6WNj87kp0vuAkqPebYnICKI474Pf8+IFgTRUpJz
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: dagster-sentry
      namespace: weyland
    type: Opaque
