---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: linear-backup-secret
  namespace: weyland
spec:
  encryptedData:
    LINEAR_API_KEY_RO: AgApoCFAB3zQypsMrGMfYAQBoyZhZfqPEZmgfCCMgWsRVAF0J8aK51SojeYEhcEXv8MWJnevK+0HsdaLj53SuoJ086PuNGqB9TDlYu85na6mrXHDJGA2MpnRlBXc5WNYC0BXcV5TEq2H1ikjS48RUsBhRI2/m9uUmPuder2ExdtkGzB2Enpi+jrUXrSyvTfAXageQctqxZrfNv75HC4xGTTX3ulLqFRXxQRySdIDqqiC7yt62QxETaDaVbQR5+Aut3PpRY3uPsAnAPPuZ9cJ0vHMinz6cq1kPXt7ylBLBTap8s7tKwrC2B2+DGH1FJmiRy+oJbVj7iL98ORMMCMui3t+zem8YHqrCx0UwnpU6lPnVr/ltNSeJZxseSkBR15WDHG6M/ZzvWgnaQa9RPzEQnlaFs/a+yfH+Y4Sdn/nGqbx08sk2ltnq7VuGMdJtiC0hiD8bYD3FB0EtF6xMpRkgREFx+EAQodUcFTKT4uy2oPWg+MUmbOwKDcqhv5z7WYzt4vxtqSUGNdBNCeOWkBsSgvpF7i2eL2Dy2tumrBa7+wjfXy86iJ2I5Uz90Agc6ywE1EaKHSQUuR1iIqEw7ZdwEzsWY/RBpdEcPxrrXGjLJomGNGGPJI2BR1Z3xyDsp0CKCn5th17m/xPzeyCFMkM0gthcV5fuAXZYGEsA8nsU43Q7eD8er+Qs+/ujmJyfd+dsSr2+H3KFJ0FYzcZcPeHtbsh5toQVqTK+ZGjPr5x4QwR5VXJB41mlLiL8nw/mEQRqsw=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: linear-backup-secret
      namespace: weyland
    type: Opaque
