---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: fred-secret
  namespace: weyland
spec:
  encryptedData:
    FRED_API_KEY: AgAOmYrhm47Ou/2td43K8+cr2q3CtWTdx8EINWx4m1aJgIu45qAiRAlzycDReJaF3TEB1bRyoNniz5d0DtHFIaJzcA3zl9chV6BNEKrYaFStf4V+Q7maTT4XHFKKhPMGA49uso4AtlAGeBhPPQwMV65IKiZa0PLgpnYS1g27/BGbEs5oVYokFl8Ij4ulHM4ya64hYqWqEQd7xAonMfQ/CKxvsj6LTbIs93OgGXqnfpZrV6sAzKuXqstPt0bNFyGl614dKWt5N0CvCEpbQWw5qLG6RqDB/fra8zWyhzoBhEBb1imKwckWng9mpDbobdTSENkmbFHPNUU5xvAeSECMl59mffiHG6KapGpb9ImidCiG/QS4dqY6b4JcA66tEPIliyXX+7cvF2Yk+4xlwdbyBvVmun3TgBAOaSMZst9a2Xn6B2y3dT6WJhScPSH0rU2dkEUPAHclv+uhqT8JEdgI/iesxZOY95/9Kbj/bp2xUuTgXk7I/3EcS42vNR1tGYd2CKSVJtm3FiTKtPfNfuoQJwtuF9XcHh+jO0Bp8gwZWeXGSHC1fV0Ts4NzjGRkWXfcovhydpvU5kNCJl93AYeKgUmMh45c1/mwwz6x1qlc+uMb3VBZYxEaN37hipdnnF5zWN6/8C4N6BwZ1hHlvPQAWg7r6/BaMMBfkPscWTLb67oE7QTpfTGuKK04qGwoikWNeg3BVEVObsoAz1dZ77GoVD9UffE9HWBJNcfV4iD6EYjF8w==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: fred-secret
      namespace: weyland
    type: Opaque
