---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: apisix-secret
  namespace: weyland
spec:
  encryptedData:
    APISIX_ADMIN_KEY: AgAdz/z1Y2aDmLdL8+LfOmD0bH0RV6CKD86AoY+Wwjcfq7fgjElkrbwrruhG7be8R/Nf3cZwCDHbjzYJIxvi1dsE3OJBCYulSfQc5JxIJefkdkvY2ufNnkEBloH0SmIyTHOqrkRGlflyIuIqww4nb6aq2aXIvEnsP/hgGJow+YeFQKgXCtjt+PrOmDkRXro7IiQuRNn0O8xEQDduEv7LLgr/Qz4Czf8KH06KtyoOIl3iKG7j1oUNqJgGJRETgkFy9axL9Uu5yLa2BX7mhL9e8wIkbz6R1UNrCRsZ8hZsokxdCMcJCs+XLGPvYQDj/j+RWoVZzYncVzZbmKxUh7JWAu244Hr6y8o7rrqMd5tFKMjIR9B75TTgMiyG7GTsgRnPXRg6HaXFmBD26YHde36iGCmtlVA1feMJIrznkjO0ulIm0EN2TEN9bE6C+wf8SnAcnYDZiD5QoDAVADqfNKBQYGMlna0z+CUXdmOJhKxjS9iDx5uJ6ox1jB7vnkXAFrHfA0Clv4Z6+wVz8V5p50JkY5vkag3inOOWYOr2UCq8nWYCdcgAqS6viWWep36fVh4aIdxXd3wkE1HBP3HGLyswDL5ocGpN9vVavyhdyougsp7eeAJooeAMYN3EslLCHjH9TtheAy/EA1YJ8mc2cLbk59QcjFqAC3lefqFqJJWNZz4hgCpo/hwhKetwwC8qa/LDZ0Xw7IC4v2FPoiAcgqowZEBYKtLoI/j1VCeJEpB8PnTnJXYefLKwwE0zC5AHjLmxPj30RQxWtmirXeBaBG/bUx5X
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: apisix-secret
      namespace: weyland
    type: Opaque
