---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: open-webui-oauth
  namespace: weyland
spec:
  encryptedData:
    OAUTH_CLIENT_SECRET: AgCPfK7PCSm3I93COXDfKdkNLv4dKXqNKT+JgCv+jsSwwrz3+NL+Tdu6hgZKJJGyNjPTCDlYdUclNZRLd7/BMsn+MhZtMimLIYFMgPKQhAcQbrXFrUBAJjNa0qLc9KYo/sT6EUcfr44rAMgdY1F8xwm815Ix5NaVhITLv/uneRSDSa9iU4wAp0PBL3aZc38F99SvsBb+ISlQ3uW5RKuhSescK7WhmzQvH0DhfbWRvygIuhij3Ew/iBw5d+WItn4qZSTEnxWDr59kdOu9JilAE0aNJUl1zBc4IcOdlmk8ybe1iAc3R05Uw/IuRRGUxuFxPoqifH2ILdNxlqaacvYpPekWUUmZv94mFhrXUfoOvhYqr+j6gZzRKBrcjDVeyf+XeEVhNWj3j6A6SGUP5Q8k/P1JhX+QIWeCbYyBmjdixPveMaWIL5BV32VkKToRCRAfS/whE2/JqwFl4QTUVNLEQcFEcBQCpOPV6gSFjjyH98XLS91fqEvwGmyxclFbOH4R/B27kEn/ceZPXS8c1g3wlyeTLwupPumvMADUBcYEcMlwzYWaErOPmPhqPyW+UfU4NZeLFNbp12ocdQm2xef/kF2EOM+4T/yUo5fyLoCv4TFEqHodA2r24hhLlbvEg/MB0j7R3iOJUyFR0yNADjbeAZLMoBtnLFR+i5kuqEHA+GOxBbzyXE4/zQaAzbjoGAk1Hv8AaLxSuCwVtIWf3cRlHnZ4z68BX7zdTtrVB2vLDuW9xg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: open-webui-oauth
      namespace: weyland
    type: Opaque
