---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: port-pr-reconcile-creds
  namespace: weyland
spec:
  encryptedData:
    clientId: AgC9clUFcTeauf8Eb4111yMZoAm0CuW8sx9zCkyDhgToLFJfYYS7RiWBViUWrYmdywifHDQIDoIMvksIF3cOxsRuZNACdHeIIeXmXK0kgrEfBdrv7DrEa3v5/xgOyLXTMihUel6a/V2my5lHEG3329PX0fQVXsO0sbmG6gVdg/lX0tjwqg9LHl83E34YPbht/oZmBp3JylRWzo9TnY5AUkJB+zSN2FbZIxgTpxA1FOHAvOeA67QdngMdp3MtVsyVe1pJYEUtyiQrd1L7UuD+MBjK6dLb2rYPSy7fz2Tr1qDu5H+LIAUIiqkiKaDrcfkG57znDZItvmMPDZtP2e3CaLUl8y+27l/Bhr7182Br8VfZ8vQc0473/8oHASKfrHVUPBSjHQlpEQBXtHOP135yWkgYXF34oU3+D6UlRUnBBPIJ0OcF36CTuHPsfKRebSYzUwsGLN5hoITv6qmQ+bVQuehPtoMgc1tGAIm39lAEGVY4SHmPzhZr8ydSA7ExZ4j0OlvW/pXru9fqnomz0fDD0jL56w/Kh76GlnqRBxnoSql0Qqpl+TeARfFnxHIRR5ofHvbA7eVyHZjOeIMoPp3IBq8vgEf2vZd2HjaPh5Li7h1OFtqNGn2TraWVGKYxbEYupjTPb9twHpnq4o42J1dGP3YjOyH5EmNtXoE+BTZfRW6xVDfKaaiqqydgYZPpCl2B6bpwDbM7grnstPLp017VUOZFerSUVkmzCuolh5WJIBPlRg==
    clientSecret: AgAOhrH0gcv8xseGTEaWenMa/kVkz2OixWtBSluZB5AEMUIEy6Mb9FAxOKlrEC/vZsjPJb2QtmZevw0K1H3dQzbiAVuzOPoldgss3qa+sBRsXacuiolFKxlZKnbSdE1PCCpHkVNkQ9dBnGuwbSq/oajXj57xMjL1Tk6ftvsgfckMznx9hoacz7O11zRSu1JoVmZ3NWX3nhqGnW0FMNxpZAEluOBudwwyD8ypo0Gs4vMhNdfxiUHgpLjpZJgvPp3fcAjZ6QYqbacFhhNgsK+xCIPA8bXd7Eq+zQzsTgQthh37DX3nqqd41n8Hizc0ldePjIOMXOP6/r6P7sI85wv1fbLzBwxo5QTfu8Rh2fbkjHQNtOoGHvnTpWw9eC8ezY+reJTu/OfoiCbknoZLkrWC59+Tb2JEpoXeeoCEVtJufgOaXY5qVjAD0Edy3D3ISHwXk3NO9mhXZnFBD7Lmeb2IqAnEax7lWlU6BTF2TyormXIO0i13IsTVQd68MeE2BUkw06OCeaESiSgvlUDkkoke8W2JFt5uLvDcW60Tn5LYXSpI48YAPWM5ruX0t9mRFemHdh5/DKKhDX7aNnEvB8+jAJxOZfWPILEsuGzMFqG5n06tIGeowQJEbOzJKML1LAAQOy1WmRcxUgrFlGW853jwCvKsxDyfQi5JYEVBauWKYIIF79pmkGPlp3VomxnH07eOWvq4WsB1VgqZCuLBHkAI/pNML3OEMlGnKu8eOA2NKrARTgKHd+XjjEBQixMSQQp7gRWO03sFrfeiKbYQXc9Hzdk7
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: port-pr-reconcile-creds
      namespace: weyland
    type: Opaque
