---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: neo4j-secret
  namespace: weyland
spec:
  encryptedData:
    auth: AgCWWpoIcbpZw9ER77NU7b47luLlVZrtWqBSE8AteLGIpMnzrl5Ff+BxJRpelu0RDbptjd3EWjDgs74NgOXeLV2mncT2ULvRdXdJygaJYZmrgWo2BKTreA96Npyq2S71E3NXxdBOXsP3o/s8Qtms9JjypL5nTRfRjI5u25RubfrFEDEHz+++i2uRAgV1XCmXpojSzEPjQfl8adI6+urEOI3muPyacUPViiZJ26wV3uaDZvbFeuVrcHmysoJs9u7NIUA7ZgjH+v3kNSaAkNmCEZzJas6Rfx2aWjCJ7SUIRBvlKBpH9Nd4NhAB7SEv46ksXBJ8zYjY3WSzXedXbUZLayeKIEpl7+qQknEStsQSjeF4cGhiBWtR7DAWMfnktJ621SEBHivfNFAUKJ73o9+2Q94GySH1dOQtyt80MN/0jqLGKIaSjSK9YVmIE5Wt3UKSl41xjGW2AJsO8s76M7S2TtOMY7cW3nMkhYf+T4gbtcUK4ZCaQDw/TfFvhJFvXq/Ab/qjut41GZI9ntMeIgA3ToPQ9mlNVckLCPzlhTWRosVa1K8Ow6HGMpzFlKOrCn7QQ5N7PWXGHFUf40Mhhe1/fGu9q1H3mEgZHW5CzVo/uv9AKSEr2iICgKud9BN/A4tvuAjfI/A+A7BMYG6KsLKVlstWHWBnY4GrBy8JPVPLziJ6GOoXFrXrl3dBdcOjX2+c1WHXhXg5xeNA4PTH3Zg5liMNfJW7PLsMogGaFA==
    password: AgA8WHGXoqfOU3vkamXDQB3eXJ/Deg5xw+NvHOA69HuLV7uqTt+RxJ8ylITHSDSgF0sXu61lg+8v7s7+YeKh1fO9Ax+8mBWtT8epBstA2mIVcyHpYBt+4HyqapecPopW09E87kpD0DopmpBgEDNNf+yiFHhmQ/QHGa+G9SytoHgTpGlv0oI/iNtllmzCkX1kPg+C26tO9DGYddjnSWeQp2cF2R1ojFcVQwngqExjQy3/9TtsRqju48haJulNt0TJQAEjS/qQSDTijBf0GI7x5kxnAFrrrLejA9kZGFAx27hjxKgQyxC4LJaqzx5dVgVGGK5r9lj5fpY1gsNQb3WC2R58wrRnhxuVK8DF7xI874vW3dsAalkA2GVwS9wZUJs8tVPXC5BdKzjhTXbRu34AwdO2nZtQL0kdVsgy+SCXLHs5KgxFdeqXg30efj/ZVG+LjDD3A0beaW79u3eESzuc3e2Vrv6pBGRdD9ieFcTEmgc/vzu27o0VQp+3h7IBwvpJrOWXfnXWBhWqyo9FC/Oqrlb643yaiGevI9Z0RxjngLGkfnYgOsuqWSgrYgR/+WisugCrYGKy4/wAp/OCjLbhLH3ONMx96W3m3jDtCtGEiIExGkErUVD9/YRjCGSlK1r8Et6n4havjrLKY9507QkruCj+ZlEXRAol/Rz9MEk/Z1raG4xSuhVgU1UXOblPnKPYo7D3wWoX2CUfEGvwMqL2WtoZQ6/WuQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: neo4j-secret
      namespace: weyland
    type: Opaque
