---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mlflow-auth
  namespace: weyland
spec:
  encryptedData:
    users: AgC5iFoLGY8moXYok3/GMajhkGmklJRCEO9+Y0AImxdDkB2k68JbyWbyHLH0N4gagEuHwhBU6C5OumqDxYHFGsgMJSJZJOKxFcCbAC6inLJgG30b2tEYYUmiVp74iPHvUIGt4VyAv9hPdsooZ6WXXUI1l3HC4ZT55pv01Dsn7qtibdj8gmiFkAPybhSfALtU8D9CvZFgHZ95nSqbFe+dw9OL5PBeSOe0gnNCvv80fAVMbFqNwFAywt9Pd5osoRwx2WvTDcp+78i7RVpJCQgPfwIZs9kJqag9UISDvqD0raxM71LEsRtl6IOUjpDK3M/ji4oLfh+1KKWaJAc5OxKmKsw6icLQk9dkSkSspOa13A+0KT3rAU9Y9Ks3xioytxb0+GGIpZ1YSPQ9N30OBiE+45P2LEjnwOZBhMAzXCNCnCZj+cxcgD8T/hh9WKNNCospBFsi+gb0PIrZZWx92bh+5Y3BLuHT3TuISmVVAMyUA3X0ltmq8j/dZU+nKL9dxJSci181j36Os4tNIuiG7sdXVY/1Y5SgMFMqw8E9/Nq+lpEEQmZbLKIPs/LJfffZm7MatlahtCitYUrojQrM8KHHLgaU9jyuZqdn0o6YTfQyIntKhLqOQzPBd4gekBdxxfwh6PhmAbDB1AO4HdYsJ+Fg6mdtNqM4G+JMdDkgxqD/ru7SCNicn6jTmy6VFpEYyRrUCSsk7M80yvJ2hb5b/GUV9O/O0miBWvDfwBrk2aFzDoy++0xlErQ5aG8x2lxx
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: mlflow-auth
      namespace: weyland
    type: Opaque
