---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pr-lifecycle-reconcile-github
  namespace: weyland
spec:
  encryptedData:
    token: AgByFYxyB/6c5X8fCbuCbVf7iiJXZYJ4K2NHaq67wzuvPU2oBZsy8aejoiVaNJbz18vwefYtnGED5MG5II9xSfCLoTUTtXYnlg03TYnsPahNGJJw5c3wiGp62er1AU1UM4KlfXj5Y/3p7sp91WlYocgeylVh2LRptKWLVrc0C/mLW+e+Yzen9yO8Ew+ka8vlJ5M8WZuoYaeCghRGx70rUTfKTgOhCnXr+7c/IvGWu8Bd1dLXNmKSUOA16hN+1h2qdLOXMxZoNJz/vIo3sMxgDOFI7FrU74pzISnsxUZlnWGr+QUJp9cwri9wZmrT3wC6yFHzSmE8L9HKteUByv9MnGPVRgPWKZY8fFqYzR+onT0lRzfOpUiDd7YwZNmm1wUZYmhO5cScLixKS/Ye3NTc8emBFIOGIN9/9/Oh0HViGkPRgMdqsTRA9JBxxoSTTc+DfIBq6WOwgCLaI8tvIM0K5LZd5hMMInjGYE0UOyUhYg7BRpN9JpXUf/kIcja8Xhq2mMGEVdulr3Q9DiG8K9SlHjei+MMPiiCqrEuXPVCCSA4qrYr9NUYOt+qDiz+iOLsNEAwy1+7J9AUScpBvCrXMKhY+FH0kZDBegixY+zO4QO+igETCuOOaD16azbFHsAR/d0jFjSlBsSQ+OVQBoQeQcpnIR+hyDMnAKf9vISSq/yds+b0+Ykxe8JnQ54+f6f2fSnKfK21j8yRP5+j2WQcAg+WIw00746bwhZa8doluzoLfnaAVHgbiVQ44JAgS03FokhVYQl2i9Bj8qplxKnA1IbhxwDzt/XZe1/5LLdUJU56WrwHpeTqGWHdohHAAXmU=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: pr-lifecycle-reconcile-github
      namespace: weyland
    type: Opaque
