---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: port-creds
  namespace: weyland
spec:
  encryptedData:
    PORT_CLIENT_ID: AgAz3UXeofQKXodG0CzW/hYwfaqSCagHGRG7jJpZkWLVyyLnSq/BURxZyQv+id8GlFb3+XnMIHzGAIm2D53iux1ctQ5OiqLEZNu6mo3CKCTBkB4Dd7/uimFN9qcxmelqd4pzcLp4MFRRaSNA54cgqnW6qfiMpri7DNUPeKuC960qyZdgv6qWVZ/9IL75bsgfvMiz0duLO/3scJKKhiwUP6gZ6pHHGbGGQ+cLuL5iE6KfHQwUTDI66Byy01zOgQY4rB0vtu2gib+upwJj2cPKBN7fRymAbmmJC8BMhiAwskfEmUJwV8KoPSsraj6kDL2XTbizF/V0siT2F0YLSVRrI3ntzAo+1juUQ6CvUfHdDE+GgHY6+gHiaF70fOCwdl5dFVmS3MMqngq1z60D1Qblpa+kYvTn8D9gq53hX0js7XHzyYV9Us2zLcFQ89XbrA3TGAwKpFuLH5QbQzGYE1SS55giBH9/4xJMK9EHgTYZ1GVO9gqXSq004RhMxJFr6sNkeaETNyXmzds8tfgnH0/xJ3mdZvCHvoULGVD1M4PzsKjiinYb3I+k9PTkVW/NmaTLc88HwxNLPxHDEhqP9CQPUy1q5nk1T9s5Vzs8CA2OZTXhP010rjLnmQV6j43RNQJeGyQaJg1Vv35QJ1xt5V5kQ0wTFsmvSHIx29DZr+ZJOKTgq3lKadL8NIYAg9iLQWhv83l0iDLogbWV
    PORT_CLIENT_SECRET: AgBUGKPnA7LBwOJB0KgQW5u5H62Ab5u44rwRguL66+ESXF2bOYn7O+GkR7xCKOuHUJj1DcKt9toxZxeXUHKeSp5jbVB8P+FKRP3+M+cv22oN0rkyg/wooEKEg85BgxQ1ifUAmM9lYi5TgOr7OVHX48nm+AhVM6C6hiWUiJ+eJECLWq8wD2mu8sQV2Z+PFhgcK7FIN8MsBOAfdqlQZ5CxNYkU2Ktqnae/BvdORTe5G8vaaZ4l3Xbc6ag00ldGBQy2JaENY63o1ekSokd63SKoQW9uvTCBW74l/2RKCkUMyKFgd4ubODluz9GdNFhKh1zrHFXe1HdsST2NeBmo8EvJaJy/PiL4Y67oXDpOZhOyxvj24Z6NCD6BUhchE8HIMsK9ZYmQ/SaThzcMqMGJ4lQWO28bHwEvnN4DEBSX8WMHGnQG2PR9Urg2F5OHixUn6x4twh1K3M/RTTRdOD+AEIcqRsCgg9zDV45rei7wIA1dWuDZ0MhHb8WVVTe4//LzXv2b62sqh8C/TMC0xPnR7sCG30bfwU86VkJ0F7afQg1m25oylc4J0tOSbU+vCO/zWHjt1b0QR+QUkVh22gRH9iz/8dPFOKUJNPtdbUbfUOga1PKG5HaOCODpSy6t7MU+3HVSwxL2t+Iz30iz7vjUY9C2YK7a4O18Hb14Ps3B8PjEWa1V/GjRX7loaoT6NiWoXeWZyHxY0mMaedDlUcqhDA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: port-creds
      namespace: weyland
    type: Opaque
