---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tool-server-sentry
  namespace: weyland
spec:
  encryptedData:
    SENTRY_DSN: AgAaoQU5m4EWDaktNgFAJJVP1lyxoY0ukHm9bFLimukx6tcFTes8EhjEmvVo+Y84cqD0WYgm88+sno5Bvrf+iyxXaCoijIr4pyixMSF1rOMwaWmHGFusUkpBocH5mzZ+5ANu9h3eOlJNt8lBaFNmX1qXWeE1pqrVTJfNzp1Qa3uOd/INSMA517hHaT7qGcWh4qWPCgt4ftxKaZUvnaHFMtPjc4ICjPmHMMowpkA1VE4fqadpHQgUmdqj1SbPDfOEF1+robUOioWQFthIn5sg0SMiMdiOvbKObpTDZfq2jER/UIXXIAvHxTeeLCCrwm9fCHR/KiOAre024MZTwgd9hJjOp/onoexy3ZVYiAZK3W4r3sKx/qH1WatckI7JNukZH9ZyZ6ZiiWTS3sfyP+sWxd2C3g57xE/1z3XFo7FPpf0HiHQr/BsdIU5RyMLMhKxaBR9rGp+4GqfL1CBhhmf50WcC4v7gAmF8frFoqLkorB8rcF5bMLdmBykvBTVsnnPQO/XZ/nkvZcuEibU2+iiaZwiG/aShVgUGmmlKZOtk9HzSlccFfJuMtyszjHWTZFbVwZ6J0xnW3KOvWApN3psyIcgwbd2f1+IIL9VGFIYrZcDWCOrWRKHnrErNG2M/ExlwupF0jPWvch9M4+rW/HdZwhNcHTYQnAM/SHPHsAK4I7RP9z77dUKnSUK55Pv7/N1Ayxw577MWz/fCb4BP+sPNRL735XNUaIaAT/pkOCuTrAsoP1ME3WaXaWHar5BEv9sog1OqpBOqETJ0Dcw+wi3ufP6eQ15QWyLcI/0J95z46hE/VE+E
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: tool-server-sentry
      namespace: weyland
    type: Opaque
