---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ray-auth
  namespace: weyland
spec:
  encryptedData:
    token: AgAGBJ91y0wdUbe50/0q7RCy3Ek5UWFUHo8/FVyGozZQ9e0VX9pLVOT8ZCC1crHb9aJvf+4cHG8ap1b4+/xnLCWqI5e5JAzBU8nTFgkL8uHXE4dUG434t2BIvy2mInFRy+sfXDiy/yicJPeKkw8LQnWhyGDh0x5FO/sk0fBnL4fByPmM0TdKqMhjvYu+ybY6Ofzhqe44KLjvy5LBVFC9GnxZ7Pdiex1Aok+UXOBz1dk7Rk2ndRaARNMuJiGPVkHyE094lS0biZJzOQrlx1Jf9f90Z6xBvqh1LW/WwULDsVSbVtmXhqGfleE55LoyKWnXT5v9QlAF0QCDSsJv6cEwVpjBcBJpU/u96453ENKJ+sPxJwbi8ffGtrsFYP9eW1fJor6wjyoD8CTPrIZVCO/9HAEDA9Kmg/Hf8I823a7K5BZdglKU6F7E+h7JV1g/+kW9ml4eDKfM9Cc6LZl7bFwg0gF+k1CZrkdWWX4fqJ1JZQC4PzO3aVbp5alFrRsuqIw1GfcaX1t2pTk1J3xvRtmjKax9vjJvosQ+9qLDAhOdeyso2CBS4Le11tjc1okpiMILe84OUpui1O3GqzfyINE45GfPNwHp/Inr5fRSchhMisUiSjjJblGQBZTIf9+7+4lDFQ+EzXCz2TD9AC86l7uO0bR/6R30o2F2ixZSperpGb+GApH5RDuRk5vO2J3utoXNAJmr5pAQZmD7bSRM9XCB9mKSUijTLQcd4jyBP4gA+UDML8gqfEjrLl2w8vy1fx8huBinzUw43zFZhhij4VVR/B+M
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: ray-auth
      namespace: weyland
    type: Opaque
