---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: datahub-token
  namespace: weyland
spec:
  encryptedData:
    token: AgBpm+gzZJT+yKtlfyqOkIJO6SsNKrfuaK84cAaiDPn/v0QHf8ndQox567KfvMNZ54pYx3DVESSWwYotGHOaOD2ECw20U5fDMIykgIoKuntiTpyV5uODAzpuyNf4snVShGAlWZ90vANSVMZSJroAfqcgmowRPEH7oL2rQQ9e+tIDctRbr1X3OJtLhPjCacTZoMwKG/Y6PZ06s3EYYnyncTbEze3f1+1riJa8rXSntpAeP+4qbZLHWIAvZ/Ls6+FDa09075krYsO48oC5l11BNzMRxgpSK1pI98EXjtII7Zh6JeZSwcSm5K56WjtaXw+/PO6PM2mVRs5Ms+tijJKXl08OJse+tYhQAzfumBHcpuxeh9Uw8faqEB20UORMfBuMLZPlpT5Nl29X2CHV0U+Wvs+9c4vAnI9BQNPjljcKrXjgWavkC5stNomqc+SGd6UZ8k5eyQXbZr7VTQy0sByqrHH5yrM+STbGkACMRZYt5jdEP2+WXWtYvQjV4rhe53Y3M9IG8UrLBFBlu/KEVbVW9CoT2/aYp6EhH6wJMDwbsX8Zesczif+pFkAnPTbsFOYC3jHg3LzsarI1W6I0QeLhAwgBUhSKpedkSq+vUKebHCwaqF/fSDLt4EklHUGUxZNszfpJX41FFKMfd1IYbFMLUSNAEE5kgVfIAUgS1JIe+LUWsGZx+h9lhK1t3/Pd4RSCngjoomUrIVr6T4bH/dg7FFs99nqczCayw5/wiaGAHmUNOPikLksBB30FiUrLrqdeqcyNK4HFcyixI4bserMFUdHhiAZQMygyrTOsV1etaFFXn8Wzbv1D1+6qub8dRjS/160DGRyUzVfZWiKPQh7os0T2AeuD2+Rmgd4S7zJSmdfDYrg/sB40vQglJzAr2D2ra8HzKj6TnzkHmX+HP+d0DKiYqJkwz8ITOTSbCOxBfc7JzAfKw0Jq/X3ibK56ZD0RkaqFMt1uf9vHCyaNBuUKRXncbfZKke+tQoD+MCIn3FsgJU+kJJkPHfsCZ3ufxvOhgc2jsoACU12cXevS9pnfrRD2djwLrSjELKPCHdR18lg/3VY/HdS3LyPv7wk3IsYdbzvO
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: datahub-token
      namespace: weyland
    type: Opaque
