---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sonarqube-secret
  namespace: weyland
spec:
  encryptedData:
    SONAR_JDBC_PASSWORD: AgCUFXz1VolladbC3VYGqfxuQneZKRCXFhcmhP2ID6jJG4EvFnofXLIs+TegnzL+OTqdYtQnBytTBQZIn8IUhz+ijwSSb7jHjzg9bLGX9H8lkNi0jp07Q5DZ1aBEJyeHBmqzYjxgEnSYxJfoLFi86jVgv4++wXI8Z1JQHMcYfntfxD339qK27qVv/MWe5qKEvDXcDZshpnBBr4tKq1xqtp1Oiuy60mhKh6ezzvAVNhRvWEQkoqFXJ45hOBqcdHSe+ROawPI0N/q8JmbJTemqSk8QdQ41XDIehumDUjRUmTXE91Xtdm86Xm/BbjxavA6Z1bPRb771O5fVnj9N0oBzCYnZ8HsmWlH02UhZpIvu/QdqihjlIkbhoPJ+Gpqg30iNrBPyJvLprNyjfBWMebaKMr5OcgpD6fktYQVDXdSX3mUaBX7zU0a1a8q2tIZaRofeU1tpwnIqC0VVpDQnJrEX1eL9suaC8y7C6MeFlFFq/PX2rLTI5hfn8htDuHB495/ld5ZVPvSGrgJoWzzt1wHnRbiX+bKywPMF3pp0nb9wQgwmrX5qbdIFzMfPkOXK7GVMjJdoCJDTXxftzYzFq/CZtKTa9DAzw2y4jAvLPf38SQfXd0irtD8p+IugCZxm+YeOUF57qFChrEmDDsR8BkpUlpV4dVjj1WS6umZ0ZqTaMKMxIx1szeXafEXdFnRWqtPMu+yefzmyG5k7+qo0EipLmo8DR194hw==
    SONAR_JDBC_USERNAME: AgAEA/DXPGLJS1A4pXI9q0C4MQQ6bs2FousXU3jBEdR2AZRT10f1A6dG/hOMtpe3NGBHCmIm40rSZKspaTpgbbhu2dS6cNqjq0LTJhphd+ddbeJsquBTmPbq1xLvoWHCkPkyRpTeXq41BrQIQg3dveSvWwKvCieejM66densqpOE38FWf0ykyK6L52zfOjS59JW0ySfa00SosOsGXgzyPsHYyp+rwTRNfMIJiW3yYX5J3z1eaf/Xw+beNUf8AZmRbBSGOa0NA00jIda3F8VTS3e7j72EFC+wPLwqC5r/p6qPCPf+lMm6XRYGFlDUUdU3jCUahUoMVJAGMTNEBuL2ISnJ/tqzfg7ZOYBbTrGMKjXxQqnOmmgBtaSpLupG48MbhlyqqKyd/b2qR58DDu1PIw0ToKGUOsOpRg9C2+cElQ9sxwUUfE2hHNS4XC7B+WE6GrlQDZ5XcA19ib1wJ47MSXjyqn+UY4SylG+qv6tP6R0qtJLaSOXHrt5TXGGki/gRDPOxtvyce8mUQ2XALhNtqWy4h+KlLc3IuPsUnXSMt+8SNLJW1B3P0RkzlYZ1tw6+rij1wvg7zPsRZRYPDgfvXEZSiy7TJal93SthjDcq5yWsLRBTRMCThI+nUZwN4WsCzaSHSP8oN8EN6d8/Y6WzItBbQW8gCegWcIfZ2c7mEAx2bXtUftAF47rr8fR2441wzfZLRuIs6dzUrVM=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: sonarqube-secret
      namespace: weyland
    type: Opaque
