---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: traefik-forward-auth-secret
  namespace: weyland
spec:
  encryptedData:
    client-secret: AgCeUIzFpVlLlkXs8ETlf+LeMkp4+IpcEq31yEKYVudp1Udj8q6cg+ncWXpxgfsruwSlKtyH9qcX653bNzkyLIVLKZaZE7aoAUy13T2InBu5awe8s5HdXn6h/MZblag+IAPVMC0YIpAS78/lqSQrmk9Ir78mpuDUTmqDz4knyt2l1ZV1YbBKyZ0A2brdVbivcdekn779spGCTtbJkF5W5Nfw2YFczFa7faFtgaPkovA313xv3vNR1mu+wFgn1Xo8xs/+0sdQpamjmvf4PZicvmmkXsAVIB12C0GU1ONYRAuSdKb1vPINQzKWu5ueUl8XS74dUQdwSjn/+YY3T9hPR7+u6aaKQyQ8YVo1SDyVo+vmXcoCJgUXZwiCgRkBxGW9iBXwT0SiXGlRRffdhk/UzNeuQSBNnBuvfoVxFoE3LEzBxQvdzOYCe4s1v1N3aNrg/tLGnLQUc97DlV2rTB46Qyabrx4SaZ3npAIu5CIdapq2OEcmfu9tyO5qsijncjxDyh+JGWImb0vcqGNVRHtEL8MlPMmod4QoBe8mDRay8tDwzazgS8JoOmkUGgbkoBu1H9+wtVRL7XUM9rtU+jDb57zBy5KAzzMLfn6Y3FSvFGsNNEzZMYgmeNb1WhbthDLowfOdN9TesLQPVP9o24uGNUQPSJxhDbqGTFdUqOzHU1MuSUsvM1/2IXzRaEejjSd4WCMGDM0Yb4Tr1ifSxvKL7lUYu+BzyqgrS+2M9IrJaDLPtA==
    cookie-secret: AgBWe5ukCpemZEWuFNgfLQqHX0SIORMotr+iG/EBAdtaI5eevYIKvkheSyY9m/YclpodImczSrDCJ7o2G0Z1D0D5Af4JbVB8M3ShOaESsEZoN7pSntG/GUcsqksLzpKkuhwXE8F3rk90V1SmJdklBT6Xmwmko3IzaR6SMFUR2SeVNDjk/p5aVUlin90HGA8LkXNmzVY8nRHLB0kTgarnIbpzibrc8aRndBws01sM3S5ZrEWMb73sGpeQrNc4r6xbS0TcFadVn/7AbtBJbJyqInMXOOBCBv8Cl8R8RqFsxhLK55rc4DCyLU/ujZbbVWwqTZyIfaLCCqJZprU18XoBp0Yh4hcp1Q016agFEe8Cy8QMgtZuxj8YrIYvl9aNfWjqb9i+d7jL2HFcI/ucNDKHPFxwFyzPSxRlyIYPgZ9tDkrIpwyebWV24Blfa2nK8VWUCunuthlZf268cLil0egMFpyvPMSp+IUMX4tvGsITHL4jltV+bk8UNNcv0mwMwRxe+Q3aZ/6ZJdRfkM+Pp6yQv2qnrp38kA3dNvzRRv6QgbGPY7G49G7SyIWNzCnodABwrycB83z5AgDRfvZQEQRm+CPmv58VkZjpH/WGtSoNNsNVRbbZ7Hkhg6Tkz8K48+4AuVYKY46pQCDylGhOJ2x3ZvI6oSRLXck3bGNgVzuyoNKD1F2XRh6a+G0TIPBGsfGqPpxynmmVuN9WuZ93OwLS57CNU/vaQybNeoNsw+ipgxkc5fsnKD7zc9lx5UJ9tCazGb9kz0IdgcyinRcZiUV1hbNw
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: traefik-forward-auth-secret
      namespace: weyland
    type: Opaque
