---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: port-creds
  namespace: weyland
spec:
  encryptedData:
    PORT_CLIENT_ID: AgAe2IbeOP7aux9+J4qW8otafmMXJV8AUn939oCs/ggusyaM21vQAFcwexdqLf3G5s/9PDTsNpYz8XDPuMCohPl63M+RVakr2Tew5l4Jul68XPpMntTVmYEQo3Z2Yo98x5xc0xPL7ss2Xkc2QfYCFMj/AubcXMJbjt+9b4qc+N6Jo6HGUv35JQ3qliL5zkPGf/NwHQEWbsIqNzc+ljKT5rnnzOUuGOp4haYm+0dalQ+UgCHoopi8cFYEZCpjvrFw+rWwRu9papubHMdtWn1Q2aBgBTH8rA7xrBwOQZlCv0ZO1wcJ+QCwBIAZSgZq08SxUanJLJ6XChA9aMjc18Z9RxewCNkXV1eBFiy5jLczbVErZJ7JpHlTjgawVJO6cErhMymXBfC8rwpfMC0Yw3nywLmbCvR/ujDmkxOol8hnazXo7mnQlmjndyvLcu0ZNPqkO3rGrz7x4bmrw2CvvtPzSSunlxMTT4majdVKFZ36NtJoaSUSu7arWr5tKufoqIVvuAZRg4jJaO4PnSh4quexW02a0h17aYtMxio00NEcBH2FEQvtRfinCm9goNf2usCW408BOa91QIpHGE8wg3WS/vvPkpDGF5xDJ/mDdbdoY7uucYRodLZDlaHVGHwRSRQeWjgq5Nxl2hf2ZnQr7RXj9owJsDAncqX4IOEjND9t6N1ovDY7OKjYaB5pbjVHd3ZmEIzB2K1CrI8SQ1165vAYhPMQMCnzGQq8JsPlYwWcFLjeAA==
    PORT_CLIENT_SECRET: AgAGElfh7JXhx+hzsa5goTyT5dUIfiOA5nuc+pyNSdzkI3ginfMiBKHzbQd8KO2vmWZAUUNY8Ajfce038sF8sy4O/8eb6zTPAazruroLZ4PyQMRVhP1/gDsf8ym7/T0WM+g4O5OTTeZRZ9srz6OKlfBovz0zaV1XfQosn7bKYqbWHNJNlAlH6rhhLc1+UDmMqkolEyX5QQ2j6dANmzfCXjKMG09uCbZOWaKOrUM49LKtb6x1f5j+60T7K66eAfXDjwYlZRBjgXJXD1HQXOZq+xnMwkvr3fgNPPWS9yZSaG2hTuyjYuvHueIt52Abj545K6+j3HOFJcxXp6iAUGwftNjB+kh3yc8SasNwcbRHVp97PyhRpuIbcv4K6cDeRSLR+4WxQdJFCvSydSb+ugXqls9scVc6tIKyb/O+UCWLbDBPLPfcBdrXzOcglmHMyXm+WvJvtJVrIQwXogMd3Wu/Lcc6MWtW9oAccTQ0gB46NeZAKrABF+iTW6gwqnFCKDMC2r0alGqX7mpi2fIuQ9goto+c4YfJpz7IXj3K1Pg9nOT3KBj1hZIr8Wtr9MI1yvI1OwhQxygjSRYzkRl8ItOFJ8hIgmOxJiREPUqyR64Q5VernuMleM1pomNiUzpoqmUKDusnvRV7GygUhJs8UZ00EL/rOpNjTVm3BPZNlawEdSTFJd6o8NA3bc4+SAZs0VCj8OIOpcWhPTnQGeVG164md9FFnsyEvJi6vwUpMLTLNOa+q2y9TIY262ma9te2x3tKIt5As6khEYxz9CVITCVZPlg3
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: port-creds
      namespace: weyland
    type: Opaque
