---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: iceberg-s3-secret
  namespace: weyland
spec:
  encryptedData:
    access_key: AgCYzpMxwEem+lM17RwaRFU327KKkgg8s6lJk7Z128PK43qiGkhIZ5YV9y+cHeXM5LF+CqgPCYvaqC/9Ngu8Pd9Uq4Pe5oqYvBXA5vspqaY0eCc3cjUvkyTgjYtpjSpeYK8KdMrSosTlqknm5TVX8MmYhs98tAQ9b+Zc0PmUvmMWy6DNhfRg8B+n15t/rRuZIHn+2cYJAlnSSmNTKQfclDX8X0chIwCJ+xAzoycpNcE+LRQ2rCYXueOSlrVZ2+S3fc1Hos5AqgKg8Zcky3r0asXkvszNRHT7zbZKOGh1afEyBUGeQ3flc0JMeW2aj/ero7vESo/DaCvBucJQPBTb7gkxStUcOfuJAgAmjBE06hHH4LerCdreWVDFHK/otki6m1Rnj67ehkLbfa92OvIPff8vjPSeepp6EgxWSEH5OOOaLHatfyIcEFhV3xYisxiDGmsxSoZQbwk21EwbHEEjIVwIs484epWyIGb9K945ODWWAApOYy3qwwX1JR4jhMSKslNrhKP0fv1x9CCW1/oZAiHcPKPLkBGU20TA7redtEXcGgO0VSnjAgsDi5RVzBG9Uou3I+2WDzyGYDn5F8cyMg7iEcS6msfVfjfChbyeMQslU/suIaFZeeS79rdWwl/9CrQwexNDXUI+7SMi/BsX9xiX+6l2eC9FUa3qH3ElUPVmVjgZyruyiXJmqbHuAXG9hhaAQPvH6w==
    secret_key: AgAYPVl3p2t8k25PlpSBoQegqvCklMBI9cWvkPN60Avi2TAQC8i/Ip/520uFv4otNUAdAWNjWrEB+c2w3Cw+Zf8gp3pY9G5zj0pvs9prCRGd00HqWzYY9d4w1DewMus2Lzzgzd8X/Va4qEFEah7g0VOF0dtQu0ibDDNJw5zaDEacQPCy6lVm21k0GERKg78/J5tuUK5WEjVIGtiHMTojR4Yw2bpy6dSm0Q2/sq7/4542XsfxZzdXrb+A5ij5YsPKXeLxFyVgCfdzDUzzfEeNsT835ygWLW1t4I7gluTva+AJjhzPVjAe21QhrnUDbEbxkWjYXaI8gCYe1aRdW2XheOlUysid03+DfVLbsfyqBmK0K8OXQHBVBS7aOTvxIaihc11ApRecEfzDdBedJEutdQ6A5bB+GFXVmOI6ypSD9yZk6UbDUHAdwwHm5kvgYGHACK1fbq7roiBDIbq0sy3eUuuSnvY1XxWXKHp5Xl/t2K+aUxV05evdXP9kAuqjB3V4ZLHhnktI+pNcYa75zYNZ30Ksr49l6wufhk/SRNwTwIdn+k5rDeuICpEB1iHg+nSnbl3IAB7wBo3qsB4MLYHfKrJiACEar2+ZcdfN8vzG7LSBP+uv+uWGaBWW17oZjhZLzRfayXNnLAsOymHas1iAjZV1RQebX93Wg17vS2tpiZehV8Ct6/OOdBBOI0yA60t4cC/s0fiDPiysWUME2AKkNTuBwwl22g==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: iceberg-s3-secret
      namespace: weyland
    type: Opaque
