---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sonarqube-scan-token
  namespace: weyland
spec:
  encryptedData:
    SONAR_TOKEN: AgCVS7ucT4/uok4FtPO7XCjJBJn9+g58y16nNWvR2M/FFHuwlLFOSfI36p4BueJXRwXl28lYgOwBZ3TNAtB3D+Wzjd6cRpgSOlblPS3ImNGAqm/D/dCLNjdluvtKrwGd9kGjHi4tcKu9RKLHChE3NraffPu958d52KMdlQEi4Pd43Z2G2L7iVMKp5D4LleyrYYjzJDvXWfKFDiCx9uegTN39CnvT4aMpNmyEoU939dxBr7RWr3Q+bMge7Qx1MC/+sFxUa/ZpyjHrxoKrfsh1dllftd5Cm2GntKuwljMUNih5O5uXIEwLZFvjqg0Mjj7ITwmaBGYvIAOFTfnS+2VtfR81NubbiXqYpn1O//uCZGbX8OsV1Rn3GTmczGMPf037C/ZAASaWNCJoi1OoIi0jv02mo8LojNLki1TiCsBYIoxRUdrGNR3jXFpp30Jl+xDZuTwfI2vf7cE6gbDB2CyXJUeJUyUnbubgLGZpJSdwChID5gzapt8snuJUYQSPY8U7RPoO3jo3J5sOeGOuW2jqHiU5556X0fdGOcBXb5z5iha2i89o+eSK3u1ZzzsDJWvBKGQVgCVTrR6B8uKIIOjWy5BtMi9s+ae0XhJQQj2+hXjOhbJdaW2TJ8nJ+Nl0Im7Z12sWzk9IsB6JHBkMtrRjT6gQI2cmr4yFUWi7U/EMp4kHk5/VxZk9RIB28LOCR+xJ9eo89n6CbmAwGE1c5FrIr22nrIHWhToE0ae35ZNfUIJTN8nYtGPeTIXo/4GfiQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: sonarqube-scan-token
      namespace: weyland
    type: Opaque
