---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: neo4j-secret
  namespace: weyland
spec:
  encryptedData:
    auth: AgB0CK9Hr9S8y+B/N5UEGkR1V3PwkfRTvTMwggNXc8xH74zR1UGzIOqpAsk9tOkRfGXgAJwj540yFKY0FNS2YgzvR2BZMSFCeoaQiDQsEhNjfm9b0F3MtlTjFDpDxLIO9Rzs61fTCyVbz42JKbwp/QGzDaUAwFZbk0E8SFLm/UWYZarbDuIbDF8YkOJTpT2sGcC2RaLZRntz+xibuNQLTy3CFZa7vhjF0CuTot4iT/1sY28SCwH7Xj2wU7bi70KwKf2PQhkeq4FHy676Zpf5zr6uF8Ikx4esVzkkiQOnL8qHXOKxVrmPIxLauVU99WP2y5+xPfBshf+Md6TBYJlyXEPLku/wD7jfbMaBUaR7oBgAuECF7EkOt1TeGBMyyE/WpYx8mBledvymGFLU47Hw1eZU8/9IQp+msEGx/I9Hhe4shLR0am20dTeRWTtvwG9TRUrOW8upv4hizAxxvbaQ78TlJ+jTcD34Ba0lmpEWBObM66togaWSdBNwES83cj0rJF3it6As6Rp5PBn0O8aQQADclIa4JEbWgqO+FbSqMnGDflFCETpvUGt4s5K9RSUC3QDpuPEmOz4rTnhys6bvtazJwc15vzBcU0JIeLFON0FZhRs+AWFY4s2laloT3xBnjyR69hNeZeJ3o+lu7lGl9LOBT5mwTlb8tlsCLQCLUt1NWSh15/+SoA1OGRC+4abApA9fOMkh4kDZUl7hjxg5I0nEv3Df5aOmgYElzg==
    password: AgB5TcNey7bwl+eTOzJ9ltyMR5KuhSRy8uVio2DtFq+qGVumMfaPjfuuJYN8t+I5gs4TDIE14Pls23tJWXOaUwFTkFRXBtd2k2Ut7fLXQIm50zg9Yaqr5f5sDnf7FkE6MqMYtSD4y68qQqzw9rHjL+ayk0nmf9gKShOXRdZrn1skr7nsa6Pd29Olf4kf3P6lHYZV0m119O4MimHabQImXHH6vzOdkD6K4IFR2890pc4E10im0KtdN8lz52SJH+kthzHN0Igz8M1hKGtbplfIG5jERZNp0due3e7xGu2gLjz71WkfFxtoo5KQ70CAv3v1UapccAsb03MSO3odBAty+boQTxrw7FF7QayoRbx82Uua1wu9pGOdB42JzEa+vDou+AvuRSrbKPz3L8MSt0NToYkyTonRjrZznmO5ypBjmVp2kj12DNx75kNKX6+k77b9YCJsWaJZF0pFRCQscHMdXFkvge47oxvCEVJ79G1Re86vAGDvBhfyNqFYqYsoNEL1mI4wFMSxCvsIYk2IxssXiVAu9fWrBTSzP4E8Lfll2AJuDCgBqerxakpBLxphackCaVfziNWYGBqOGZBNAxb7g4gh3+Cr0nZzs3UztPsUlO8bnMVM6eAJdctGaQJTKmyDGfAm3tWdH4U1P4DnrsJKDcSp1ijChISNNrVwefkp+qFKujjyU7M/B6iuV5dUelVbWWFJg6je37b99xmTOCJlvgDXRvNyWA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: neo4j-secret
      namespace: weyland
    type: Opaque
