---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mlflow-secret
  namespace: weyland
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgBXWJV0qce6xhGpyedIKQcoc2S88/FxQVWNzjStCYWT1sncwUphJ7mJnaBQ8o/bV7Y5n7Ktnu2VFQMx75uqyhMxxvVRqPwwK+xZkpGrYAIIhP797dDNFwKDLqukLTYIhYGk3vTb/69PqxkRiRKZJnlnaWisi0wBirs0An9djpd51HfKPdY1GCsmqCH6pNrfy/TBrdf2JdXidPSscsO5RjWlvphDJhGQsvLPT3F6a2fK7TL/p8TV6qo0sagjFE5DZfqoLc1TrnYU9Oa6AxAhP7N2ObNz3/V+DberZwyhvgltx+idOqqhzzuxkzq0UXTxpXjZ0A7oa5M+QEjV9k/aiYUQfcRErhVEQbiI/YLs10C+gbzMwzYB+8YVhQunWwQRn/jH9B5PnMsrA675KqffkJWP9qypJG0gOGhqo+AFRaZBxUCX9AFHclghAXhXaQ82w5Jycp35QXI/rjCAdDvb9xrY504Mobt2hTjbSEUZ1RZBZMHQS06eEbisI7ou97LZ/LlsClv5T2dBIEGbCgb6HhyoZU4Dw34TWwRdGVUgi/bayoA8/U19yVEHjUuoXtTjax2MO741k8GHjvoYmFOShorRYGx8yyUDO9VgS76QitD1VbBNOCdRbSi5iLgx1CMOedj9FbigN4VxrikSLMPvvn2rRRiAeRaw33Ug6AyOAXZNPKvpT4pj5E62ys3ff8AFgcd3IRtKZ/8jkKvhqQs5HLmIzO/8Rw==
    POSTGRES_USER: AgAVe1iYfxbhJToT36fRsRy5+DLBUZuQ94R8YQ7+HjVhoyu4kevIktcyQotM1nbTS29MWW/UapA506ftRM5d94ypdSg2x0yuIubqKqw2phbTpnwtClCtOufHIXOpavfKzO1to4fmsX9zCJE374hh9RyD9NJsqXv8owVojrOyS6roikxPZxTTHFPWZ/yZlwPnB9evsuUfSx9+yABrL8upWZ7t1zug2cof8lxk58Urr1GQfK5i/Y1HfMxRLQq/F383Dcil37dghF/5pkinzlUCTv1ptchRvhBqlj7dyetteFDH9ZPl7HaGeX86xgqEfqqeGpWXjXKTMcLRvCsrbGo9YiFeAoWl+YYSqDXamA7coQq6pjEOT4c44PYp3Qj5WWHKnLGOlrlmPnj1tOzANRavW3fuQh3FM+2dOrK/J8OLBkINtv2KiKoEiIHTjU+fypev4j1W7zU/IXTFqzsbrC52nrDBPC44vXaBoWSosvwBhEJe608WpsTT+mII4LW2abIybf8SciMagXr8OQ3YwUAQfN+Vr7f7CwxyPSKvr1mZftldKiMnZLYuAu7epbNBhq6TXMlvDKoY4B2EfTTXIuELIbnRbMR2P0v6jZsyqid4HR+EBgJzC+5GXaW4yoVfN2njn4fTSEKUvrDDFnedJarKx2AloYWVeaIdBuBDlwru2hPEF0uvBmVytAvohwHQElF0ZjY3IzJKiYc=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: mlflow-secret
      namespace: weyland
    type: Opaque
