---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: glitchtip-secret
  namespace: weyland
spec:
  encryptedData:
    DATABASE_URL: AgB0Spn3UYlDfMNDISz2d3K4Bp8W8BIMrX7AhdoIJ21MvpJd/OW2tgcE1MUyZX+45k1W9PqFG/p6Xx6a8TxP79tXY+g+WxmVj4f64mF3BLe8Fph0uVYZSW9PW7KxcKwHnRsYmlvoRz9iBBaRevTN0fPnVULyzMV37q7vvsUtHEs+qSkdIoQg6XJeUkRWTsJKe/powsZM8x0FavDbzZcozo8Sr9G8eU6Ycaoq2j+ge5HA61yMnzIYl2hPvH1cXkqyW2KKslb05lxeuWosDDCn7ToqWHn4a2wioHNWqpsujGXJ1W7KAOr0csE6/zAI2c0eDnGuJ4g0b3JG7giOrb4DS4BQK/eqj8JPLIMYPSDHF4I/ZWF+KR+CT2UlV47ktI8H9OfppZu+7dKh2H9jgwxf7uqnRXSSv+j0uqZ1O6SrqYctGxHk9W0dmEAVUnQ8q9BoIFKZdOogxsHhivK8GiiesQIMNzJSJ8XBvC74rRJa+N2fgmJ8TbW9qLGoy8+2xwgjXb1rIESTisOyvN199QLuS9TUl5Cl0IJUT+7+7Iffru0NYs0FJZaMTr53TW574vhpde548g4jM0qltFYyDf6awmmBD2NUGxQlXjkQ04OvGdkU1wm53Byb557NBzc76+yl1jfnsz5cO04/pPGPGmIQLhKKfnl/N18Z7lH7HvYBR5Zwbhj9ZIY8uBQSrCYNXcb3gQbcbXE1OX3bvwLUAAHywYPAVZ4fwhuJjqAdFv0pNH40SzaxFVHye/CSqu6cdMhhh/V6rVBKVWdQXNMR9jfArRAdCONl2UbDARPhP314EkqaEyXWuqT3FLrEkTa/CKvgcQne64c=
    SECRET_KEY: AgB3GSlwpeIy1H9lYx41RS+Og6YSfSS5GEm8oitcRkIbW+BUXAiG0dsMZZj01m0R5hbZeYlVU7/lHc7nXWSr1D6efHU+KtMajLLgM4QWEcnQe5i74FlvS8G6EhVjDWASwLO48vKZvZpx10UnbXMjwdrf6SgtHVotFYZAKLzwM6AfQeQ1z+sm5eMDx75qfvBf6+3l2+MoMI73kh3kn47BVQSgA0AxhjxDGjwrFxqWiJQlW1ixr3cDAVkbcj1qP9Mb4LvjYwRhqqapee4//5j7qlNEPwWq7hpmITlcmqGB5KWvHmsvsNMGeXGqJtt6hamlUgfLcQbEOtLdA/7pe2pAaLQnWhT1c/12qB6RuKd4km5v87janXl0Gk2PUO9aZJm7FqpK1JX5OP0lsmzzuRyVZI+ruWd2beyuJ9rosVKDNme7FMrsHgdVaUl/rcuVFc/gwQriIM1NQhW9CMkowJyYJjCEzlusV/GE6ItuQthkCzcgQu8rJIgAFn6Vx2ktJRcALBtNJTNeatibq427t1kYpZw0jx3arz0pdw8wBR5L8UK0rFBPnr82ZEyXaTYniH0xfcjInkH/WSkEyaYdGGpNqH//zZYVblylItDaSz5abXbNCz7T6hDwk5KOViF9LBgj6WMato/FCRd52nj1BcBJRjgeGzKuAtCPS8SswufvcerybAe7vi/eyl1F4N5qmAhFwMq1/TW9RAkfZ0z1gIAxL/Zw1qU62wpEzCA3YWKs5uDjxtg9cXf6QdEZIpgcbz5ooqEAw4lFrOy/oY4ODK8lwVy0
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: glitchtip-secret
      namespace: weyland
    type: Opaque
