---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pr-lifecycle-reconcile-github
  namespace: weyland
spec:
  encryptedData:
    token: AgC+oTUd85uDkv2LoebSqENxRt/JMfDo7lBT0cHJjJQmGOAkymXCJv4pctvdqqlgQO6CnYVtBhpLyVKaYvrLUBsK5jh2wij9mWAPk5wxy7ylcbHkjwQ/NOHLbUQa5qLpnR5oBeDZ7yBLheeXx9yijCbgiw06Je1j+uFMH8J9+EoFaOz8NVdXVcYemt7XNw8EgWMHo1mNgnnUGNMiywiaUPcsW0bxdyAAAs+A7Cyro6+17ONTBlHrSQEZ7+JUbdStlCeRjsdZEYqOAItHqx8UKK2IAOdZM3zIm7By5DTAoFWl09G3WDr9bac6P22KkWzxmbSNtaf5A/8Z3Q5jvjLtT6hYD8xlj64pPwTiHJW5OoV2Uf2eD8+i7cDvyGYOXqIF5LoiS3tOTG8oal7310oGFPkNdbcistOcnEl4KMD0megGQbubTqfQeXfG+S4V9RvGRYKWXAP3N0pPdBe4YJPsj6U3UvWjWlTa2RjG6oz/FcEW6EIAx1aOE/JTTmTaMA4Z3XL5vSHZKrtkg/iR18YhFbwK+QfC9VdZMurRwpKigmzylEq0N7+XI2amKRmkMt3OgJb0c5BjndBpbc54UvNOYuYqVjO5im+L6AJcfOnuT6G9+WhOT0UjoGsQPoT85yF4YIfiU4ViAjTQt1KTVZzXeH2QO/8Dk/P+k/SdzFyMAHFdestNi7aNu1eGRVPdQrGvbRxXfV/YEsd4LXMae5sJpxs1XlFyDbRS/ZcGgL3LCwvtbe6XafaJ2bso
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: pr-lifecycle-reconcile-github
      namespace: weyland
    type: Opaque
