---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: traefik-forward-auth-secret
  namespace: weyland
spec:
  encryptedData:
    client-secret: AgAocSRGpUclA+apsHiZzwu7od703yo6hLL7v+h65ZlOWyU8FFIyvjX7JZ1/xiC2y9R4F3/CiU8EDnDzViQLpTZww9rMeNz0abEUEMciW1W8+6xGOJLv1wIzkqpPbbL5QX/Y8kkDhvzYqc/CKltsuelaSy3UZDcSaXHtpej9XJEAJtztaahvPFN6TD7YZv0uBpN9vdmYKQmRAEajYzHLCGy2Faa8wcD/f/DIO7FfZ/e5qlf2SxJeKsPaj4ESGt1s5izcraaqRlFsUsTx2gORzepYAbW6COgcYs5mtRqdJQCpEracbVXoXBwVWO78/Fk0TsQTu0k1/QPgeMsHRAHnEK0NTy21S/8FH9hjBnxGrXbrvfes2MyPTI/Pnm6yfyEkuxc1LFPu/7qPcsLcG8lp2xOjAE/z6eAIITdXtj960nB33TqYysxSV1H+pPoDSx9KglX6FZG+ouWNmSQrMfKRayxDYvnsqYWvA92o9XRPJLNOQa+ca8UVm+4PzBqyHA9pnKSQ6mvAQhrHAaS0EGbqoiMHESukiWpTexWtfcv8qo56czzwlF4gysChChd60EQeiCpeGO1HPG5Md7yAi0SKPm44RZKEQym8QjjWU+4qaHptrSPvkRbeuRiGrq8yhdn/lPYU/Zi2oeuxuYv75VK2lVqBWcJSI2CldMcgMRA3dg1ZZtPRpkQXlObbYVBX2mE+CPhfAMAQPs13tp/Ithhiue2a1IgXYx+ko0Mv2KqPTUK0Aw==
    cookie-secret: AgBf9ODMivIAK+8TRnRC7ekHpAvCRwVkLEUNVPrIyW9wtmv3VCERHz++6nP6cR9+f5lw4YSZMAWBKG6OWi46Z7nwMlstDa53Co2qWbdEIB3wE0OUrNhmCs5/rSKzvpQW6Nz1YrSKnG9d81t0CCOfPQUa+0fWhPuXx/aPQUiDlwZdVrMWL7yoNs9fAFHSk4EheBlPA4+SckILT5DnxZtRSx55uelOVhUcuGT9Nh8bihmVkOok7oGnj5Lp35jtRNj13wUzCYmt4MW9Cni3usjV13uVH+VqNVzyV5dGliOAwKmW68nB1WwH++KUqQiq6fhglvN9W9Kin8qGuGXcIGa93RjAmCOxji4bjpnV1ns/LDkBQA3AUv1Jyhb3xL1uy1AjLDA7otfxRNyOUELPVRPWdNQMUT/Yfh+sIcwC3WRnJM7k+/3LVNcJv97aR4H2nkb2V97M/qazCDMRwWjy9ILDIklWj4w4T/e5NvWFgYKIVo77BOlF4JXoqLwvtgG0TlYPy/JeHa8qsxB3H3m72olGgLwBxAeekoQxYoMWHwOvmZS+TDRKkgX5QgSyEhEStUVnVRVMlGHOaj+HLfvXXWr3SsTVWViGUVEvSnF9D2yY9M3peUzvGuJgIfe+eaqbYljrQb/YZNawCvhfdhWFO3K8EI/bDWE9/nKHCc9vFNK1DRHsBu7FPUMPRsGe/0m7ql0AHzXnTXkdFckoh3VsSG1dJ1BeDDmO5HH6DtI74Cg4lswNRGrzfibHCApjezRftaBZLSx4OKcPckYFuyZfvliH6A/o
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: traefik-forward-auth-secret
      namespace: weyland
    type: Opaque
