---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: glitchtip-secret
  namespace: weyland
spec:
  encryptedData:
    DATABASE_URL: AgA80uY5YgjoZ4bkJ/U0W7sCGtGyi39pnCeW/zJ3ea98n5zjGXKtP3bvgoG1RK1AUR3X5FibKOskx4g/DjCqACIVgjEBVha9QHKbMYSt2QRoydWLlBqP10EVrKkyU1XA+wIk7xrVUi+8RC/OqnAypC/jlX5K4qu+ybjWWK5V5oYfI1vU0Dmz/XWfmdOxapfNTkBwRJld6qI/PrciYtQLS9Fl98NurkZE8Mih+4pjLZIgtwvZkEf65MxzSS0ub90lftILQKOskRH9vrvaZTQEYxnkH7M2OCsCCd+zYj37IbYSBpxbzm88m2Pqs5SJWqVyaGmwQDOwH7T4/cCPuw0KwKU2Douv93MzGbLdtDDbDLaDxUs7Fm5/WiAhFev89xzL0KD5WSdz8riOgcbXSuE/I9L2sGFIBOR6c6G0Tu+MFzxwQcknOlAYpHRCar/PW5g5gwZT1bZm581kD9ZdeQQNKNH7TrKPScQCGUUx8cKOiatQrpkNYaqPgbuzA1FThLKF9pAfQgTMkOmWQMRdTb86km41I1Zw+bFtktT/MpHY0kpG8S9cOOk/f4kEFCL8bmiJPhB8bVeeO2YKD5nGNpFh1WW6vj0ygnCAPMAfcCbulE7FsET8fpT1lPD/qcuS4rCTJPEn4vBxhcq3YuBH5uPAfz+q+y7mKXu5IedjN8N8Mydex46aHs3ltjIvgNGqzz+/w0XlpyElhUvR9BGQHxA78ZKY6f7BI3fD2X15fwTZLA1hsBqbUAaJEcaqPlJf5yCRI2+vNQOB263x1/6k5zVFTc6QT4Mmk70YBAkSFCqvPpbrq02U4DiPATyaM1MzT57ZWIdmasE=
    SECRET_KEY: AgByDd4YfnRnOlQsye4zD/nY0C/UIcxCIbC9ISOSDAtk0prrEEY+jnS+AgRVKXe3JNLwbV5wruMoXcyc0GtJROM/RxaJxjjTrrDZA/oeDPYuhnypfPqVzkcEMlEQ4PirbOEXqydvvIbrTFa7wEfdLJLDcli0SZksRHZEF5EBBGfbJ5JQgjvKrWQ56jTEkK7a0n28gxkhQ2mdQR+fYLAGmX5XeckASKk5UATMIN/ol/IJcX4XlM9l8yXf9HKHARHPUfazPnWKQivWmCb2msUtiX7QtY220PZV//c6j241OXlyGX5HKlBAfqy/kdTmsR5+yu6A1o0uTE23983h23nfdUd6OlSSQExJViV9iqD4XN3rolPxymL3LxAXurJ4P326I43+nJu8WJaRRtLrj5PmRw3U5JSKmFsydxRW6Abq/987uQ47STfiAW8DVuAl/XGpuT5VtySs+SqvqgQTZCBbKm8URox3hrS78DNdv3WYsFFwOXJXj0r9720zcvD+x2rLM6l518hBovoGJQD7AxdCglLfNB6JraH3e9mlefbl0hvZSKrrFJawmUY2xZ/BM2qDZINdMbZgaoAtBxiwMNZD+Y0iu5mGOfS2sGIKbhJJbTgaWVirEGa70YHRToHbDYRYfvEfpDebnwiEA6oHKtY5l7QM6lBbp+4XV4ZzkK94DlkbOdVXaCaavzq1Rt2qfJiCmsJrJTAqsR+oDqxPLSfu57rHuJRYI/vVf/kAulJ7aphoAO740h6u2nYGP53JO0qOil+64zu/sxxoiv6ger5VHtOc
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: glitchtip-secret
      namespace: weyland
    type: Opaque
