---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: apisix-secret
  namespace: weyland
spec:
  encryptedData:
    APISIX_ADMIN_KEY: AgByInlCaRveKOHeX00PyeBPUjBY2E8gGsD5k/sigqLCmMuLwW5HWEaBOb3izAU9advJ9RMibwbaC1+QUcrZZ0vLzA71gjUZqeiHXnlPrlCIZ1Yvg6cI+qww2g+d4F/9ssb92awhmktrjVryPjrHnrv/zfIBKMD6oPrRCKyTCmdL6EIJwycoAy6TIBB6Kdw5L8fsfHBWuFII1lVX47XosBa7hkoHb8dFZaUSdedaoPP1Ij0FyRPPXeKCQrbjq7oKyXGu5xyfPSU4vRvIPz3CxJ3b7ajYYgL2Y5PVdePQVv7153H8Dfpw/fa+VNolmHMWO+57MzyHz8AW2ijDswpXuCfavV0e2nNy9ZQ2U3GlxL8jktIlrk04EATGiU414meqTavqDsxZOx/H0lPnpoi7nyW6ctapJP/hNHEbFgGeLIzxWYmJcu9zfv93dtGdphJV0YfuLlr+mFZsUHPqI3dNRZOglPlkyOCgNyMdrp8SiqsuT6BANpKDRsyDGVIWs80uSTeJLL3CopRsdcDVpZPKnYg+kTkSdBNJFc2QyTCRDXt9Zp841TElAxx50PuZKQtwBeOO2qw4XmU5VnSSeR5pxhaFmIGOCp8oeRpMfKnr03mTiT/qUTtWHbpgbbzh4JmsYXdV3Ae7WFwlDMMJ9r87yPos8l9Vj0/ItYQlYzctiPea7Zc3z+6jA4xcjHVSOkQx3kQU6VfpaqrShaF0zCHaylbzW5TVT21MkuLEkAzjRqmccDgwX6vRqKl9VNFUh41w0rzUpjekWJJ5p1DfHyrZYRmk
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: apisix-secret
      namespace: weyland
    type: Opaque
