---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: iceberg-s3-secret
  namespace: weyland
spec:
  encryptedData:
    access_key: AgA5tAMgN5XxQ+hUcKIh03H5zW/jvPS7WWCnOR4PKohjTeEYKfl0GF3B6QG5Lz5h8swSWWUYEg6yoB9lsW3IBCf85IzN26GI142ZYjadhvFtYRsFPZvayO6ds/uhmeqGZjUi0Wkw5Nfojz7S05zx8hTOxV2jV3G8TzXnnHfQucU3QI/kVQyQziu5oVw7KUie/znc2tmNzU/2LNZnqnx+vR8SlhKFkSaG29bK5uVJU7dgtxZAlPbvYGHUEWGdpfPUnf4ArocO8xCL2huDPh2WJ4LIsbKgD+Ha3dpDl1pW9KY1lIYMUPuSgs/Ch0zMrttR1AJKUBw33vl5AmW8qMeaMtie6tEopUUhiGXsxftR/liSfcBA9wUj9ZRbJZC2/jtGe0tSaLQEzmGf7tlYW7b32Bf8L2N+w+BXr78aS/oQLcOoZ0mOGGIhif1/pXmN3Sp0P8W3k3TExBlx7V7bsiNFuiOCCpnGGfWZnsgn9k/Sx+rMNC9kRwvD4jqOLqd1ej9bsN0EVlm/d3nY3945KEzB/yzBDLSqOhdBpQNs7rYqj4F/Hkt3V61GpyV97Rafsq2qXJU4kup4exI/+Vp9jGLaIcOgOka3YLNlbVCSvQkrZU7DBFowP87yVkjDa6F6pXsijc5MumhOn/MfoSd5txyc9h/ZdiG381R5bjJQ5yT6hxTOYSvQ3CFNusO/W420jJzpWJkcNHnPDw==
    secret_key: AgDTpQGjNrhGxIESLiDYGhnmEfLKyYg9Oe3O8a5roH8rUn6G7V+TOvFhxYr/kOWQlzLqtOoHGyzCy0P8VHJkeELonaJ+yDmIQMEqoinAl3sDdgLVzHK3w0C1NiAE8tB6TzkgKo3yXN7oKDUR3gTtHsMnRgI4HpG62itoHfQc6pOlz4KunRcp9siSNQ3KaSBE7E0nVgOu2dh+DPKuEZuG0fpoBCbNY6DOaPoESUQQpmJEedDXA/fFRSypEm3mIb18TtAIIH+dFmqixqJIqv4sG9xuWrSGYuwngDbIJQovI8v4VfdNZpkeieA9qmQWtE/KzkxENhb3W/gm9MUT+Ll9gcLtK3E40C6aT3dqqd+m7jIzmD2sDihRbdaWLt5fa2XES1epXhqqiHvb1z5l01PdCOwq0qO2sehU64aLThqKVVVNvibk5IfRDMjWYs0hkLc/o8586Fl6TIg4PT5qQLMaNedq5W6q/6clAWb1FQ8KM/tpQi5fK2iJUY19MAaPiMEogU1T1f3hhnwkoeii6m++ci5DfzhD+aXadaeB/00S6wyzuTbbgBBXwP9niKrF7w3v/NQzClu5JG3CRqXQEajoHiS3NIyeeqSOFFpprhkQW7u2gCTHGNnnzfNedRa2UGnGxHKbh0C2Uv/Pi7bWxJaUUk27ipSC+1x1ku4hu5ys1P+Ha27ZLmxkSxF1CbBtb62yIIQZ1piXsajtu6vFqauheS1p9AOqnQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: iceberg-s3-secret
      namespace: weyland
    type: Opaque
