---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dagster-postgres-secret
  namespace: weyland
spec:
  encryptedData:
    password: AgCRNPj5jT/fgRj4r0L7a1zFvyck6yhnxk84ErEQ+kqYn4mZ4luJUW8HLQzntLUacpl2q0V86FZxEnb91LRnuS1w4mil+YUGazBQsdBE9C8qPasrYdqxN61eUmB5cxWrryo5G61QI6pzrAPS1orL1w82+TKMwMQd6/6H98no0mAMJGNI/RPSUNeqfo2G0gzIQd9BFTpVf52kLujxCYHEfpLMfOm7ObVWkQlAhla5Lz/brajLZyG1gU8P6wkbGMa19rEjSi6pPjWPh3jbPP8K7pgrhsxuJp1UO5JVtklkuuWT4G3CNZ/VKb0+SIjRvHULQC2neEb6LrVnzYZQ5y5f2SU5gpC8gD/yoPQzTGrBlQ6t0N57HeMswc8sXuMlctf3sUumv+qXygY41XxWbD2018S8s1KTuhGX05KojWfI3KCVEB14QJKc8u4nW2O77Y8Qi/L2XzyZiroVoH4HVpn7eOfzjJSCcWc0XBEfFDi736nS0Y6xPbeduXsfA2X8q7jp/TG0LOtY3+5am2iVQ+BWRbJOgHbEDALN5tBU/9rtxsLYQXZEoY/QoEW7/6ZLlgmpycIqYtHMvT4oYSjVQMmZvHJB5EI+TAlMwg8KFxd/iuhXZz1QPACdot/hbS5iTu8jTSmLCrro/YV7TXcJozVasJpKqhCvpy9sZxBsXugx8O9icfrjiRWQrGXjzQAo+XgZE6cB2gvg62/+lUw1YLk7HE/DFMQdow==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: dagster-postgres-secret
      namespace: weyland
    type: Opaque
