---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mlflow-secret
  namespace: weyland
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgBvFCzY6vnekHpTpA9GUaU2G1iP3ibPrN49pT+mVQAYUYeatMtBY/wkzI3/cg8kGIjCxnFhzKGRfjcZnj7/wJgxz5SDWXDsp0JdS0HbdvRBQMfivY/6qLH47w1V9wVtY4DBQDhbv4Zi4TbI9CEdQYL6Fz+MhfX4wWrt1Lc1x0/t17El5gTwqbrQvNqjxg4hKY6cP1i7YmLb59YeSjxPVEfVW2afI/VoGgmXZ2X77hIMD3n0iAQGusa2EGr6/lFgc9lujXOdPKQvdpqqxUrbfyWpEfjm17vsfykQS/HlFvVF+/wr6siBbC2Mzg1Fwh/VsnYUqc/mS2VFb3toI2ni8R7swSAHk4F9oXljqSatLZuNKORgJeRQM0H01AmVVNsVX7kadVxv/pmlE6+NN1aU5b4tnBeM4S5r4kNleXHYeN+kxLJYc0jbHDlcAJhJvdEXEg6/3G12xKpItqgmzlbS//LpCQ/fQLVm9JMIWtao34PayoPaOG5uFhrxOWX4yF7aSWhmT3zkn2VGyWA691Y3u+gJJYzL7ng8Z1pKOTmHnVSCyQjbQi1Tx0RpMJtgRah20PJd8q3tjxXJU8xCbkIVS1sRpZLBur/k2GMl/bwIjqK1BKUtgrO/E3a/uXWrrixXFjG7Gbu2rliPJuewWBgck/nQgb8aoAdrbqSkiOJjRIjpaneCBu4N7POPCV5iWZHPV8uApRatx3343z5noIV51v1cCR7hWw==
    POSTGRES_USER: AgAS1eg2SMnNPPwJ3vqWfuOIsSPH+zNhX8fxDkkI/H8MVqwZtjZ1+W6LcLE2yesEF7h7awdiPR/fCnWNFW1cXm9RRX/7IaKY8MlfCCrq9tsgVaPT4MHOtlUNlDq1EJrY6Jd6UoJTgUqfCbMq4goG3CH/ed/J6n+aRK5UFS4hEUW7RarRYmMVOmlrajsvhMwbI67R+CRiKzNUVFdWFaMRIBs9TVVQcspUUyAENX4u98hH1R0zaC8fWbs2LArnT+EHU5Ml3LyQ0BP2xY1PstgzfB57e7iaZzL/STb/aAdH0QFjglHgg+DsmHBmu2+bgtGdLa6kj7nzFW4g6IHE5Hr/SkljDaH7Nzq3iYXPbk3IE2DTW69YYMrsAOFr5WeJX1geykNiIbi33rv9VE9hljvXCcm4ufzaiQcIrqpudMz0HkA0SAIszVk3F/usMuVZJc8oYpyQpJjhvE3Knb04Br42yoJK3k/8gbUB5l8VZIAgm+s0K8vKRJBuBLT8tjsPtXCx8hZwFNkq3scFdSh/c2KBBHmYuF0f2uFAEKhUX6XAxYZ1FHRpOuWT9qYIqWIBB5YFSEApsW16RR2Qh7jXDXNYaAy/5tPw85E7R3coESSrhy6FyJHkNcaNQKPGeWvox5bAHzISBQZ3StYh3w5+y/CK3JbG5K20gxpdap6kIcDGlGTAaqLsPtolhpn8A+x1NFbVPepRbgnS5jU=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: mlflow-secret
      namespace: weyland
    type: Opaque
