---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cron-freshness-woodpecker
  namespace: weyland
spec:
  encryptedData:
    token: AgBVaPC8NuQxEvEpXYyh56ufoBQwswrYPVy7+8BMFMVvzWHzfOQ+ugDT2lVlIOy7jSKlBEUKaeQ7Tl3U6BZo6M6L4d5tfjPa9rq89+DlqtuoOlkAznT8lZyjlkfPYZOaNgfVixfexZzfXRFyI2z2giontqNgUyxnPCmXSthWJO8A96KMoQy1quNItbyJfk1fA+7vwKFACHr/Y4JDWR8C016WELFUxssTvDHU8a9gf+XMwYssqZYqKlp1v5xy13XTzdHtNl98KD1n7Q41rTvSMDGxdqaWbIJyvT4s3+jZI7swlt9/oeuD/1TLxukMjHnOwyoJod59aX00jHFP7qld7YUL/xdEO4tvGXkT2Q2F9VGOoxojtJd9VKixZZT0DjaE9xLwaP+AZbHPXJGW2geXgIGzhrsVz8HrTAtsoMvaSPVYcTrXkK8KAftUFYdb3BAZ9WNc6Yse5uOSKjrhsKcOLnhnX8FyesVw7ICZ69OQP0JhhaxF/7J+0ZDT/MtfPXyDDlCdilpzReVXCItIcN+GaCRqiy0nR5tS4ZwuuXwk4efre7fDYw2P0uL4OKPZnerbSo8cOTBk+spLkdOO5MYikJQe4u2VNxDP2YFmYQtzLJe3F/OCazJNVAW8YVozsFEndneLX+ADHfATSomRVkoEJq2/kpXH8BaD2EZxxuw7xmFiHdsX79Glm4+psesMWr77FqSBJZaGVQ9nOwpBN5mCrXCf4EYRChZCIQAK7fDqsazkuaGjiG6s0fT/FOly7EcwgM6h6a9ZKkIvsf6RO9+0AkassSJTfShiLyCXjW4Va3tFW/oDUSbqe1eMG3dNhbYyeMbNbTQQKN/7m2YTXwMDQsX+E0wYR//5A3g=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: cron-freshness-woodpecker
      namespace: weyland
    type: Opaque
