---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dagster-postgres-secret
  namespace: weyland
spec:
  encryptedData:
    password: AgBbPF3TKDZ8LOwEW64zlYxxxFoj5r40a83WIkRRUavYLaZ9yga6m6hFslZdYwcJvfZoEJsm6w5q8yO9Pe4bzg/wbEWEyqCyNBA1llQjuKSDzGZKsklr4nAlZz9atYFQbWZy8mUcdbEb4BCbxWiY0WlP5OlJKqmJsnLOD4Gk/0EMQnvLkNwlDGULOcyfQ9eJM5ejui/H5pGetv7/NxubQdxv02rSPVPPJiNEklhee85SzS2Eg0iVCDld9J72EUafiEAjBvnTd8m60Am5cMw8U438D50Hdeh+UIxXtk1FPOS84894F1hd59ArMPgzhUv8fVEn9XQ39lJ8ySl2SEtwMF/rT2hMyI91C1pnP+BvNY7Z2bvsA/WF1/kcWlFep9IyMKvSt9u3uYcLFrt4Q0Lquh/Mwa3RSmYARaIfP1YmgSQWqcfYAT/gGGE2hfRWDmxBccEwDpWB/j6R+za5t1Qvmj2w2JcVoH9T1MvxyBIF4pLSmSnYHqFh1hhaC9d5pZ3SgW667pWi460FBfyQkDaNF5KI1TbUro6DiNnpDecGoUnBszdotuXYisUgANVbYUptLOu3YszqixC0ZSCFQCXWMFzaDbO1xHTKgQ93sHIIbAZYh40ymmhfw4M++JxDXYmxpJ5jUGs2mASmIuY7MWs1EqOLSvCtzYZhgVnHLop58v9d/astnxStzjUmrSexFEOKstaDOk4lvnrqGkWtcinthkcx7cshjw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: dagster-postgres-secret
      namespace: weyland
    type: Opaque
