---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: lightdash-api-token
  namespace: weyland
spec:
  encryptedData:
    token: AgB6lsnA7w6hfH3OYrA4eiohsLo991wCZS6YwVmwTvrbhQg8PCrNINKZIuN2a0ELzaWN7Y6aet/TE+BAD6H2OABSK+V6NSvCngqfvpYhqdMZqjhVitTEld7pYZISry47UjTK6t4qEkj8daxhTZzcedW0khDRCwwQ3kUWs3RoLPmiEi3neVgOv2yLL5XbCzf3oEyx5hqRV/JHYSYmvUs6srrV16l89bEm1ToC+uJOeJGGa4UoyaKJ0iMD1y5jj5rfzG/e5Ja4AwDnEumurMxHubI1rntzCsN0n3JOvdnajr447CPauAB+5u2YK//llTPQBJPjRSy1AFnag91vf+9TkPHDGR87eNLcZTO0JlvYiEGn0Pjthsj4pw8c5BGQW+kVtBQxZ6hRv5ARwfSYENeFwbzKOTMrfEnZwgdHFTO2LSBMdodblBQbcFkOBj5RJEgW7dsc0NQVx+0PNRxSY3gbfwaX0AcIOD/A4V4g++qClJekXzopuGp1DbVvdkfgWbZ7ft7xIfUWUMIgywFbKC/ID40oS98dBPKq6v2NMBxh9n9sp3RZFO9InV6olDCSbhwXsT7OGH4BKCzfc1uYftfMI3T578NuaFca1CvpCtm4YE2tJllfw2D3AEaKBbri4VsIVVa2BXkZdU5e/F0RJFeQcqMzB2UuQsn3EzqXA4twa0N/cKUfTmAqzmu3ikpZMawlBirY0tc1t+Q8vHzyyo4s1IlDnRDywtvbNtyzv1vM/leaN0dn89nS9w==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: lightdash-api-token
      namespace: weyland
    type: Opaque
