---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: port-pr-reconcile-creds
  namespace: weyland
spec:
  encryptedData:
    clientId: AgC0GRBuus6hczYhlEwvPsed8884dbj7y+XAxrAUhK60tuL8nnyppKC9ffGY/XZRvJgCvEBCf3QYxQ0vtnmhyRNT/sRL3LP5OtC8V33Dqf1tSwPgkP0Bp9Fs+9+DeohLJGYEHKwP47gAl+GCUI7+ET2dh2ysqD0WovIevPnYdBYebhmoMGjSByHiDybWFFO7tMflODpZ7vwIbtCCwJn+2c6ZSrWiKCroZbXkwP6OdSGtHa1ptUzyKFS072C7gYkMRxnJ49ctHIpWxAofm/VEyGqoWCfbKQz9XTwZuJjapNrrXsARnC8f0Hw9GqsK5RdIkGtOvBYlOK0MpJ+zSiM5RSPtiU8VdSYSGGzOEwtuF/03as3Mo/5iFLWviAAgNch5RsSUAut/p43ytP4DimAUFGIzQe5jtM6zY3860Mfl+jq/a4RXfhvmODYi8kFvqzMjFa63HrQxGgV2vJhLFo9snU3cGS2CUGrS2MruqzHciN4rXTt1TW+ZXv8VA9pLXp9YSudLtUCAyCIVT8TttGSjn/URHTDzxtVpyGp11c9gctEo9tth90QiEDj55RZNRI3S7VVnpUNUuBhlaN5o2XRJ/tzdgLAxq9KTjGpttCj9MoP7MEtPbQ/5STMTtmfDC4SPSl/uF2EdZ5DXnkTGnemrVECSUWbDMZaU/NZw+CXpZP1EVo+4L/EJUuyLplYP4MatJil3xHymzunrk4sU72pUmcgv7I1P8Da/wp0JjE7joMhrDg==
    clientSecret: AgCaA3mO96jCarDtM1nkuN+OPYBSnoAxKCUPNxvaqq8BbyHK9Ozr7nmg6RLuBLBCLw4UuNu+P4fiPcY1DMXydXt/zsuROFEgfGroBp4TfsZSXY671pSy5FJgC/nErHBHruDcfWCINHBQ8N3O/SLgnkIcxcyCxkJUmp4OmxE15SKfJXaDXQe2Dll64zdbhdGelbKbbvLf3izzxR6t7hOo0y7caPqWV5ae+ftJgGZe9GAcmZKtpIsG/Rb/MC9gmknlJdqLUrFYOb7hG3e5pOqhCdmamaau/h5B5Cd8BXTLu99IZYva5y1BtyQ6UZs9IzANu6t+Yok2A+4crI4MjtHDf5gyGSnG02/GYnA501OjbV+3LrVMGKOqptYAc7r7dKsfrfbqLsf1duFFGD6PLbBKQYiN8w4+OMINQHgbm6z46+4TQM/aVBJZCVNDuWi/zjca8f/9yvRwYuWgXmOc35DiS6dx3Ue3svMYmx3Iq72l8Clnz4SKsQ3cdz3nhxwBm8Kn6dxYNSVIpuDY7IVz+WmCAYb9CO6ipxCOEyGYSQLfZ/mcYUZXcZ1Cy283LiGdpzFhSL7/WR1kmMrcgsBhegIloZ0H4hDFsqwbo9ANdx8M+5CwGpFPrko7aVkivYKrDWVlrt/CYvf1VMqDTCk3pmyddZA4KmCpkDu6bX+/zwLNpcwwt50pIEglQE97g44FDOtbNd+5YJPTej4KYdvntfoDK21lQP0jFV8gyyK4OaUpcj9GzZ3tuL76dADmzDOJJv2JM8HFe4dbkm3xOBjfu6iKfnt2
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: port-pr-reconcile-creds
      namespace: weyland
    type: Opaque
