---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: port-creds
  namespace: weyland
spec:
  encryptedData:
    PORT_CLIENT_ID: AgBlpGTTssZ6FF3exwfY0e7hIMxgc31Bhm7rDMWpDT4c4/Gx/ODR+v38buZoQkBKLGBWrc1C9OaxuuUmQg+Pw1omreX6elG1i6MD7kVUcRqTbkWF5MBAQ+JY++OPXaPg01Ko/sGQIo1n4rRcLPBtvlFZYK26iV8hB3roGhKIUjzEbgXlaPotC4RBWX6W76FnXqjuCic3K4IldZc/IBJEXKQS5g8o6ASkJ0ebV/uzv7n4xW/UQWJseK7UohF1258J43l0M2hRXAD0B9xnyqxWTnSQYRpvF9CoDoTztKSt+ImM/yunVUjqVfCwf4ldxeNAtI53I1jTz0nN21iaaaHY/y5TtDB9LlMcyFvHb2D95EmxiE21vShvCytFSRE7MjGisQBiQL5R8hMcNbczUR1JM2h0bZHRTCHzXQIaIeIp/gdBXXnKWpiNbmPAvHrukLE00B7Rl+VgQG8cJnDlYrI4ILVD3oE0BRGuHsVu1C6qCIfQLOlIEFvHqiTpFYFK1ktvVS+Uu/2kj9RNNz3XFDvo5cw9X+oe/q76zbMRHV9mlgsNNxoCVqICG8urd7f6qUeYLOP9p3gMu9wos6AQ8dGtKT7MjoaQo4baBJkOKvmTHWbgCUfDHDOKmg9b1PtGkByelecNx9c/r0LfpoU0e7KO9xtpE0eocBlznfPF3vxTrTVgABDQi8ep7GHlsLY4kuSnvMxbshBrdgRSnVy/Hjvm00EEvna9zzDDT6M1gca2rjx/xQ==
    PORT_CLIENT_SECRET: AgCiNTVRDZqyZzaHlJ5uNdGaxQSLS2HAGM8jk6AJQzE3zxSlh4i2h587LBxt2GKonXPq4JezmNsjI9XvniZcXLizepKnMhGBYRvaPSH2BW1Iq5QeZZEOhMPXWE9xO91tT5NDcfhzK+44ddziDNq6iUZ+kNL0QTNO5d1gz9XMiHfohxNcDfvh9ezYJaP8S+cqPjyT52uMrY9J5oHC/D+1kYqkezrBRNpwZqXh+vwQ8QWFgyrsqSLSvuBS4Oc/UMNg5XNJ1VHORufYMHPi2DnB69EYbpe1r63o26IJsItD6kDru/vgvWBVReB4MaYXwLdJ9BJyzMETx1jf07MBMdnHgpsFhKL3ireBvTlExfHDsRk5bKJrXo1zlZzL/tKvOlLp5/K+X9uXT32RrKzuT3iDdoYS8+JvgUA7xNMR7mcL2yK7bib/E6omn9ic97eo0QstRG94zXj5DEpTEhT5KFV/boSTbZNVBHmJgVvm72YdwNrWnrT/7pBw63nhQWeXLxBEuXK218WQ3gBmmE62RA/MsFQsHL+nVWsSYZSGIw08J7WT/9MlrXH4FZZjEkqCVWxRjUlvgANQfvZzlLqG0PTPtXfPHIKcwqY98MAyfwwCVWS1fVKLOyNHtSvqxEk7NeDGh8ZwFJ9a6QSN5u9zx1rhJY7Id1usbmxrFG63J40NmNFKm7HSuwYCTtyEf0TgBFE9KDOcPFfzkuuTdcR/JzApurgaIsVfoVS1D8aYsTXhz+VI1qHh7h4qIDkQgtJcipnhaGPRoVm42ALBJ4mGcgAOXfvg
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: port-creds
      namespace: weyland
    type: Opaque
