---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: port-ingest-url
  namespace: weyland
spec:
  encryptedData:
    url: AgCdA10vWs7uLsyXbdvgtKRGjh7XtVkIAAx6kj18jDs0fPhap1P5DbSVSUS+K9Uw0RJPzyDP+dK1vaUBzowXJhRJuhUT/3BS+ORKfmgeTozXuLOTS86LbLi73ErXJHVncp2LgK2wkon3FQ4XqjW2usWLqpQ2kYyQBZqT6dMWUy+ocobr8SurvJh0GpTwNKRItmC7hPoO/Q0Re9EL/6hMCKxRrT5ccZGuISFvF4LXdmetipI3LG35WxI+kJIuh2cxs4dWcQv878qSZoehUhJa1oiWGF7iRH6AgOh833oBMPwMFB93Sfp2/bHwbjRtRkFjXkBXf5mInngHSxl4x8cMhAYzxuAKii+s2SS2JNmsXmTlQ2yIlileZIrA1N/BhqnTA052KoI/giJ0hTH9ln2IrmPyrLlyxjKhA7sEa6h2Pb2SHg4jiBrGA6+HpDAbr1MdlD+nqFSJXhiEkwOtIFL8mJJMoIq5lBzxIsN95YoBXCiZI7ZceZKSOMarXDAEPQfBE+3VuHchORJRsEH4NFp/1zdAb9Fwq4qxTbevtKJV0IhPZKKisR0+kQEoKm2ATSsLJSo8M6PHlbxLoN3OhCw66nLx0gfrlVG+B2Ls4vXHboytJz1njXt0NSrNUlgz8HJtyCO14aIOY8UbEEUTYJpQDv5L0FKoAWdfzGHLVNA9QD/zGcA/15cBhkKKv+m0XIfVzZC+ngrnVzAe4NtIRGmLsR2is1uuapWJ1SZRNqplmTUc9BL0fVF/k/phzTM=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: port-ingest-url
      namespace: weyland
    type: Opaque
