---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mlflow-auth
  namespace: weyland
spec:
  encryptedData:
    users: AgBynoQWG07OnUJ7xe4AI3oAVgSPdQF5XElAvV6FLzyoiDyYvV5uDGPnpBSap6yIoozsHbrVX6VBUczhp6q4eVOfGHetxlv+jkrUm7aEh8tFGrLQH2FLvRl17GHastJfh/bbaQ1ytTwwyy54S/yBsWTF7xVEJFjI88cPr7NWoLWKgKFRunhCLOXT9g8W+xZZKf9R2o1JkkvPCR4xda06IvIqADG/vCeq2bB8MM6nYpGW0rWPifmHykZ67ejapYqEamcxK2aVKbMHynn/IkAQZBzSvVfkPaQrVEME5xZeZlLeIcN2JgVk8FtFordrJhJKGVRCjzmsS4UQ6fb+gnqbe3GOLN/Zl22sVLPOyjaKEDyQC74qYHYuyrhE4riqKtSZFHhI0XnXiGx27SbY8Ale8PmwPVZv9fUFSsp2T1U4K4pSQmrN+ttyb/N2i9/GbcczFx623AohQAnUzaPpFvfNSD5V8PEe7wAslPllTmB9LBe9nmO+E+31jQSlckNgmEUGvd3hfC/kvQf2YWenB2+Syw9PxD1pbZAUsA0eqClvaNnVqnAi83IBjetrtUBpAW/XVAooLkvumzG0Ws0YkZGN4JRXT8DlMePO4/a4v/6jV8PfNAv5IHssuZdEu8tqLf1Fps5T4zBx0u/Bww5CVwa0p/wmJogWvFneYqpAcQEpiAOZL/0SRmaCsbedv2R/jmPQ/P1vUH3i/cRmRoLYkHNvp97r8/EsZtQxelNlLS1qbedBfcvOYyjJfTC8pQcm
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: mlflow-auth
      namespace: weyland
    type: Opaque
