---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: registry-auth
  namespace: weyland
spec:
  encryptedData:
    users: AgAWOCoD9TfVYHw/gGhDGW4ZmQvNtEKw8NifMVXiZuJhugqn5qfLqtljy8J7p+rLHZ/J6JI5QXSfcUqrdpCuW6yhHcgs55Xu+bLSfdi/UyQ5K53ibD68JNk7LAIC9ehAklmDSIIyPhPIJsDLfQdwKDku/i0Mf8048ZmWHuDcJjZWg6HKniL5X24ywDnD683QHh4ygU8mp2Oa19L/0piDvAtkzw639a9gSlhATdJVy2n29yP9RTvz+oV24Qz0fCtrCKkLq5mESvkk0Ldp3wAfxJRAaA1+idJ5SSWbvbZ627V81o+JHwGir6Zd26O6F+G2z0M2jmJfzp2NRh39+jXvkPCoEeuV+n15txWXVOgjA8flIlB8pOzFQkHZ68gWRMSZy9JxnVtQchCwCi6xF2dG2tMrbg78Gi+DzJIOiibwWODlPV69ghK17VXzBAzyrHBJMlmSYzIMUa6bnuLFATq65rDK+/LXrXYrxKCvRec85raf5unhngLglEVnwUkvqvyTCE3CpwCNgjxSRSXlByucZOaUeVxCrH6jztyUDToU/6WUx+URSqI8WR5aYY5O6eNVn+jc41GrIdXuzsnwtohskqmk3+lkB2digwgXuZpFSmf6ECyJFQG+YHtma3B9viXiUm7BJiJbaIn2S0VXja2lscxkzO8Md9TjzC/+c0Ga9TosoEEt29Uh/xmGLot93cg2wqvdzf5iYP8/WnUKj1uc4+eKQJHzhxzg515gHLmKGlRjbo0BTOp3I9HRNc9u
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: registry-auth
      namespace: weyland
    type: Opaque
