---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: lakefs-creds
  namespace: weyland
spec:
  encryptedData:
    LAKEFS_ACCESS_KEY_ID: AgBN14iMvCI9bVaz3ZV3vO4V95OOuGbmBfn9u1DuUlWbF+3gQ9EfanGnEldy1sRx7SIf7RRsmZPv2U+ODTELyeHWYeKyjLcEp45W6ok1kQyr/c1fqMuYWZHa85FLz6c/sMSH6IvFSd2oQdrW2G78orZO1LRV+MxdxFOV/By4XzPE98sD+nQdAf8vF8vNgfguapeihxXaGZJOIdh5gtFCQdYsaj1Q7PISpj6lhoi+NxpWHAny//JkFzWzREZ/sKgMT6R3iwOYGhTMHS86Y87HOuF4EEqT0Wv6DE6znKsNMee3s9UI4zj37BpFGFadV4ZpNUigDeUFZVEvf5jmjw44bDaBTrSOKfGRDuRF78mG/CMBSyNok6ZH08gZYFJvGDo94wsAEGrth2Cygs8EwiW6C+lSCasPHKwB+w3G6FhJprd5dfE82jUlJZXRIHV1/eDBbblgQREm3uBGyL1d7N9UDwkdG+0qk88Vzr/oQ6j985VB9hWWm23p3L2Y3zUav5tALeztoxe0hSk20umQN2h7iKZE08cPT2LkaUUNrVH0TYPAyx53cmACGbcPd3xsfEHqNwSxDq5zKNVtHTa7XlaVJ1Kw7bAIIETOZwvmydCj5mUf1UrSjySBHu4T7310hfkc+T1jEQkQlZ8909AGUttW1hPp+ChBaWjd+iwXzIf84cJYRqoAfhNPThyKK42ZSNAmMlo0kPG7Pk0pfG1tQ12Z9sORp9SlsA==
    LAKEFS_SECRET_ACCESS_KEY: AgALGzSqmwq/NHUs/mO8dwpnOn4TOx4dpyRkFmDO/r3cuG7OZROXX8mp8EyZidSN2WUjVJvAVFJHTKGxTlqPytfF4Y3cTzH4KiDFfnMYle2HTA0bRNF2viPMhcQXkNSatP21bT3/T6cIj4PyIWvvI/iiyti6uQk8HIh7c7+CGplVrcpZJPzCY6A7aRJrd4P3eptNZ1mgQYV4bAoM7746HEU7InncUW2xyXajojPzQfnceWql+moVMFLFp00RWolFDNMTlKLlk6EbQdovvhiMlg5VCcbUypZR+b4/OGWlZVH/onMhYBtmOG6uzteTsYKC4BlGMnB0mqNYDdjW4d0SKIs/uz1tITNC8O248Vw8GriXExFxmpYUzkO/bBUDIzsn8P+bxXURJwJLnvNlf9o0GW/qhxLcbetkWD4udq5Yr3AHperU9jnK6Ifrr47nBjMG/Te+xJx1V7rdFPCsUi77Vm01kNf8jJq3gLFQ5tCqHHKjYhoTF1PvTbuPSAk6Oz1Hm+znufZK0m8VmhwK2sWnM01Z7+3HvdH5gDAQSpNYQ+BYIwqIV3DvOGEpegG7x5tlje5t62rQXdlRHwRk2fMNC2bitj41O7VB03JmqfsuXrGfrHFfX+6T4+z3y5Hecg7FOWOJboj5MGjpu+lwTTUhMqVuiB/sutekYZabGW0Aqujy62b6a+F9X9WvU2BWH9GlKaRnl644/ZWSf7qSHtpN7rJNxrcrCsqtAzg8/y0VTXCdGwrG7i8GRYXN
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: lakefs-creds
      namespace: weyland
    type: Opaque
