---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: lakefs-creds
  namespace: weyland
spec:
  encryptedData:
    LAKEFS_ACCESS_KEY_ID: AgAI/dzfLr/PQ7Fx8BbBXQRHZjMGuSBKB+76I7cMvFEYwBWZE3LmVn8epOz+Z6yUXC7/i/53E2TZJy1hyJTsx57EVbLNmdGKiKmjmPeE3HsmvG1V3gQ+4Xkf6T8Hs+CzftN23u7BJU6uLw3GVLYwNca8TdS7MJsGXV3eIJDFHdz2PwgQttDNHr3BLuyQ2cQr9bw2XK9hzsLFKMlNfZENGP5sIlWWkacjTWvfy6hxlunifiLhiMePAFAZoO2hZOHAJrEZW9nSpHJeyMMfIc7bOJ/ni9enLHbq55lhByRtsJBLZTg1dNXqcpdlCX+fUKKt5t1LX/r4U0S9zDGgNIsU09ROR7WqvuNtvTMn7H1hyGN3gVe04P8tZxGyG4Apy7jkTTyl4bQ3c4IwYqKRCGnnnVWZKaGpREJj+efywRdm35dIrq8DdRjSLWBYQfjO9JK5XUVlXJFooYmpOG4bTLFTiKsXfWL++RtNJYO1SR54rZ3IMfrfcCLvO37udc5WHksffyWnuOiYh7Y5P8II8mSJYbrFqDIsKe/KqVzB3IB5RZV5nsBlm+Fwe+nmFLK3+cwCcR2AIL2CWbUylcPDW3AO9om7AuYCkg91yDmmfho/mebAbmjMyW5duHtYDDvK56Yo6KFlxDacoi9bXxbNwWY/YzOdkgNxkWIwPzSXJi3NN9IJUfQ+PcYuluh8297fgOBnSDX7q6re/lOOrOi1NxxEQfd34X0oYQ==
    LAKEFS_SECRET_ACCESS_KEY: AgBXLkhTj0lXS3GDLJZRxa+KMqvYMVRftpzNC2ilAncXMAOtb7ai8OPVBuUbVGFKSxXicyWAw6mw2SyioBvv2TEnfKfM0lpo4mppCbz0DNXgEkAodC3pfBx9ztOtN8+jovnyfIWlFrPYGkgnykLR6OwJYb4iWZVxvWGX1bL64x3NHjpb+ZTpVWxgGrVNwuR58p9+EEWYoD+kp1PI/lSBXd2oUSoRR0D05q7shFRVMew8IW/KNyCYdfbOf3dEhov60Zdcmlbgm/Qpp8eI9mFm/uC9UgAO2+vf2PPW8H8Cu3+Vd2IEe0b8tQBU6IcApI/6XIXdUi0IuGAH3gHW0z383V1Y6kxw1K8TVwMNcqfCIOynLY8s8J6DN95Fx0HVtZ4JsDpBQTeEJjj3gtdg3IF5z5VhgTPC/3iQiPAyAqbq2wCY5MoZWGaNH04WRIn8y+79QAxs8S9b7/UWrGrzVjryrhlFFso6MHpQd7MwkBH33YNY/SRP77pfFfWQWHsf32nNJuvUBV8Xr1fDZqBkv2gQsb0+SfnoO38t8n4gIipltJBl3xEdNfB8v1ouYYkAHh0HxG+qOuWws1NBeiYn5UmJ8TC7ajBGiUKNXVdpQvmRCOqArIZFYRtWEzypDdhLwDMp1myyKx2xASeMmuIqwr8cZvdPLfFGEJz2lq628zBABIFIbMCrxKbRm8IiS1TpAQB9q2f2H+4ym3giweDH4WlR9zs9U/zkUQvGEyyiK3GdRCjUtxjIj59DEcZc
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: lakefs-creds
      namespace: weyland
    type: Opaque
