---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: woodpecker-default-agent-secret
  namespace: woodpecker
spec:
  encryptedData:
    WOODPECKER_AGENT_SECRET: AgCn4Q2IBROWWniIAnsXOhqS7LTQfv/kwE2UOwNPO19ijRT8rXx+/ojTc9UU/9Q0ifwt20YgyfajtnTHXWIPVALSF2yWagwV9V7VYOz71RV6LhDYyNESCq0x79TqzCj+yvuFauQMjlZdLP0tzEYx5oETd248MCrWuimtXmk3frgwXn/48v123A2Hl6SMH2LxNedViwMqayFqE5l12Modp+eeB3XL2PUgsO4WO45wBRpzRx0Yn53YFJj6inVo0FaE3y5gBCxvZjJapFE9dwkQGIuzvQ+NeiXHcBDGVgQFn9gwLBBeBUK9xC6zvu/I24gQDPvELvqTUSJUK7k9/I0HqCC00nzC3I4A7YywlHTQPdAwXW6IawLsUNFYVnCe9VQCXjdFbDe5Xnt+IZ/vbj+tYh9UIzxexolOmKcH27cCt8c974Wl7kF7Ew3ddE5lZ1yZiKcBc+sKlQPre8HjnrvBp/83YL2GTWAu+KnvCGg2QTTjU5bfk6VCpzT73HbYYKYjIB1kz1folMN48xORvUcmC40uO/bMzJJuS55119X2j6wbo+1y9KBa2lTXOAb2wOnWboqZyxKrmueTu7sU2MRNJ/9RkiJxhqU0z+ChjbVMT3Z4SCFPdhuz51hzopSREPoKTLQYdgaYaheSqo/IboScA2mTKLsOiAanm/1B/tVFLgglqbx6BqoP8VxOuuzLE4iepdSeQybL4ZqOFxtAGxCKiW62bS9oX5oEjzNgF2GgRBiWFcNkiyNb0Bx5Y5Lc7w4RaxjiMymgzcnIVzQSfaeV+LrX
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: woodpecker-default-agent-secret
      namespace: woodpecker
