#!/usr/bin/env bash
# Regenerate the api-drift CronJob's ConfigMap from the repo sources, keeping the embedded copies
# byte-identical to the originals (api-drift.bats asserts it). Run after editing the engine, the runner,
# the catalog, or any contract snapshot.
#
#   usage: scripts/embed-api-drift.sh
#
# The ConfigMap carries everything the in-cluster runner needs (no repo, no kubectl): the breaking-change
# engine, the drift runner, apis.yaml, and every contract snapshot — all mounted flat at /opt/api-drift,
# which is both the module dir and the specs dir the runner reads.
set -euo pipefail
here="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="$here/nodes/mother/lab/weyland-platform/k8s/monitoring/api-drift-configmap.yaml"

python3 - "$here" "$OUT" <<'PY'
import glob, os, sys
root, out = sys.argv[1], sys.argv[2]
files = [
    ("api_spec_diff.py", f"{root}/scripts/lib/api_spec_diff.py"),
    ("api_drift.py", f"{root}/scripts/lib/api_drift.py"),
    ("apis.yaml", f"{root}/nodes/mother/lab/weyland-platform/services/weyland-dagster/weyland_pipeline/apis.yaml"),
]
for spec in sorted(glob.glob(f"{root}/docs/api/specs/*.json")):
    files.append((os.path.basename(spec), spec))

lines = [
    "# GENERATED by scripts/embed-api-drift.sh — DO NOT EDIT. Edit the sources under scripts/lib/,",
    "# the apis.yaml catalog, or docs/api/specs/, then re-run the embed script. api-drift.bats asserts",
    "# the embedded engine + runner are byte-identical to the repo copies.",
    "apiVersion: v1",
    "kind: ConfigMap",
    "metadata:",
    "  name: api-drift-logic",
    "  namespace: monitoring",
    "data:",
]
for key, path in files:
    lines.append(f"  {key}: |")
    for ln in open(path).read().rstrip("\n").split("\n"):
        lines.append("    " + ln if ln else "")
with open(out, "w") as fh:
    fh.write("\n".join(lines).rstrip("\n") + "\n")
print(f"embedded {len(files)} files into {os.path.basename(out)}")
PY
