apiVersion: v1
kind: Service
metadata:
  name: weyland-agent
  namespace: weyland
  labels:
    app: weyland-agent   # selected by the ServiceMonitor
spec:
  type: ClusterIP
  selector:
    app: weyland-agent
  ports:
    - name: http
      port: 8080
      targetPort: 8080
