# B17+B19 MCP gateway — per-agent client_credentials clients.
#
# One Keycloak client PER agent (not a shared "agents" client) so the token's `azp` claim is meaningful: the
# weyland-mcp-gateway forwards `azp` as X-Forwarded-Consumer → guardrail_verdicts.actor, so per-agent clients give a
# per-agent actor (which is the whole point of injecting identity, and what the enforcing act gate keys on).
#
# These are SERVICE-ACCOUNT (machine) clients: service_accounts_enabled = client_credentials grant, no browser flow.
# The operator (B66) is the first agent (the act consumer). Add weyland-agent / coding-agents the same way as they
# gain the ability to present a Bearer token on the MCP endpoint.

resource "keycloak_openid_client" "mcp_operator" {
  realm_id  = keycloak_realm.weyland.id
  client_id = "weyland-operator"
  name      = "MCP agent — weyland-operator (B66)"
  enabled   = true

  access_type                  = "CONFIDENTIAL"
  service_accounts_enabled     = true  # client_credentials grant + a service-account user (machine identity)
  standard_flow_enabled        = false # no browser / auth-code flow
  direct_access_grants_enabled = false # no password grant
}

# The client secret is generated by Keycloak. Surface it (sensitive) so it can be wired into the operator's env as a
# k8s Secret (out-of-band / sealed — never committed). The operator does: POST .../token client_id+secret → access_token.
output "mcp_operator_client_secret" {
  value     = keycloak_openid_client.mcp_operator.client_secret
  sensitive = true
}
